// Code generated by ent, DO NOT EDIT.

package emaillabel

import (
	"clockzen-next/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldID, id))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldConnectionID, v))
}

// ProviderLabelID applies equality check predicate on the "provider_label_id" field. It's identical to ProviderLabelIDEQ.
func ProviderLabelID(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldProviderLabelID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldDisplayName, v))
}

// ParentLabelID applies equality check predicate on the "parent_label_id" field. It's identical to ParentLabelIDEQ.
func ParentLabelID(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldParentLabelID, v))
}

// SyncEnabled applies equality check predicate on the "sync_enabled" field. It's identical to SyncEnabledEQ.
func SyncEnabled(v bool) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldSyncEnabled, v))
}

// MessageCount applies equality check predicate on the "message_count" field. It's identical to MessageCountEQ.
func MessageCount(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldMessageCount, v))
}

// UnreadCount applies equality check predicate on the "unread_count" field. It's identical to UnreadCountEQ.
func UnreadCount(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldUnreadCount, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldColor, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastScannedAt applies equality check predicate on the "last_scanned_at" field. It's identical to LastScannedAtEQ.
func LastScannedAt(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldLastScannedAt, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDGT applies the GT predicate on the "connection_id" field.
func ConnectionIDGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldConnectionID, v))
}

// ConnectionIDGTE applies the GTE predicate on the "connection_id" field.
func ConnectionIDGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldConnectionID, v))
}

// ConnectionIDLT applies the LT predicate on the "connection_id" field.
func ConnectionIDLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldConnectionID, v))
}

// ConnectionIDLTE applies the LTE predicate on the "connection_id" field.
func ConnectionIDLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldConnectionID, v))
}

// ConnectionIDContains applies the Contains predicate on the "connection_id" field.
func ConnectionIDContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldConnectionID, v))
}

// ConnectionIDHasPrefix applies the HasPrefix predicate on the "connection_id" field.
func ConnectionIDHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldConnectionID, v))
}

// ConnectionIDHasSuffix applies the HasSuffix predicate on the "connection_id" field.
func ConnectionIDHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldConnectionID, v))
}

// ConnectionIDEqualFold applies the EqualFold predicate on the "connection_id" field.
func ConnectionIDEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldConnectionID, v))
}

// ConnectionIDContainsFold applies the ContainsFold predicate on the "connection_id" field.
func ConnectionIDContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldConnectionID, v))
}

// ProviderLabelIDEQ applies the EQ predicate on the "provider_label_id" field.
func ProviderLabelIDEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldProviderLabelID, v))
}

// ProviderLabelIDNEQ applies the NEQ predicate on the "provider_label_id" field.
func ProviderLabelIDNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldProviderLabelID, v))
}

// ProviderLabelIDIn applies the In predicate on the "provider_label_id" field.
func ProviderLabelIDIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldProviderLabelID, vs...))
}

// ProviderLabelIDNotIn applies the NotIn predicate on the "provider_label_id" field.
func ProviderLabelIDNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldProviderLabelID, vs...))
}

// ProviderLabelIDGT applies the GT predicate on the "provider_label_id" field.
func ProviderLabelIDGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldProviderLabelID, v))
}

// ProviderLabelIDGTE applies the GTE predicate on the "provider_label_id" field.
func ProviderLabelIDGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldProviderLabelID, v))
}

// ProviderLabelIDLT applies the LT predicate on the "provider_label_id" field.
func ProviderLabelIDLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldProviderLabelID, v))
}

// ProviderLabelIDLTE applies the LTE predicate on the "provider_label_id" field.
func ProviderLabelIDLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldProviderLabelID, v))
}

// ProviderLabelIDContains applies the Contains predicate on the "provider_label_id" field.
func ProviderLabelIDContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldProviderLabelID, v))
}

// ProviderLabelIDHasPrefix applies the HasPrefix predicate on the "provider_label_id" field.
func ProviderLabelIDHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldProviderLabelID, v))
}

// ProviderLabelIDHasSuffix applies the HasSuffix predicate on the "provider_label_id" field.
func ProviderLabelIDHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldProviderLabelID, v))
}

// ProviderLabelIDEqualFold applies the EqualFold predicate on the "provider_label_id" field.
func ProviderLabelIDEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldProviderLabelID, v))
}

// ProviderLabelIDContainsFold applies the ContainsFold predicate on the "provider_label_id" field.
func ProviderLabelIDContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldProviderLabelID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldDisplayName, v))
}

// LabelTypeEQ applies the EQ predicate on the "label_type" field.
func LabelTypeEQ(v LabelType) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldLabelType, v))
}

// LabelTypeNEQ applies the NEQ predicate on the "label_type" field.
func LabelTypeNEQ(v LabelType) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldLabelType, v))
}

// LabelTypeIn applies the In predicate on the "label_type" field.
func LabelTypeIn(vs ...LabelType) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldLabelType, vs...))
}

// LabelTypeNotIn applies the NotIn predicate on the "label_type" field.
func LabelTypeNotIn(vs ...LabelType) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldLabelType, vs...))
}

// ParentLabelIDEQ applies the EQ predicate on the "parent_label_id" field.
func ParentLabelIDEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldParentLabelID, v))
}

// ParentLabelIDNEQ applies the NEQ predicate on the "parent_label_id" field.
func ParentLabelIDNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldParentLabelID, v))
}

// ParentLabelIDIn applies the In predicate on the "parent_label_id" field.
func ParentLabelIDIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldParentLabelID, vs...))
}

// ParentLabelIDNotIn applies the NotIn predicate on the "parent_label_id" field.
func ParentLabelIDNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldParentLabelID, vs...))
}

// ParentLabelIDGT applies the GT predicate on the "parent_label_id" field.
func ParentLabelIDGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldParentLabelID, v))
}

// ParentLabelIDGTE applies the GTE predicate on the "parent_label_id" field.
func ParentLabelIDGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldParentLabelID, v))
}

// ParentLabelIDLT applies the LT predicate on the "parent_label_id" field.
func ParentLabelIDLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldParentLabelID, v))
}

// ParentLabelIDLTE applies the LTE predicate on the "parent_label_id" field.
func ParentLabelIDLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldParentLabelID, v))
}

// ParentLabelIDContains applies the Contains predicate on the "parent_label_id" field.
func ParentLabelIDContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldParentLabelID, v))
}

// ParentLabelIDHasPrefix applies the HasPrefix predicate on the "parent_label_id" field.
func ParentLabelIDHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldParentLabelID, v))
}

// ParentLabelIDHasSuffix applies the HasSuffix predicate on the "parent_label_id" field.
func ParentLabelIDHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldParentLabelID, v))
}

// ParentLabelIDIsNil applies the IsNil predicate on the "parent_label_id" field.
func ParentLabelIDIsNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIsNull(FieldParentLabelID))
}

// ParentLabelIDNotNil applies the NotNil predicate on the "parent_label_id" field.
func ParentLabelIDNotNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotNull(FieldParentLabelID))
}

// ParentLabelIDEqualFold applies the EqualFold predicate on the "parent_label_id" field.
func ParentLabelIDEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldParentLabelID, v))
}

// ParentLabelIDContainsFold applies the ContainsFold predicate on the "parent_label_id" field.
func ParentLabelIDContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldParentLabelID, v))
}

// SyncEnabledEQ applies the EQ predicate on the "sync_enabled" field.
func SyncEnabledEQ(v bool) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldSyncEnabled, v))
}

// SyncEnabledNEQ applies the NEQ predicate on the "sync_enabled" field.
func SyncEnabledNEQ(v bool) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldSyncEnabled, v))
}

// MessageCountEQ applies the EQ predicate on the "message_count" field.
func MessageCountEQ(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldMessageCount, v))
}

// MessageCountNEQ applies the NEQ predicate on the "message_count" field.
func MessageCountNEQ(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldMessageCount, v))
}

// MessageCountIn applies the In predicate on the "message_count" field.
func MessageCountIn(vs ...int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldMessageCount, vs...))
}

// MessageCountNotIn applies the NotIn predicate on the "message_count" field.
func MessageCountNotIn(vs ...int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldMessageCount, vs...))
}

// MessageCountGT applies the GT predicate on the "message_count" field.
func MessageCountGT(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldMessageCount, v))
}

// MessageCountGTE applies the GTE predicate on the "message_count" field.
func MessageCountGTE(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldMessageCount, v))
}

// MessageCountLT applies the LT predicate on the "message_count" field.
func MessageCountLT(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldMessageCount, v))
}

// MessageCountLTE applies the LTE predicate on the "message_count" field.
func MessageCountLTE(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldMessageCount, v))
}

// UnreadCountEQ applies the EQ predicate on the "unread_count" field.
func UnreadCountEQ(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldUnreadCount, v))
}

// UnreadCountNEQ applies the NEQ predicate on the "unread_count" field.
func UnreadCountNEQ(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldUnreadCount, v))
}

// UnreadCountIn applies the In predicate on the "unread_count" field.
func UnreadCountIn(vs ...int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldUnreadCount, vs...))
}

// UnreadCountNotIn applies the NotIn predicate on the "unread_count" field.
func UnreadCountNotIn(vs ...int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldUnreadCount, vs...))
}

// UnreadCountGT applies the GT predicate on the "unread_count" field.
func UnreadCountGT(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldUnreadCount, v))
}

// UnreadCountGTE applies the GTE predicate on the "unread_count" field.
func UnreadCountGTE(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldUnreadCount, v))
}

// UnreadCountLT applies the LT predicate on the "unread_count" field.
func UnreadCountLT(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldUnreadCount, v))
}

// UnreadCountLTE applies the LTE predicate on the "unread_count" field.
func UnreadCountLTE(v int64) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldUnreadCount, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldContainsFold(FieldColor, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastScannedAtEQ applies the EQ predicate on the "last_scanned_at" field.
func LastScannedAtEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldEQ(FieldLastScannedAt, v))
}

// LastScannedAtNEQ applies the NEQ predicate on the "last_scanned_at" field.
func LastScannedAtNEQ(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNEQ(FieldLastScannedAt, v))
}

// LastScannedAtIn applies the In predicate on the "last_scanned_at" field.
func LastScannedAtIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIn(FieldLastScannedAt, vs...))
}

// LastScannedAtNotIn applies the NotIn predicate on the "last_scanned_at" field.
func LastScannedAtNotIn(vs ...time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotIn(FieldLastScannedAt, vs...))
}

// LastScannedAtGT applies the GT predicate on the "last_scanned_at" field.
func LastScannedAtGT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGT(FieldLastScannedAt, v))
}

// LastScannedAtGTE applies the GTE predicate on the "last_scanned_at" field.
func LastScannedAtGTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldGTE(FieldLastScannedAt, v))
}

// LastScannedAtLT applies the LT predicate on the "last_scanned_at" field.
func LastScannedAtLT(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLT(FieldLastScannedAt, v))
}

// LastScannedAtLTE applies the LTE predicate on the "last_scanned_at" field.
func LastScannedAtLTE(v time.Time) predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldLTE(FieldLastScannedAt, v))
}

// LastScannedAtIsNil applies the IsNil predicate on the "last_scanned_at" field.
func LastScannedAtIsNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldIsNull(FieldLastScannedAt))
}

// LastScannedAtNotNil applies the NotNil predicate on the "last_scanned_at" field.
func LastScannedAtNotNil() predicate.EmailLabel {
	return predicate.EmailLabel(sql.FieldNotNull(FieldLastScannedAt))
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.EmailLabel {
	return predicate.EmailLabel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.EmailConnection) predicate.EmailLabel {
	return predicate.EmailLabel(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailLabel) predicate.EmailLabel {
	return predicate.EmailLabel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailLabel) predicate.EmailLabel {
	return predicate.EmailLabel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailLabel) predicate.EmailLabel {
	return predicate.EmailLabel(sql.NotPredicates(p))
}
