// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EmailConnectionsColumns holds the columns for the "email_connections" table.
	EmailConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "provider_account_id", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"gmail", "outlook", "imap"}},
		{Name: "access_token", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString},
		{Name: "token_expiry", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "revoked", "expired"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_sync_at", Type: field.TypeTime, Nullable: true},
	}
	// EmailConnectionsTable holds the schema information for the "email_connections" table.
	EmailConnectionsTable = &schema.Table{
		Name:       "email_connections",
		Columns:    EmailConnectionsColumns,
		PrimaryKey: []*schema.Column{EmailConnectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "emailconnection_user_id",
				Unique:  false,
				Columns: []*schema.Column{EmailConnectionsColumns[1]},
			},
			{
				Name:    "emailconnection_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{EmailConnectionsColumns[2]},
			},
			{
				Name:    "emailconnection_status",
				Unique:  false,
				Columns: []*schema.Column{EmailConnectionsColumns[8]},
			},
			{
				Name:    "emailconnection_provider",
				Unique:  false,
				Columns: []*schema.Column{EmailConnectionsColumns[4]},
			},
		},
	}
	// EmailLabelsColumns holds the columns for the "email_labels" table.
	EmailLabelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "provider_label_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "label_type", Type: field.TypeEnum, Enums: []string{"system", "user", "category"}, Default: "user"},
		{Name: "parent_label_id", Type: field.TypeString, Nullable: true},
		{Name: "sync_enabled", Type: field.TypeBool, Default: true},
		{Name: "message_count", Type: field.TypeInt64, Default: 0},
		{Name: "unread_count", Type: field.TypeInt64, Default: 0},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_scanned_at", Type: field.TypeTime, Nullable: true},
		{Name: "connection_id", Type: field.TypeString},
	}
	// EmailLabelsTable holds the schema information for the "email_labels" table.
	EmailLabelsTable = &schema.Table{
		Name:       "email_labels",
		Columns:    EmailLabelsColumns,
		PrimaryKey: []*schema.Column{EmailLabelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "email_labels_email_connections_labels",
				Columns:    []*schema.Column{EmailLabelsColumns[13]},
				RefColumns: []*schema.Column{EmailConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "emaillabel_connection_id",
				Unique:  false,
				Columns: []*schema.Column{EmailLabelsColumns[13]},
			},
			{
				Name:    "emaillabel_provider_label_id",
				Unique:  false,
				Columns: []*schema.Column{EmailLabelsColumns[1]},
			},
			{
				Name:    "emaillabel_connection_id_provider_label_id",
				Unique:  true,
				Columns: []*schema.Column{EmailLabelsColumns[13], EmailLabelsColumns[1]},
			},
			{
				Name:    "emaillabel_sync_enabled",
				Unique:  false,
				Columns: []*schema.Column{EmailLabelsColumns[6]},
			},
			{
				Name:    "emaillabel_label_type",
				Unique:  false,
				Columns: []*schema.Column{EmailLabelsColumns[4]},
			},
		},
	}
	// EmailSyncsColumns holds the columns for the "email_syncs" table.
	EmailSyncsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "label_id", Type: field.TypeString, Nullable: true},
		{Name: "sync_type", Type: field.TypeEnum, Enums: []string{"full", "incremental", "manual"}, Default: "incremental"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed", "cancelled"}, Default: "pending"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "messages_scanned", Type: field.TypeInt, Default: 0},
		{Name: "messages_downloaded", Type: field.TypeInt, Default: 0},
		{Name: "messages_indexed", Type: field.TypeInt, Default: 0},
		{Name: "messages_failed", Type: field.TypeInt, Default: 0},
		{Name: "attachments_downloaded", Type: field.TypeInt, Default: 0},
		{Name: "bytes_transferred", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "error_details", Type: field.TypeJSON, Nullable: true},
		{Name: "history_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "connection_id", Type: field.TypeString},
	}
	// EmailSyncsTable holds the schema information for the "email_syncs" table.
	EmailSyncsTable = &schema.Table{
		Name:       "email_syncs",
		Columns:    EmailSyncsColumns,
		PrimaryKey: []*schema.Column{EmailSyncsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "email_syncs_email_connections_syncs",
				Columns:    []*schema.Column{EmailSyncsColumns[17]},
				RefColumns: []*schema.Column{EmailConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "emailsync_connection_id",
				Unique:  false,
				Columns: []*schema.Column{EmailSyncsColumns[17]},
			},
			{
				Name:    "emailsync_status",
				Unique:  false,
				Columns: []*schema.Column{EmailSyncsColumns[3]},
			},
			{
				Name:    "emailsync_sync_type",
				Unique:  false,
				Columns: []*schema.Column{EmailSyncsColumns[2]},
			},
			{
				Name:    "emailsync_connection_id_status",
				Unique:  false,
				Columns: []*schema.Column{EmailSyncsColumns[17], EmailSyncsColumns[3]},
			},
			{
				Name:    "emailsync_created_at",
				Unique:  false,
				Columns: []*schema.Column{EmailSyncsColumns[15]},
			},
		},
	}
	// GoogleDriveConnectionsColumns holds the columns for the "google_drive_connections" table.
	GoogleDriveConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "google_account_id", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "access_token", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString},
		{Name: "token_expiry", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "revoked", "expired"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_sync_at", Type: field.TypeTime, Nullable: true},
	}
	// GoogleDriveConnectionsTable holds the schema information for the "google_drive_connections" table.
	GoogleDriveConnectionsTable = &schema.Table{
		Name:       "google_drive_connections",
		Columns:    GoogleDriveConnectionsColumns,
		PrimaryKey: []*schema.Column{GoogleDriveConnectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "googledriveconnection_user_id",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveConnectionsColumns[1]},
			},
			{
				Name:    "googledriveconnection_google_account_id",
				Unique:  true,
				Columns: []*schema.Column{GoogleDriveConnectionsColumns[2]},
			},
			{
				Name:    "googledriveconnection_status",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveConnectionsColumns[7]},
			},
		},
	}
	// GoogleDriveFoldersColumns holds the columns for the "google_drive_folders" table.
	GoogleDriveFoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "drive_folder_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Nullable: true},
		{Name: "parent_folder_id", Type: field.TypeString, Nullable: true},
		{Name: "is_root", Type: field.TypeBool, Default: false},
		{Name: "sync_enabled", Type: field.TypeBool, Default: true},
		{Name: "sync_direction", Type: field.TypeEnum, Enums: []string{"download", "upload", "bidirectional"}, Default: "download"},
		{Name: "file_count", Type: field.TypeInt64, Default: 0},
		{Name: "total_size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_scanned_at", Type: field.TypeTime, Nullable: true},
		{Name: "connection_id", Type: field.TypeString},
	}
	// GoogleDriveFoldersTable holds the schema information for the "google_drive_folders" table.
	GoogleDriveFoldersTable = &schema.Table{
		Name:       "google_drive_folders",
		Columns:    GoogleDriveFoldersColumns,
		PrimaryKey: []*schema.Column{GoogleDriveFoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "google_drive_folders_google_drive_connections_folders",
				Columns:    []*schema.Column{GoogleDriveFoldersColumns[13]},
				RefColumns: []*schema.Column{GoogleDriveConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "googledrivefolder_connection_id",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveFoldersColumns[13]},
			},
			{
				Name:    "googledrivefolder_drive_folder_id",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveFoldersColumns[1]},
			},
			{
				Name:    "googledrivefolder_connection_id_drive_folder_id",
				Unique:  true,
				Columns: []*schema.Column{GoogleDriveFoldersColumns[13], GoogleDriveFoldersColumns[1]},
			},
			{
				Name:    "googledrivefolder_sync_enabled",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveFoldersColumns[6]},
			},
		},
	}
	// GoogleDriveSyncsColumns holds the columns for the "google_drive_syncs" table.
	GoogleDriveSyncsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "folder_id", Type: field.TypeString, Nullable: true},
		{Name: "sync_type", Type: field.TypeEnum, Enums: []string{"full", "incremental", "manual"}, Default: "incremental"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed", "cancelled"}, Default: "pending"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "files_scanned", Type: field.TypeInt, Default: 0},
		{Name: "files_downloaded", Type: field.TypeInt, Default: 0},
		{Name: "files_uploaded", Type: field.TypeInt, Default: 0},
		{Name: "files_deleted", Type: field.TypeInt, Default: 0},
		{Name: "files_failed", Type: field.TypeInt, Default: 0},
		{Name: "bytes_transferred", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "error_details", Type: field.TypeJSON, Nullable: true},
		{Name: "change_token", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "connection_id", Type: field.TypeString},
	}
	// GoogleDriveSyncsTable holds the schema information for the "google_drive_syncs" table.
	GoogleDriveSyncsTable = &schema.Table{
		Name:       "google_drive_syncs",
		Columns:    GoogleDriveSyncsColumns,
		PrimaryKey: []*schema.Column{GoogleDriveSyncsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "google_drive_syncs_google_drive_connections_syncs",
				Columns:    []*schema.Column{GoogleDriveSyncsColumns[17]},
				RefColumns: []*schema.Column{GoogleDriveConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "googledrivesync_connection_id",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveSyncsColumns[17]},
			},
			{
				Name:    "googledrivesync_status",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveSyncsColumns[3]},
			},
			{
				Name:    "googledrivesync_sync_type",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveSyncsColumns[2]},
			},
			{
				Name:    "googledrivesync_connection_id_status",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveSyncsColumns[17], GoogleDriveSyncsColumns[3]},
			},
			{
				Name:    "googledrivesync_created_at",
				Unique:  false,
				Columns: []*schema.Column{GoogleDriveSyncsColumns[15]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EmailConnectionsTable,
		EmailLabelsTable,
		EmailSyncsTable,
		GoogleDriveConnectionsTable,
		GoogleDriveFoldersTable,
		GoogleDriveSyncsTable,
	}
)

func init() {
	EmailLabelsTable.ForeignKeys[0].RefTable = EmailConnectionsTable
	EmailSyncsTable.ForeignKeys[0].RefTable = EmailConnectionsTable
	GoogleDriveFoldersTable.ForeignKeys[0].RefTable = GoogleDriveConnectionsTable
	GoogleDriveSyncsTable.ForeignKeys[0].RefTable = GoogleDriveConnectionsTable
}
