// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emaillabel"
	"clockzen-next/internal/ent/emailsync"
	"clockzen-next/internal/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailConnectionQuery is the builder for querying EmailConnection entities.
type EmailConnectionQuery struct {
	config
	ctx        *QueryContext
	order      []emailconnection.OrderOption
	inters     []Interceptor
	predicates []predicate.EmailConnection
	withLabels *EmailLabelQuery
	withSyncs  *EmailSyncQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmailConnectionQuery builder.
func (_q *EmailConnectionQuery) Where(ps ...predicate.EmailConnection) *EmailConnectionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EmailConnectionQuery) Limit(limit int) *EmailConnectionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EmailConnectionQuery) Offset(offset int) *EmailConnectionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EmailConnectionQuery) Unique(unique bool) *EmailConnectionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EmailConnectionQuery) Order(o ...emailconnection.OrderOption) *EmailConnectionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLabels chains the current query on the "labels" edge.
func (_q *EmailConnectionQuery) QueryLabels() *EmailLabelQuery {
	query := (&EmailLabelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(emailconnection.Table, emailconnection.FieldID, selector),
			sqlgraph.To(emaillabel.Table, emaillabel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, emailconnection.LabelsTable, emailconnection.LabelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySyncs chains the current query on the "syncs" edge.
func (_q *EmailConnectionQuery) QuerySyncs() *EmailSyncQuery {
	query := (&EmailSyncClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(emailconnection.Table, emailconnection.FieldID, selector),
			sqlgraph.To(emailsync.Table, emailsync.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, emailconnection.SyncsTable, emailconnection.SyncsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EmailConnection entity from the query.
// Returns a *NotFoundError when no EmailConnection was found.
func (_q *EmailConnectionQuery) First(ctx context.Context) (*EmailConnection, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emailconnection.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EmailConnectionQuery) FirstX(ctx context.Context) *EmailConnection {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmailConnection ID from the query.
// Returns a *NotFoundError when no EmailConnection ID was found.
func (_q *EmailConnectionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emailconnection.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EmailConnectionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmailConnection entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmailConnection entity is found.
// Returns a *NotFoundError when no EmailConnection entities are found.
func (_q *EmailConnectionQuery) Only(ctx context.Context) (*EmailConnection, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emailconnection.Label}
	default:
		return nil, &NotSingularError{emailconnection.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EmailConnectionQuery) OnlyX(ctx context.Context) *EmailConnection {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmailConnection ID in the query.
// Returns a *NotSingularError when more than one EmailConnection ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EmailConnectionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emailconnection.Label}
	default:
		err = &NotSingularError{emailconnection.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EmailConnectionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmailConnections.
func (_q *EmailConnectionQuery) All(ctx context.Context) ([]*EmailConnection, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmailConnection, *EmailConnectionQuery]()
	return withInterceptors[[]*EmailConnection](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EmailConnectionQuery) AllX(ctx context.Context) []*EmailConnection {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmailConnection IDs.
func (_q *EmailConnectionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(emailconnection.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EmailConnectionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EmailConnectionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EmailConnectionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EmailConnectionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EmailConnectionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EmailConnectionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmailConnectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EmailConnectionQuery) Clone() *EmailConnectionQuery {
	if _q == nil {
		return nil
	}
	return &EmailConnectionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]emailconnection.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.EmailConnection{}, _q.predicates...),
		withLabels: _q.withLabels.Clone(),
		withSyncs:  _q.withSyncs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLabels tells the query-builder to eager-load the nodes that are connected to
// the "labels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EmailConnectionQuery) WithLabels(opts ...func(*EmailLabelQuery)) *EmailConnectionQuery {
	query := (&EmailLabelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLabels = query
	return _q
}

// WithSyncs tells the query-builder to eager-load the nodes that are connected to
// the "syncs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EmailConnectionQuery) WithSyncs(opts ...func(*EmailSyncQuery)) *EmailConnectionQuery {
	query := (&EmailSyncClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSyncs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmailConnection.Query().
//		GroupBy(emailconnection.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EmailConnectionQuery) GroupBy(field string, fields ...string) *EmailConnectionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmailConnectionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = emailconnection.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.EmailConnection.Query().
//		Select(emailconnection.FieldUserID).
//		Scan(ctx, &v)
func (_q *EmailConnectionQuery) Select(fields ...string) *EmailConnectionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EmailConnectionSelect{EmailConnectionQuery: _q}
	sbuild.label = emailconnection.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmailConnectionSelect configured with the given aggregations.
func (_q *EmailConnectionQuery) Aggregate(fns ...AggregateFunc) *EmailConnectionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EmailConnectionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !emailconnection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EmailConnectionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmailConnection, error) {
	var (
		nodes       = []*EmailConnection{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLabels != nil,
			_q.withSyncs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmailConnection).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmailConnection{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLabels; query != nil {
		if err := _q.loadLabels(ctx, query, nodes,
			func(n *EmailConnection) { n.Edges.Labels = []*EmailLabel{} },
			func(n *EmailConnection, e *EmailLabel) { n.Edges.Labels = append(n.Edges.Labels, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSyncs; query != nil {
		if err := _q.loadSyncs(ctx, query, nodes,
			func(n *EmailConnection) { n.Edges.Syncs = []*EmailSync{} },
			func(n *EmailConnection, e *EmailSync) { n.Edges.Syncs = append(n.Edges.Syncs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EmailConnectionQuery) loadLabels(ctx context.Context, query *EmailLabelQuery, nodes []*EmailConnection, init func(*EmailConnection), assign func(*EmailConnection, *EmailLabel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*EmailConnection)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(emaillabel.FieldConnectionID)
	}
	query.Where(predicate.EmailLabel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(emailconnection.LabelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ConnectionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "connection_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EmailConnectionQuery) loadSyncs(ctx context.Context, query *EmailSyncQuery, nodes []*EmailConnection, init func(*EmailConnection), assign func(*EmailConnection, *EmailSync)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*EmailConnection)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(emailsync.FieldConnectionID)
	}
	query.Where(predicate.EmailSync(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(emailconnection.SyncsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ConnectionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "connection_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EmailConnectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EmailConnectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emailconnection.Table, emailconnection.Columns, sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailconnection.FieldID)
		for i := range fields {
			if fields[i] != emailconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EmailConnectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(emailconnection.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = emailconnection.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmailConnectionGroupBy is the group-by builder for EmailConnection entities.
type EmailConnectionGroupBy struct {
	selector
	build *EmailConnectionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EmailConnectionGroupBy) Aggregate(fns ...AggregateFunc) *EmailConnectionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EmailConnectionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailConnectionQuery, *EmailConnectionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EmailConnectionGroupBy) sqlScan(ctx context.Context, root *EmailConnectionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmailConnectionSelect is the builder for selecting fields of EmailConnection entities.
type EmailConnectionSelect struct {
	*EmailConnectionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EmailConnectionSelect) Aggregate(fns ...AggregateFunc) *EmailConnectionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EmailConnectionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailConnectionQuery, *EmailConnectionSelect](ctx, _s.EmailConnectionQuery, _s, _s.inters, v)
}

func (_s *EmailConnectionSelect) sqlScan(ctx context.Context, root *EmailConnectionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
