// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emaillabel"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailLabelCreate is the builder for creating a EmailLabel entity.
type EmailLabelCreate struct {
	config
	mutation *EmailLabelMutation
	hooks    []Hook
}

// SetConnectionID sets the "connection_id" field.
func (_c *EmailLabelCreate) SetConnectionID(v string) *EmailLabelCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetProviderLabelID sets the "provider_label_id" field.
func (_c *EmailLabelCreate) SetProviderLabelID(v string) *EmailLabelCreate {
	_c.mutation.SetProviderLabelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *EmailLabelCreate) SetName(v string) *EmailLabelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *EmailLabelCreate) SetDisplayName(v string) *EmailLabelCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableDisplayName(v *string) *EmailLabelCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetLabelType sets the "label_type" field.
func (_c *EmailLabelCreate) SetLabelType(v emaillabel.LabelType) *EmailLabelCreate {
	_c.mutation.SetLabelType(v)
	return _c
}

// SetNillableLabelType sets the "label_type" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableLabelType(v *emaillabel.LabelType) *EmailLabelCreate {
	if v != nil {
		_c.SetLabelType(*v)
	}
	return _c
}

// SetParentLabelID sets the "parent_label_id" field.
func (_c *EmailLabelCreate) SetParentLabelID(v string) *EmailLabelCreate {
	_c.mutation.SetParentLabelID(v)
	return _c
}

// SetNillableParentLabelID sets the "parent_label_id" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableParentLabelID(v *string) *EmailLabelCreate {
	if v != nil {
		_c.SetParentLabelID(*v)
	}
	return _c
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_c *EmailLabelCreate) SetSyncEnabled(v bool) *EmailLabelCreate {
	_c.mutation.SetSyncEnabled(v)
	return _c
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableSyncEnabled(v *bool) *EmailLabelCreate {
	if v != nil {
		_c.SetSyncEnabled(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *EmailLabelCreate) SetMessageCount(v int64) *EmailLabelCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableMessageCount(v *int64) *EmailLabelCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetUnreadCount sets the "unread_count" field.
func (_c *EmailLabelCreate) SetUnreadCount(v int64) *EmailLabelCreate {
	_c.mutation.SetUnreadCount(v)
	return _c
}

// SetNillableUnreadCount sets the "unread_count" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableUnreadCount(v *int64) *EmailLabelCreate {
	if v != nil {
		_c.SetUnreadCount(*v)
	}
	return _c
}

// SetColor sets the "color" field.
func (_c *EmailLabelCreate) SetColor(v string) *EmailLabelCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableColor(v *string) *EmailLabelCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailLabelCreate) SetCreatedAt(v time.Time) *EmailLabelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableCreatedAt(v *time.Time) *EmailLabelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailLabelCreate) SetUpdatedAt(v time.Time) *EmailLabelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableUpdatedAt(v *time.Time) *EmailLabelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastScannedAt sets the "last_scanned_at" field.
func (_c *EmailLabelCreate) SetLastScannedAt(v time.Time) *EmailLabelCreate {
	_c.mutation.SetLastScannedAt(v)
	return _c
}

// SetNillableLastScannedAt sets the "last_scanned_at" field if the given value is not nil.
func (_c *EmailLabelCreate) SetNillableLastScannedAt(v *time.Time) *EmailLabelCreate {
	if v != nil {
		_c.SetLastScannedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailLabelCreate) SetID(v string) *EmailLabelCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetConnection sets the "connection" edge to the EmailConnection entity.
func (_c *EmailLabelCreate) SetConnection(v *EmailConnection) *EmailLabelCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the EmailLabelMutation object of the builder.
func (_c *EmailLabelCreate) Mutation() *EmailLabelMutation {
	return _c.mutation
}

// Save creates the EmailLabel in the database.
func (_c *EmailLabelCreate) Save(ctx context.Context) (*EmailLabel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailLabelCreate) SaveX(ctx context.Context) *EmailLabel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailLabelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailLabelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailLabelCreate) defaults() {
	if _, ok := _c.mutation.LabelType(); !ok {
		v := emaillabel.DefaultLabelType
		_c.mutation.SetLabelType(v)
	}
	if _, ok := _c.mutation.SyncEnabled(); !ok {
		v := emaillabel.DefaultSyncEnabled
		_c.mutation.SetSyncEnabled(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := emaillabel.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
	if _, ok := _c.mutation.UnreadCount(); !ok {
		v := emaillabel.DefaultUnreadCount
		_c.mutation.SetUnreadCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emaillabel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emaillabel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailLabelCreate) check() error {
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "EmailLabel.connection_id"`)}
	}
	if v, ok := _c.mutation.ConnectionID(); ok {
		if err := emaillabel.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "EmailLabel.connection_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderLabelID(); !ok {
		return &ValidationError{Name: "provider_label_id", err: errors.New(`ent: missing required field "EmailLabel.provider_label_id"`)}
	}
	if v, ok := _c.mutation.ProviderLabelID(); ok {
		if err := emaillabel.ProviderLabelIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_label_id", err: fmt.Errorf(`ent: validator failed for field "EmailLabel.provider_label_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EmailLabel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := emaillabel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailLabel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LabelType(); !ok {
		return &ValidationError{Name: "label_type", err: errors.New(`ent: missing required field "EmailLabel.label_type"`)}
	}
	if v, ok := _c.mutation.LabelType(); ok {
		if err := emaillabel.LabelTypeValidator(v); err != nil {
			return &ValidationError{Name: "label_type", err: fmt.Errorf(`ent: validator failed for field "EmailLabel.label_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncEnabled(); !ok {
		return &ValidationError{Name: "sync_enabled", err: errors.New(`ent: missing required field "EmailLabel.sync_enabled"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "EmailLabel.message_count"`)}
	}
	if _, ok := _c.mutation.UnreadCount(); !ok {
		return &ValidationError{Name: "unread_count", err: errors.New(`ent: missing required field "EmailLabel.unread_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailLabel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailLabel.updated_at"`)}
	}
	if len(_c.mutation.ConnectionIDs()) == 0 {
		return &ValidationError{Name: "connection", err: errors.New(`ent: missing required edge "EmailLabel.connection"`)}
	}
	return nil
}

func (_c *EmailLabelCreate) sqlSave(ctx context.Context) (*EmailLabel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EmailLabel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailLabelCreate) createSpec() (*EmailLabel, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailLabel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emaillabel.Table, sqlgraph.NewFieldSpec(emaillabel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProviderLabelID(); ok {
		_spec.SetField(emaillabel.FieldProviderLabelID, field.TypeString, value)
		_node.ProviderLabelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(emaillabel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(emaillabel.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.LabelType(); ok {
		_spec.SetField(emaillabel.FieldLabelType, field.TypeEnum, value)
		_node.LabelType = value
	}
	if value, ok := _c.mutation.ParentLabelID(); ok {
		_spec.SetField(emaillabel.FieldParentLabelID, field.TypeString, value)
		_node.ParentLabelID = &value
	}
	if value, ok := _c.mutation.SyncEnabled(); ok {
		_spec.SetField(emaillabel.FieldSyncEnabled, field.TypeBool, value)
		_node.SyncEnabled = value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(emaillabel.FieldMessageCount, field.TypeInt64, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.UnreadCount(); ok {
		_spec.SetField(emaillabel.FieldUnreadCount, field.TypeInt64, value)
		_node.UnreadCount = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(emaillabel.FieldColor, field.TypeString, value)
		_node.Color = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emaillabel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emaillabel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastScannedAt(); ok {
		_spec.SetField(emaillabel.FieldLastScannedAt, field.TypeTime, value)
		_node.LastScannedAt = &value
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emaillabel.ConnectionTable,
			Columns: []string{emaillabel.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConnectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmailLabelCreateBulk is the builder for creating many EmailLabel entities in bulk.
type EmailLabelCreateBulk struct {
	config
	err      error
	builders []*EmailLabelCreate
}

// Save creates the EmailLabel entities in the database.
func (_c *EmailLabelCreateBulk) Save(ctx context.Context) ([]*EmailLabel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailLabel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailLabelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailLabelCreateBulk) SaveX(ctx context.Context) []*EmailLabel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailLabelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailLabelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
