// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emaillabel"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmailLabel is the model entity for the EmailLabel schema.
type EmailLabel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ID of the parent EmailConnection
	ConnectionID string `json:"connection_id,omitempty"`
	// Label/folder ID from the email provider
	ProviderLabelID string `json:"provider_label_id,omitempty"`
	// Label/folder name
	Name string `json:"name,omitempty"`
	// User-friendly display name
	DisplayName string `json:"display_name,omitempty"`
	// Type of label
	LabelType emaillabel.LabelType `json:"label_type,omitempty"`
	// Parent label ID if nested
	ParentLabelID *string `json:"parent_label_id,omitempty"`
	// Whether syncing is enabled for this label
	SyncEnabled bool `json:"sync_enabled,omitempty"`
	// Number of messages with this label
	MessageCount int64 `json:"message_count,omitempty"`
	// Number of unread messages with this label
	UnreadCount int64 `json:"unread_count,omitempty"`
	// Label color if applicable
	Color *string `json:"color,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Last time label was scanned for changes
	LastScannedAt *time.Time `json:"last_scanned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmailLabelQuery when eager-loading is set.
	Edges        EmailLabelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmailLabelEdges holds the relations/edges for other nodes in the graph.
type EmailLabelEdges struct {
	// The connection this label belongs to
	Connection *EmailConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailLabelEdges) ConnectionOrErr() (*EmailConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: emailconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailLabel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emaillabel.FieldSyncEnabled:
			values[i] = new(sql.NullBool)
		case emaillabel.FieldMessageCount, emaillabel.FieldUnreadCount:
			values[i] = new(sql.NullInt64)
		case emaillabel.FieldID, emaillabel.FieldConnectionID, emaillabel.FieldProviderLabelID, emaillabel.FieldName, emaillabel.FieldDisplayName, emaillabel.FieldLabelType, emaillabel.FieldParentLabelID, emaillabel.FieldColor:
			values[i] = new(sql.NullString)
		case emaillabel.FieldCreatedAt, emaillabel.FieldUpdatedAt, emaillabel.FieldLastScannedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailLabel fields.
func (_m *EmailLabel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emaillabel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case emaillabel.FieldConnectionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = value.String
			}
		case emaillabel.FieldProviderLabelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_label_id", values[i])
			} else if value.Valid {
				_m.ProviderLabelID = value.String
			}
		case emaillabel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case emaillabel.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case emaillabel.FieldLabelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label_type", values[i])
			} else if value.Valid {
				_m.LabelType = emaillabel.LabelType(value.String)
			}
		case emaillabel.FieldParentLabelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_label_id", values[i])
			} else if value.Valid {
				_m.ParentLabelID = new(string)
				*_m.ParentLabelID = value.String
			}
		case emaillabel.FieldSyncEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sync_enabled", values[i])
			} else if value.Valid {
				_m.SyncEnabled = value.Bool
			}
		case emaillabel.FieldMessageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_count", values[i])
			} else if value.Valid {
				_m.MessageCount = value.Int64
			}
		case emaillabel.FieldUnreadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unread_count", values[i])
			} else if value.Valid {
				_m.UnreadCount = value.Int64
			}
		case emaillabel.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = new(string)
				*_m.Color = value.String
			}
		case emaillabel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emaillabel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case emaillabel.FieldLastScannedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_scanned_at", values[i])
			} else if value.Valid {
				_m.LastScannedAt = new(time.Time)
				*_m.LastScannedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailLabel.
// This includes values selected through modifiers, order, etc.
func (_m *EmailLabel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConnection queries the "connection" edge of the EmailLabel entity.
func (_m *EmailLabel) QueryConnection() *EmailConnectionQuery {
	return NewEmailLabelClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this EmailLabel.
// Note that you need to call EmailLabel.Unwrap() before calling this method if this EmailLabel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailLabel) Update() *EmailLabelUpdateOne {
	return NewEmailLabelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailLabel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailLabel) Unwrap() *EmailLabel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailLabel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailLabel) String() string {
	var builder strings.Builder
	builder.WriteString("EmailLabel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("connection_id=")
	builder.WriteString(_m.ConnectionID)
	builder.WriteString(", ")
	builder.WriteString("provider_label_id=")
	builder.WriteString(_m.ProviderLabelID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("label_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.LabelType))
	builder.WriteString(", ")
	if v := _m.ParentLabelID; v != nil {
		builder.WriteString("parent_label_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sync_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncEnabled))
	builder.WriteString(", ")
	builder.WriteString("message_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageCount))
	builder.WriteString(", ")
	builder.WriteString("unread_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnreadCount))
	builder.WriteString(", ")
	if v := _m.Color; v != nil {
		builder.WriteString("color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastScannedAt; v != nil {
		builder.WriteString("last_scanned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EmailLabels is a parsable slice of EmailLabel.
type EmailLabels []*EmailLabel
