// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emailsync"
	"clockzen-next/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailSyncUpdate is the builder for updating EmailSync entities.
type EmailSyncUpdate struct {
	config
	hooks    []Hook
	mutation *EmailSyncMutation
}

// Where appends a list predicates to the EmailSyncUpdate builder.
func (_u *EmailSyncUpdate) Where(ps ...predicate.EmailSync) *EmailSyncUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *EmailSyncUpdate) SetConnectionID(v string) *EmailSyncUpdate {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableConnectionID(v *string) *EmailSyncUpdate {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetLabelID sets the "label_id" field.
func (_u *EmailSyncUpdate) SetLabelID(v string) *EmailSyncUpdate {
	_u.mutation.SetLabelID(v)
	return _u
}

// SetNillableLabelID sets the "label_id" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableLabelID(v *string) *EmailSyncUpdate {
	if v != nil {
		_u.SetLabelID(*v)
	}
	return _u
}

// ClearLabelID clears the value of the "label_id" field.
func (_u *EmailSyncUpdate) ClearLabelID() *EmailSyncUpdate {
	_u.mutation.ClearLabelID()
	return _u
}

// SetSyncType sets the "sync_type" field.
func (_u *EmailSyncUpdate) SetSyncType(v emailsync.SyncType) *EmailSyncUpdate {
	_u.mutation.SetSyncType(v)
	return _u
}

// SetNillableSyncType sets the "sync_type" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableSyncType(v *emailsync.SyncType) *EmailSyncUpdate {
	if v != nil {
		_u.SetSyncType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailSyncUpdate) SetStatus(v emailsync.Status) *EmailSyncUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableStatus(v *emailsync.Status) *EmailSyncUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EmailSyncUpdate) SetStartedAt(v time.Time) *EmailSyncUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableStartedAt(v *time.Time) *EmailSyncUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EmailSyncUpdate) ClearStartedAt() *EmailSyncUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EmailSyncUpdate) SetCompletedAt(v time.Time) *EmailSyncUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableCompletedAt(v *time.Time) *EmailSyncUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EmailSyncUpdate) ClearCompletedAt() *EmailSyncUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetMessagesScanned sets the "messages_scanned" field.
func (_u *EmailSyncUpdate) SetMessagesScanned(v int) *EmailSyncUpdate {
	_u.mutation.ResetMessagesScanned()
	_u.mutation.SetMessagesScanned(v)
	return _u
}

// SetNillableMessagesScanned sets the "messages_scanned" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableMessagesScanned(v *int) *EmailSyncUpdate {
	if v != nil {
		_u.SetMessagesScanned(*v)
	}
	return _u
}

// AddMessagesScanned adds value to the "messages_scanned" field.
func (_u *EmailSyncUpdate) AddMessagesScanned(v int) *EmailSyncUpdate {
	_u.mutation.AddMessagesScanned(v)
	return _u
}

// SetMessagesDownloaded sets the "messages_downloaded" field.
func (_u *EmailSyncUpdate) SetMessagesDownloaded(v int) *EmailSyncUpdate {
	_u.mutation.ResetMessagesDownloaded()
	_u.mutation.SetMessagesDownloaded(v)
	return _u
}

// SetNillableMessagesDownloaded sets the "messages_downloaded" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableMessagesDownloaded(v *int) *EmailSyncUpdate {
	if v != nil {
		_u.SetMessagesDownloaded(*v)
	}
	return _u
}

// AddMessagesDownloaded adds value to the "messages_downloaded" field.
func (_u *EmailSyncUpdate) AddMessagesDownloaded(v int) *EmailSyncUpdate {
	_u.mutation.AddMessagesDownloaded(v)
	return _u
}

// SetMessagesIndexed sets the "messages_indexed" field.
func (_u *EmailSyncUpdate) SetMessagesIndexed(v int) *EmailSyncUpdate {
	_u.mutation.ResetMessagesIndexed()
	_u.mutation.SetMessagesIndexed(v)
	return _u
}

// SetNillableMessagesIndexed sets the "messages_indexed" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableMessagesIndexed(v *int) *EmailSyncUpdate {
	if v != nil {
		_u.SetMessagesIndexed(*v)
	}
	return _u
}

// AddMessagesIndexed adds value to the "messages_indexed" field.
func (_u *EmailSyncUpdate) AddMessagesIndexed(v int) *EmailSyncUpdate {
	_u.mutation.AddMessagesIndexed(v)
	return _u
}

// SetMessagesFailed sets the "messages_failed" field.
func (_u *EmailSyncUpdate) SetMessagesFailed(v int) *EmailSyncUpdate {
	_u.mutation.ResetMessagesFailed()
	_u.mutation.SetMessagesFailed(v)
	return _u
}

// SetNillableMessagesFailed sets the "messages_failed" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableMessagesFailed(v *int) *EmailSyncUpdate {
	if v != nil {
		_u.SetMessagesFailed(*v)
	}
	return _u
}

// AddMessagesFailed adds value to the "messages_failed" field.
func (_u *EmailSyncUpdate) AddMessagesFailed(v int) *EmailSyncUpdate {
	_u.mutation.AddMessagesFailed(v)
	return _u
}

// SetAttachmentsDownloaded sets the "attachments_downloaded" field.
func (_u *EmailSyncUpdate) SetAttachmentsDownloaded(v int) *EmailSyncUpdate {
	_u.mutation.ResetAttachmentsDownloaded()
	_u.mutation.SetAttachmentsDownloaded(v)
	return _u
}

// SetNillableAttachmentsDownloaded sets the "attachments_downloaded" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableAttachmentsDownloaded(v *int) *EmailSyncUpdate {
	if v != nil {
		_u.SetAttachmentsDownloaded(*v)
	}
	return _u
}

// AddAttachmentsDownloaded adds value to the "attachments_downloaded" field.
func (_u *EmailSyncUpdate) AddAttachmentsDownloaded(v int) *EmailSyncUpdate {
	_u.mutation.AddAttachmentsDownloaded(v)
	return _u
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_u *EmailSyncUpdate) SetBytesTransferred(v int64) *EmailSyncUpdate {
	_u.mutation.ResetBytesTransferred()
	_u.mutation.SetBytesTransferred(v)
	return _u
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableBytesTransferred(v *int64) *EmailSyncUpdate {
	if v != nil {
		_u.SetBytesTransferred(*v)
	}
	return _u
}

// AddBytesTransferred adds value to the "bytes_transferred" field.
func (_u *EmailSyncUpdate) AddBytesTransferred(v int64) *EmailSyncUpdate {
	_u.mutation.AddBytesTransferred(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EmailSyncUpdate) SetErrorMessage(v string) *EmailSyncUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableErrorMessage(v *string) *EmailSyncUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EmailSyncUpdate) ClearErrorMessage() *EmailSyncUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *EmailSyncUpdate) SetErrorDetails(v map[string]interface{}) *EmailSyncUpdate {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *EmailSyncUpdate) ClearErrorDetails() *EmailSyncUpdate {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetHistoryID sets the "history_id" field.
func (_u *EmailSyncUpdate) SetHistoryID(v string) *EmailSyncUpdate {
	_u.mutation.SetHistoryID(v)
	return _u
}

// SetNillableHistoryID sets the "history_id" field if the given value is not nil.
func (_u *EmailSyncUpdate) SetNillableHistoryID(v *string) *EmailSyncUpdate {
	if v != nil {
		_u.SetHistoryID(*v)
	}
	return _u
}

// ClearHistoryID clears the value of the "history_id" field.
func (_u *EmailSyncUpdate) ClearHistoryID() *EmailSyncUpdate {
	_u.mutation.ClearHistoryID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailSyncUpdate) SetUpdatedAt(v time.Time) *EmailSyncUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConnection sets the "connection" edge to the EmailConnection entity.
func (_u *EmailSyncUpdate) SetConnection(v *EmailConnection) *EmailSyncUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the EmailSyncMutation object of the builder.
func (_u *EmailSyncUpdate) Mutation() *EmailSyncMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the EmailConnection entity.
func (_u *EmailSyncUpdate) ClearConnection() *EmailSyncUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailSyncUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSyncUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailSyncUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSyncUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailSyncUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailsync.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailSyncUpdate) check() error {
	if v, ok := _u.mutation.ConnectionID(); ok {
		if err := emailsync.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "EmailSync.connection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncType(); ok {
		if err := emailsync.SyncTypeValidator(v); err != nil {
			return &ValidationError{Name: "sync_type", err: fmt.Errorf(`ent: validator failed for field "EmailSync.sync_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailsync.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailSync.status": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSync.connection"`)
	}
	return nil
}

func (_u *EmailSyncUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailsync.Table, emailsync.Columns, sqlgraph.NewFieldSpec(emailsync.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LabelID(); ok {
		_spec.SetField(emailsync.FieldLabelID, field.TypeString, value)
	}
	if _u.mutation.LabelIDCleared() {
		_spec.ClearField(emailsync.FieldLabelID, field.TypeString)
	}
	if value, ok := _u.mutation.SyncType(); ok {
		_spec.SetField(emailsync.FieldSyncType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailsync.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(emailsync.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(emailsync.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(emailsync.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(emailsync.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessagesScanned(); ok {
		_spec.SetField(emailsync.FieldMessagesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesScanned(); ok {
		_spec.AddField(emailsync.FieldMessagesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesDownloaded(); ok {
		_spec.SetField(emailsync.FieldMessagesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesDownloaded(); ok {
		_spec.AddField(emailsync.FieldMessagesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesIndexed(); ok {
		_spec.SetField(emailsync.FieldMessagesIndexed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesIndexed(); ok {
		_spec.AddField(emailsync.FieldMessagesIndexed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesFailed(); ok {
		_spec.SetField(emailsync.FieldMessagesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesFailed(); ok {
		_spec.AddField(emailsync.FieldMessagesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttachmentsDownloaded(); ok {
		_spec.SetField(emailsync.FieldAttachmentsDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttachmentsDownloaded(); ok {
		_spec.AddField(emailsync.FieldAttachmentsDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BytesTransferred(); ok {
		_spec.SetField(emailsync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesTransferred(); ok {
		_spec.AddField(emailsync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(emailsync.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(emailsync.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(emailsync.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(emailsync.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.HistoryID(); ok {
		_spec.SetField(emailsync.FieldHistoryID, field.TypeString, value)
	}
	if _u.mutation.HistoryIDCleared() {
		_spec.ClearField(emailsync.FieldHistoryID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsync.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsync.ConnectionTable,
			Columns: []string{emailsync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsync.ConnectionTable,
			Columns: []string{emailsync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailSyncUpdateOne is the builder for updating a single EmailSync entity.
type EmailSyncUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailSyncMutation
}

// SetConnectionID sets the "connection_id" field.
func (_u *EmailSyncUpdateOne) SetConnectionID(v string) *EmailSyncUpdateOne {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableConnectionID(v *string) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetLabelID sets the "label_id" field.
func (_u *EmailSyncUpdateOne) SetLabelID(v string) *EmailSyncUpdateOne {
	_u.mutation.SetLabelID(v)
	return _u
}

// SetNillableLabelID sets the "label_id" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableLabelID(v *string) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetLabelID(*v)
	}
	return _u
}

// ClearLabelID clears the value of the "label_id" field.
func (_u *EmailSyncUpdateOne) ClearLabelID() *EmailSyncUpdateOne {
	_u.mutation.ClearLabelID()
	return _u
}

// SetSyncType sets the "sync_type" field.
func (_u *EmailSyncUpdateOne) SetSyncType(v emailsync.SyncType) *EmailSyncUpdateOne {
	_u.mutation.SetSyncType(v)
	return _u
}

// SetNillableSyncType sets the "sync_type" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableSyncType(v *emailsync.SyncType) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetSyncType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailSyncUpdateOne) SetStatus(v emailsync.Status) *EmailSyncUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableStatus(v *emailsync.Status) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EmailSyncUpdateOne) SetStartedAt(v time.Time) *EmailSyncUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableStartedAt(v *time.Time) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EmailSyncUpdateOne) ClearStartedAt() *EmailSyncUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EmailSyncUpdateOne) SetCompletedAt(v time.Time) *EmailSyncUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableCompletedAt(v *time.Time) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EmailSyncUpdateOne) ClearCompletedAt() *EmailSyncUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetMessagesScanned sets the "messages_scanned" field.
func (_u *EmailSyncUpdateOne) SetMessagesScanned(v int) *EmailSyncUpdateOne {
	_u.mutation.ResetMessagesScanned()
	_u.mutation.SetMessagesScanned(v)
	return _u
}

// SetNillableMessagesScanned sets the "messages_scanned" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableMessagesScanned(v *int) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetMessagesScanned(*v)
	}
	return _u
}

// AddMessagesScanned adds value to the "messages_scanned" field.
func (_u *EmailSyncUpdateOne) AddMessagesScanned(v int) *EmailSyncUpdateOne {
	_u.mutation.AddMessagesScanned(v)
	return _u
}

// SetMessagesDownloaded sets the "messages_downloaded" field.
func (_u *EmailSyncUpdateOne) SetMessagesDownloaded(v int) *EmailSyncUpdateOne {
	_u.mutation.ResetMessagesDownloaded()
	_u.mutation.SetMessagesDownloaded(v)
	return _u
}

// SetNillableMessagesDownloaded sets the "messages_downloaded" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableMessagesDownloaded(v *int) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetMessagesDownloaded(*v)
	}
	return _u
}

// AddMessagesDownloaded adds value to the "messages_downloaded" field.
func (_u *EmailSyncUpdateOne) AddMessagesDownloaded(v int) *EmailSyncUpdateOne {
	_u.mutation.AddMessagesDownloaded(v)
	return _u
}

// SetMessagesIndexed sets the "messages_indexed" field.
func (_u *EmailSyncUpdateOne) SetMessagesIndexed(v int) *EmailSyncUpdateOne {
	_u.mutation.ResetMessagesIndexed()
	_u.mutation.SetMessagesIndexed(v)
	return _u
}

// SetNillableMessagesIndexed sets the "messages_indexed" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableMessagesIndexed(v *int) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetMessagesIndexed(*v)
	}
	return _u
}

// AddMessagesIndexed adds value to the "messages_indexed" field.
func (_u *EmailSyncUpdateOne) AddMessagesIndexed(v int) *EmailSyncUpdateOne {
	_u.mutation.AddMessagesIndexed(v)
	return _u
}

// SetMessagesFailed sets the "messages_failed" field.
func (_u *EmailSyncUpdateOne) SetMessagesFailed(v int) *EmailSyncUpdateOne {
	_u.mutation.ResetMessagesFailed()
	_u.mutation.SetMessagesFailed(v)
	return _u
}

// SetNillableMessagesFailed sets the "messages_failed" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableMessagesFailed(v *int) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetMessagesFailed(*v)
	}
	return _u
}

// AddMessagesFailed adds value to the "messages_failed" field.
func (_u *EmailSyncUpdateOne) AddMessagesFailed(v int) *EmailSyncUpdateOne {
	_u.mutation.AddMessagesFailed(v)
	return _u
}

// SetAttachmentsDownloaded sets the "attachments_downloaded" field.
func (_u *EmailSyncUpdateOne) SetAttachmentsDownloaded(v int) *EmailSyncUpdateOne {
	_u.mutation.ResetAttachmentsDownloaded()
	_u.mutation.SetAttachmentsDownloaded(v)
	return _u
}

// SetNillableAttachmentsDownloaded sets the "attachments_downloaded" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableAttachmentsDownloaded(v *int) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetAttachmentsDownloaded(*v)
	}
	return _u
}

// AddAttachmentsDownloaded adds value to the "attachments_downloaded" field.
func (_u *EmailSyncUpdateOne) AddAttachmentsDownloaded(v int) *EmailSyncUpdateOne {
	_u.mutation.AddAttachmentsDownloaded(v)
	return _u
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_u *EmailSyncUpdateOne) SetBytesTransferred(v int64) *EmailSyncUpdateOne {
	_u.mutation.ResetBytesTransferred()
	_u.mutation.SetBytesTransferred(v)
	return _u
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableBytesTransferred(v *int64) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetBytesTransferred(*v)
	}
	return _u
}

// AddBytesTransferred adds value to the "bytes_transferred" field.
func (_u *EmailSyncUpdateOne) AddBytesTransferred(v int64) *EmailSyncUpdateOne {
	_u.mutation.AddBytesTransferred(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EmailSyncUpdateOne) SetErrorMessage(v string) *EmailSyncUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableErrorMessage(v *string) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EmailSyncUpdateOne) ClearErrorMessage() *EmailSyncUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *EmailSyncUpdateOne) SetErrorDetails(v map[string]interface{}) *EmailSyncUpdateOne {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *EmailSyncUpdateOne) ClearErrorDetails() *EmailSyncUpdateOne {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetHistoryID sets the "history_id" field.
func (_u *EmailSyncUpdateOne) SetHistoryID(v string) *EmailSyncUpdateOne {
	_u.mutation.SetHistoryID(v)
	return _u
}

// SetNillableHistoryID sets the "history_id" field if the given value is not nil.
func (_u *EmailSyncUpdateOne) SetNillableHistoryID(v *string) *EmailSyncUpdateOne {
	if v != nil {
		_u.SetHistoryID(*v)
	}
	return _u
}

// ClearHistoryID clears the value of the "history_id" field.
func (_u *EmailSyncUpdateOne) ClearHistoryID() *EmailSyncUpdateOne {
	_u.mutation.ClearHistoryID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailSyncUpdateOne) SetUpdatedAt(v time.Time) *EmailSyncUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConnection sets the "connection" edge to the EmailConnection entity.
func (_u *EmailSyncUpdateOne) SetConnection(v *EmailConnection) *EmailSyncUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the EmailSyncMutation object of the builder.
func (_u *EmailSyncUpdateOne) Mutation() *EmailSyncMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the EmailConnection entity.
func (_u *EmailSyncUpdateOne) ClearConnection() *EmailSyncUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the EmailSyncUpdate builder.
func (_u *EmailSyncUpdateOne) Where(ps ...predicate.EmailSync) *EmailSyncUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailSyncUpdateOne) Select(field string, fields ...string) *EmailSyncUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailSync entity.
func (_u *EmailSyncUpdateOne) Save(ctx context.Context) (*EmailSync, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailSyncUpdateOne) SaveX(ctx context.Context) *EmailSync {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailSyncUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailSyncUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailSyncUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailsync.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailSyncUpdateOne) check() error {
	if v, ok := _u.mutation.ConnectionID(); ok {
		if err := emailsync.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "EmailSync.connection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncType(); ok {
		if err := emailsync.SyncTypeValidator(v); err != nil {
			return &ValidationError{Name: "sync_type", err: fmt.Errorf(`ent: validator failed for field "EmailSync.sync_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailsync.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailSync.status": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailSync.connection"`)
	}
	return nil
}

func (_u *EmailSyncUpdateOne) sqlSave(ctx context.Context) (_node *EmailSync, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailsync.Table, emailsync.Columns, sqlgraph.NewFieldSpec(emailsync.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailSync.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailsync.FieldID)
		for _, f := range fields {
			if !emailsync.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailsync.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LabelID(); ok {
		_spec.SetField(emailsync.FieldLabelID, field.TypeString, value)
	}
	if _u.mutation.LabelIDCleared() {
		_spec.ClearField(emailsync.FieldLabelID, field.TypeString)
	}
	if value, ok := _u.mutation.SyncType(); ok {
		_spec.SetField(emailsync.FieldSyncType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailsync.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(emailsync.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(emailsync.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(emailsync.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(emailsync.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessagesScanned(); ok {
		_spec.SetField(emailsync.FieldMessagesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesScanned(); ok {
		_spec.AddField(emailsync.FieldMessagesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesDownloaded(); ok {
		_spec.SetField(emailsync.FieldMessagesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesDownloaded(); ok {
		_spec.AddField(emailsync.FieldMessagesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesIndexed(); ok {
		_spec.SetField(emailsync.FieldMessagesIndexed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesIndexed(); ok {
		_spec.AddField(emailsync.FieldMessagesIndexed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessagesFailed(); ok {
		_spec.SetField(emailsync.FieldMessagesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessagesFailed(); ok {
		_spec.AddField(emailsync.FieldMessagesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttachmentsDownloaded(); ok {
		_spec.SetField(emailsync.FieldAttachmentsDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttachmentsDownloaded(); ok {
		_spec.AddField(emailsync.FieldAttachmentsDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BytesTransferred(); ok {
		_spec.SetField(emailsync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesTransferred(); ok {
		_spec.AddField(emailsync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(emailsync.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(emailsync.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(emailsync.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(emailsync.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.HistoryID(); ok {
		_spec.SetField(emailsync.FieldHistoryID, field.TypeString, value)
	}
	if _u.mutation.HistoryIDCleared() {
		_spec.ClearField(emailsync.FieldHistoryID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsync.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsync.ConnectionTable,
			Columns: []string{emailsync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emailsync.ConnectionTable,
			Columns: []string{emailsync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EmailSync{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailsync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
