// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emailsync"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmailSync is the model entity for the EmailSync schema.
type EmailSync struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ID of the parent EmailConnection
	ConnectionID string `json:"connection_id,omitempty"`
	// Specific label ID if sync was for a label
	LabelID *string `json:"label_id,omitempty"`
	// Type of sync operation
	SyncType emailsync.SyncType `json:"sync_type,omitempty"`
	// Current sync status
	Status emailsync.Status `json:"status,omitempty"`
	// When sync started
	StartedAt *time.Time `json:"started_at,omitempty"`
	// When sync completed
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Number of messages scanned
	MessagesScanned int `json:"messages_scanned,omitempty"`
	// Number of messages downloaded
	MessagesDownloaded int `json:"messages_downloaded,omitempty"`
	// Number of messages indexed
	MessagesIndexed int `json:"messages_indexed,omitempty"`
	// Number of message operations that failed
	MessagesFailed int `json:"messages_failed,omitempty"`
	// Number of attachments downloaded
	AttachmentsDownloaded int `json:"attachments_downloaded,omitempty"`
	// Total bytes transferred
	BytesTransferred int64 `json:"bytes_transferred,omitempty"`
	// Error message if sync failed
	ErrorMessage *string `json:"error_message,omitempty"`
	// Detailed error information
	ErrorDetails map[string]interface{} `json:"error_details,omitempty"`
	// Email provider history ID for incremental sync
	HistoryID *string `json:"history_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmailSyncQuery when eager-loading is set.
	Edges        EmailSyncEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmailSyncEdges holds the relations/edges for other nodes in the graph.
type EmailSyncEdges struct {
	// The connection this sync belongs to
	Connection *EmailConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailSyncEdges) ConnectionOrErr() (*EmailConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: emailconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailSync) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailsync.FieldErrorDetails:
			values[i] = new([]byte)
		case emailsync.FieldMessagesScanned, emailsync.FieldMessagesDownloaded, emailsync.FieldMessagesIndexed, emailsync.FieldMessagesFailed, emailsync.FieldAttachmentsDownloaded, emailsync.FieldBytesTransferred:
			values[i] = new(sql.NullInt64)
		case emailsync.FieldID, emailsync.FieldConnectionID, emailsync.FieldLabelID, emailsync.FieldSyncType, emailsync.FieldStatus, emailsync.FieldErrorMessage, emailsync.FieldHistoryID:
			values[i] = new(sql.NullString)
		case emailsync.FieldStartedAt, emailsync.FieldCompletedAt, emailsync.FieldCreatedAt, emailsync.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailSync fields.
func (_m *EmailSync) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailsync.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case emailsync.FieldConnectionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = value.String
			}
		case emailsync.FieldLabelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label_id", values[i])
			} else if value.Valid {
				_m.LabelID = new(string)
				*_m.LabelID = value.String
			}
		case emailsync.FieldSyncType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_type", values[i])
			} else if value.Valid {
				_m.SyncType = emailsync.SyncType(value.String)
			}
		case emailsync.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = emailsync.Status(value.String)
			}
		case emailsync.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case emailsync.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case emailsync.FieldMessagesScanned:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field messages_scanned", values[i])
			} else if value.Valid {
				_m.MessagesScanned = int(value.Int64)
			}
		case emailsync.FieldMessagesDownloaded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field messages_downloaded", values[i])
			} else if value.Valid {
				_m.MessagesDownloaded = int(value.Int64)
			}
		case emailsync.FieldMessagesIndexed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field messages_indexed", values[i])
			} else if value.Valid {
				_m.MessagesIndexed = int(value.Int64)
			}
		case emailsync.FieldMessagesFailed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field messages_failed", values[i])
			} else if value.Valid {
				_m.MessagesFailed = int(value.Int64)
			}
		case emailsync.FieldAttachmentsDownloaded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attachments_downloaded", values[i])
			} else if value.Valid {
				_m.AttachmentsDownloaded = int(value.Int64)
			}
		case emailsync.FieldBytesTransferred:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes_transferred", values[i])
			} else if value.Valid {
				_m.BytesTransferred = value.Int64
			}
		case emailsync.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case emailsync.FieldErrorDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field error_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ErrorDetails); err != nil {
					return fmt.Errorf("unmarshal field error_details: %w", err)
				}
			}
		case emailsync.FieldHistoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field history_id", values[i])
			} else if value.Valid {
				_m.HistoryID = new(string)
				*_m.HistoryID = value.String
			}
		case emailsync.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailsync.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailSync.
// This includes values selected through modifiers, order, etc.
func (_m *EmailSync) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConnection queries the "connection" edge of the EmailSync entity.
func (_m *EmailSync) QueryConnection() *EmailConnectionQuery {
	return NewEmailSyncClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this EmailSync.
// Note that you need to call EmailSync.Unwrap() before calling this method if this EmailSync
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailSync) Update() *EmailSyncUpdateOne {
	return NewEmailSyncClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailSync entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailSync) Unwrap() *EmailSync {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailSync is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailSync) String() string {
	var builder strings.Builder
	builder.WriteString("EmailSync(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("connection_id=")
	builder.WriteString(_m.ConnectionID)
	builder.WriteString(", ")
	if v := _m.LabelID; v != nil {
		builder.WriteString("label_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sync_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("messages_scanned=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessagesScanned))
	builder.WriteString(", ")
	builder.WriteString("messages_downloaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessagesDownloaded))
	builder.WriteString(", ")
	builder.WriteString("messages_indexed=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessagesIndexed))
	builder.WriteString(", ")
	builder.WriteString("messages_failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessagesFailed))
	builder.WriteString(", ")
	builder.WriteString("attachments_downloaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttachmentsDownloaded))
	builder.WriteString(", ")
	builder.WriteString("bytes_transferred=")
	builder.WriteString(fmt.Sprintf("%v", _m.BytesTransferred))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("error_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorDetails))
	builder.WriteString(", ")
	if v := _m.HistoryID; v != nil {
		builder.WriteString("history_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailSyncs is a parsable slice of EmailSync.
type EmailSyncs []*EmailSync
