// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/googledriveconnection"
	"clockzen-next/internal/ent/googledrivesync"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GoogleDriveSync is the model entity for the GoogleDriveSync schema.
type GoogleDriveSync struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ID of the parent GoogleDriveConnection
	ConnectionID string `json:"connection_id,omitempty"`
	// Specific folder ID if sync was for a folder
	FolderID *string `json:"folder_id,omitempty"`
	// Type of sync operation
	SyncType googledrivesync.SyncType `json:"sync_type,omitempty"`
	// Current sync status
	Status googledrivesync.Status `json:"status,omitempty"`
	// When sync started
	StartedAt *time.Time `json:"started_at,omitempty"`
	// When sync completed
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Number of files scanned
	FilesScanned int `json:"files_scanned,omitempty"`
	// Number of files downloaded
	FilesDownloaded int `json:"files_downloaded,omitempty"`
	// Number of files uploaded
	FilesUploaded int `json:"files_uploaded,omitempty"`
	// Number of files deleted
	FilesDeleted int `json:"files_deleted,omitempty"`
	// Number of file operations that failed
	FilesFailed int `json:"files_failed,omitempty"`
	// Total bytes transferred
	BytesTransferred int64 `json:"bytes_transferred,omitempty"`
	// Error message if sync failed
	ErrorMessage *string `json:"error_message,omitempty"`
	// Detailed error information
	ErrorDetails map[string]interface{} `json:"error_details,omitempty"`
	// Google Drive change token for incremental sync
	ChangeToken *string `json:"change_token,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoogleDriveSyncQuery when eager-loading is set.
	Edges        GoogleDriveSyncEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GoogleDriveSyncEdges holds the relations/edges for other nodes in the graph.
type GoogleDriveSyncEdges struct {
	// The connection this sync belongs to
	Connection *GoogleDriveConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoogleDriveSyncEdges) ConnectionOrErr() (*GoogleDriveConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: googledriveconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoogleDriveSync) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case googledrivesync.FieldErrorDetails:
			values[i] = new([]byte)
		case googledrivesync.FieldFilesScanned, googledrivesync.FieldFilesDownloaded, googledrivesync.FieldFilesUploaded, googledrivesync.FieldFilesDeleted, googledrivesync.FieldFilesFailed, googledrivesync.FieldBytesTransferred:
			values[i] = new(sql.NullInt64)
		case googledrivesync.FieldID, googledrivesync.FieldConnectionID, googledrivesync.FieldFolderID, googledrivesync.FieldSyncType, googledrivesync.FieldStatus, googledrivesync.FieldErrorMessage, googledrivesync.FieldChangeToken:
			values[i] = new(sql.NullString)
		case googledrivesync.FieldStartedAt, googledrivesync.FieldCompletedAt, googledrivesync.FieldCreatedAt, googledrivesync.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoogleDriveSync fields.
func (_m *GoogleDriveSync) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case googledrivesync.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case googledrivesync.FieldConnectionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = value.String
			}
		case googledrivesync.FieldFolderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = new(string)
				*_m.FolderID = value.String
			}
		case googledrivesync.FieldSyncType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_type", values[i])
			} else if value.Valid {
				_m.SyncType = googledrivesync.SyncType(value.String)
			}
		case googledrivesync.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = googledrivesync.Status(value.String)
			}
		case googledrivesync.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case googledrivesync.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case googledrivesync.FieldFilesScanned:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field files_scanned", values[i])
			} else if value.Valid {
				_m.FilesScanned = int(value.Int64)
			}
		case googledrivesync.FieldFilesDownloaded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field files_downloaded", values[i])
			} else if value.Valid {
				_m.FilesDownloaded = int(value.Int64)
			}
		case googledrivesync.FieldFilesUploaded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field files_uploaded", values[i])
			} else if value.Valid {
				_m.FilesUploaded = int(value.Int64)
			}
		case googledrivesync.FieldFilesDeleted:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field files_deleted", values[i])
			} else if value.Valid {
				_m.FilesDeleted = int(value.Int64)
			}
		case googledrivesync.FieldFilesFailed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field files_failed", values[i])
			} else if value.Valid {
				_m.FilesFailed = int(value.Int64)
			}
		case googledrivesync.FieldBytesTransferred:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bytes_transferred", values[i])
			} else if value.Valid {
				_m.BytesTransferred = value.Int64
			}
		case googledrivesync.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case googledrivesync.FieldErrorDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field error_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ErrorDetails); err != nil {
					return fmt.Errorf("unmarshal field error_details: %w", err)
				}
			}
		case googledrivesync.FieldChangeToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_token", values[i])
			} else if value.Valid {
				_m.ChangeToken = new(string)
				*_m.ChangeToken = value.String
			}
		case googledrivesync.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case googledrivesync.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoogleDriveSync.
// This includes values selected through modifiers, order, etc.
func (_m *GoogleDriveSync) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConnection queries the "connection" edge of the GoogleDriveSync entity.
func (_m *GoogleDriveSync) QueryConnection() *GoogleDriveConnectionQuery {
	return NewGoogleDriveSyncClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this GoogleDriveSync.
// Note that you need to call GoogleDriveSync.Unwrap() before calling this method if this GoogleDriveSync
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoogleDriveSync) Update() *GoogleDriveSyncUpdateOne {
	return NewGoogleDriveSyncClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoogleDriveSync entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoogleDriveSync) Unwrap() *GoogleDriveSync {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoogleDriveSync is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoogleDriveSync) String() string {
	var builder strings.Builder
	builder.WriteString("GoogleDriveSync(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("connection_id=")
	builder.WriteString(_m.ConnectionID)
	builder.WriteString(", ")
	if v := _m.FolderID; v != nil {
		builder.WriteString("folder_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sync_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("files_scanned=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesScanned))
	builder.WriteString(", ")
	builder.WriteString("files_downloaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesDownloaded))
	builder.WriteString(", ")
	builder.WriteString("files_uploaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesUploaded))
	builder.WriteString(", ")
	builder.WriteString("files_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesDeleted))
	builder.WriteString(", ")
	builder.WriteString("files_failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesFailed))
	builder.WriteString(", ")
	builder.WriteString("bytes_transferred=")
	builder.WriteString(fmt.Sprintf("%v", _m.BytesTransferred))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("error_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorDetails))
	builder.WriteString(", ")
	if v := _m.ChangeToken; v != nil {
		builder.WriteString("change_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GoogleDriveSyncs is a parsable slice of GoogleDriveSync.
type GoogleDriveSyncs []*GoogleDriveSync
