// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/googledrivesync"
	"clockzen-next/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoogleDriveSyncDelete is the builder for deleting a GoogleDriveSync entity.
type GoogleDriveSyncDelete struct {
	config
	hooks    []Hook
	mutation *GoogleDriveSyncMutation
}

// Where appends a list predicates to the GoogleDriveSyncDelete builder.
func (_d *GoogleDriveSyncDelete) Where(ps ...predicate.GoogleDriveSync) *GoogleDriveSyncDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GoogleDriveSyncDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GoogleDriveSyncDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GoogleDriveSyncDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(googledrivesync.Table, sqlgraph.NewFieldSpec(googledrivesync.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GoogleDriveSyncDeleteOne is the builder for deleting a single GoogleDriveSync entity.
type GoogleDriveSyncDeleteOne struct {
	_d *GoogleDriveSyncDelete
}

// Where appends a list predicates to the GoogleDriveSyncDelete builder.
func (_d *GoogleDriveSyncDeleteOne) Where(ps ...predicate.GoogleDriveSync) *GoogleDriveSyncDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GoogleDriveSyncDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{googledrivesync.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GoogleDriveSyncDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
