// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/googledriveconnection"
	"clockzen-next/internal/ent/googledrivesync"
	"clockzen-next/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoogleDriveSyncUpdate is the builder for updating GoogleDriveSync entities.
type GoogleDriveSyncUpdate struct {
	config
	hooks    []Hook
	mutation *GoogleDriveSyncMutation
}

// Where appends a list predicates to the GoogleDriveSyncUpdate builder.
func (_u *GoogleDriveSyncUpdate) Where(ps ...predicate.GoogleDriveSync) *GoogleDriveSyncUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *GoogleDriveSyncUpdate) SetConnectionID(v string) *GoogleDriveSyncUpdate {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableConnectionID(v *string) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *GoogleDriveSyncUpdate) SetFolderID(v string) *GoogleDriveSyncUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFolderID(v *string) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *GoogleDriveSyncUpdate) ClearFolderID() *GoogleDriveSyncUpdate {
	_u.mutation.ClearFolderID()
	return _u
}

// SetSyncType sets the "sync_type" field.
func (_u *GoogleDriveSyncUpdate) SetSyncType(v googledrivesync.SyncType) *GoogleDriveSyncUpdate {
	_u.mutation.SetSyncType(v)
	return _u
}

// SetNillableSyncType sets the "sync_type" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableSyncType(v *googledrivesync.SyncType) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetSyncType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoogleDriveSyncUpdate) SetStatus(v googledrivesync.Status) *GoogleDriveSyncUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableStatus(v *googledrivesync.Status) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *GoogleDriveSyncUpdate) SetStartedAt(v time.Time) *GoogleDriveSyncUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableStartedAt(v *time.Time) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *GoogleDriveSyncUpdate) ClearStartedAt() *GoogleDriveSyncUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GoogleDriveSyncUpdate) SetCompletedAt(v time.Time) *GoogleDriveSyncUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableCompletedAt(v *time.Time) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GoogleDriveSyncUpdate) ClearCompletedAt() *GoogleDriveSyncUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetFilesScanned sets the "files_scanned" field.
func (_u *GoogleDriveSyncUpdate) SetFilesScanned(v int) *GoogleDriveSyncUpdate {
	_u.mutation.ResetFilesScanned()
	_u.mutation.SetFilesScanned(v)
	return _u
}

// SetNillableFilesScanned sets the "files_scanned" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFilesScanned(v *int) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFilesScanned(*v)
	}
	return _u
}

// AddFilesScanned adds value to the "files_scanned" field.
func (_u *GoogleDriveSyncUpdate) AddFilesScanned(v int) *GoogleDriveSyncUpdate {
	_u.mutation.AddFilesScanned(v)
	return _u
}

// SetFilesDownloaded sets the "files_downloaded" field.
func (_u *GoogleDriveSyncUpdate) SetFilesDownloaded(v int) *GoogleDriveSyncUpdate {
	_u.mutation.ResetFilesDownloaded()
	_u.mutation.SetFilesDownloaded(v)
	return _u
}

// SetNillableFilesDownloaded sets the "files_downloaded" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFilesDownloaded(v *int) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFilesDownloaded(*v)
	}
	return _u
}

// AddFilesDownloaded adds value to the "files_downloaded" field.
func (_u *GoogleDriveSyncUpdate) AddFilesDownloaded(v int) *GoogleDriveSyncUpdate {
	_u.mutation.AddFilesDownloaded(v)
	return _u
}

// SetFilesUploaded sets the "files_uploaded" field.
func (_u *GoogleDriveSyncUpdate) SetFilesUploaded(v int) *GoogleDriveSyncUpdate {
	_u.mutation.ResetFilesUploaded()
	_u.mutation.SetFilesUploaded(v)
	return _u
}

// SetNillableFilesUploaded sets the "files_uploaded" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFilesUploaded(v *int) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFilesUploaded(*v)
	}
	return _u
}

// AddFilesUploaded adds value to the "files_uploaded" field.
func (_u *GoogleDriveSyncUpdate) AddFilesUploaded(v int) *GoogleDriveSyncUpdate {
	_u.mutation.AddFilesUploaded(v)
	return _u
}

// SetFilesDeleted sets the "files_deleted" field.
func (_u *GoogleDriveSyncUpdate) SetFilesDeleted(v int) *GoogleDriveSyncUpdate {
	_u.mutation.ResetFilesDeleted()
	_u.mutation.SetFilesDeleted(v)
	return _u
}

// SetNillableFilesDeleted sets the "files_deleted" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFilesDeleted(v *int) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFilesDeleted(*v)
	}
	return _u
}

// AddFilesDeleted adds value to the "files_deleted" field.
func (_u *GoogleDriveSyncUpdate) AddFilesDeleted(v int) *GoogleDriveSyncUpdate {
	_u.mutation.AddFilesDeleted(v)
	return _u
}

// SetFilesFailed sets the "files_failed" field.
func (_u *GoogleDriveSyncUpdate) SetFilesFailed(v int) *GoogleDriveSyncUpdate {
	_u.mutation.ResetFilesFailed()
	_u.mutation.SetFilesFailed(v)
	return _u
}

// SetNillableFilesFailed sets the "files_failed" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableFilesFailed(v *int) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetFilesFailed(*v)
	}
	return _u
}

// AddFilesFailed adds value to the "files_failed" field.
func (_u *GoogleDriveSyncUpdate) AddFilesFailed(v int) *GoogleDriveSyncUpdate {
	_u.mutation.AddFilesFailed(v)
	return _u
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_u *GoogleDriveSyncUpdate) SetBytesTransferred(v int64) *GoogleDriveSyncUpdate {
	_u.mutation.ResetBytesTransferred()
	_u.mutation.SetBytesTransferred(v)
	return _u
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableBytesTransferred(v *int64) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetBytesTransferred(*v)
	}
	return _u
}

// AddBytesTransferred adds value to the "bytes_transferred" field.
func (_u *GoogleDriveSyncUpdate) AddBytesTransferred(v int64) *GoogleDriveSyncUpdate {
	_u.mutation.AddBytesTransferred(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GoogleDriveSyncUpdate) SetErrorMessage(v string) *GoogleDriveSyncUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableErrorMessage(v *string) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *GoogleDriveSyncUpdate) ClearErrorMessage() *GoogleDriveSyncUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *GoogleDriveSyncUpdate) SetErrorDetails(v map[string]interface{}) *GoogleDriveSyncUpdate {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *GoogleDriveSyncUpdate) ClearErrorDetails() *GoogleDriveSyncUpdate {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetChangeToken sets the "change_token" field.
func (_u *GoogleDriveSyncUpdate) SetChangeToken(v string) *GoogleDriveSyncUpdate {
	_u.mutation.SetChangeToken(v)
	return _u
}

// SetNillableChangeToken sets the "change_token" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdate) SetNillableChangeToken(v *string) *GoogleDriveSyncUpdate {
	if v != nil {
		_u.SetChangeToken(*v)
	}
	return _u
}

// ClearChangeToken clears the value of the "change_token" field.
func (_u *GoogleDriveSyncUpdate) ClearChangeToken() *GoogleDriveSyncUpdate {
	_u.mutation.ClearChangeToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoogleDriveSyncUpdate) SetUpdatedAt(v time.Time) *GoogleDriveSyncUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConnection sets the "connection" edge to the GoogleDriveConnection entity.
func (_u *GoogleDriveSyncUpdate) SetConnection(v *GoogleDriveConnection) *GoogleDriveSyncUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the GoogleDriveSyncMutation object of the builder.
func (_u *GoogleDriveSyncUpdate) Mutation() *GoogleDriveSyncMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the GoogleDriveConnection entity.
func (_u *GoogleDriveSyncUpdate) ClearConnection() *GoogleDriveSyncUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoogleDriveSyncUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoogleDriveSyncUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoogleDriveSyncUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoogleDriveSyncUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoogleDriveSyncUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := googledrivesync.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoogleDriveSyncUpdate) check() error {
	if v, ok := _u.mutation.ConnectionID(); ok {
		if err := googledrivesync.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.connection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncType(); ok {
		if err := googledrivesync.SyncTypeValidator(v); err != nil {
			return &ValidationError{Name: "sync_type", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.sync_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := googledrivesync.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.status": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GoogleDriveSync.connection"`)
	}
	return nil
}

func (_u *GoogleDriveSyncUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(googledrivesync.Table, googledrivesync.Columns, sqlgraph.NewFieldSpec(googledrivesync.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(googledrivesync.FieldFolderID, field.TypeString, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(googledrivesync.FieldFolderID, field.TypeString)
	}
	if value, ok := _u.mutation.SyncType(); ok {
		_spec.SetField(googledrivesync.FieldSyncType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(googledrivesync.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(googledrivesync.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(googledrivesync.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(googledrivesync.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(googledrivesync.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FilesScanned(); ok {
		_spec.SetField(googledrivesync.FieldFilesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesScanned(); ok {
		_spec.AddField(googledrivesync.FieldFilesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesDownloaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesDownloaded(); ok {
		_spec.AddField(googledrivesync.FieldFilesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesUploaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesUploaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesUploaded(); ok {
		_spec.AddField(googledrivesync.FieldFilesUploaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesDeleted(); ok {
		_spec.SetField(googledrivesync.FieldFilesDeleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesDeleted(); ok {
		_spec.AddField(googledrivesync.FieldFilesDeleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesFailed(); ok {
		_spec.SetField(googledrivesync.FieldFilesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesFailed(); ok {
		_spec.AddField(googledrivesync.FieldFilesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BytesTransferred(); ok {
		_spec.SetField(googledrivesync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesTransferred(); ok {
		_spec.AddField(googledrivesync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(googledrivesync.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(googledrivesync.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(googledrivesync.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(googledrivesync.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.ChangeToken(); ok {
		_spec.SetField(googledrivesync.FieldChangeToken, field.TypeString, value)
	}
	if _u.mutation.ChangeTokenCleared() {
		_spec.ClearField(googledrivesync.FieldChangeToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(googledrivesync.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   googledrivesync.ConnectionTable,
			Columns: []string{googledrivesync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(googledriveconnection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   googledrivesync.ConnectionTable,
			Columns: []string{googledrivesync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(googledriveconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{googledrivesync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoogleDriveSyncUpdateOne is the builder for updating a single GoogleDriveSync entity.
type GoogleDriveSyncUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoogleDriveSyncMutation
}

// SetConnectionID sets the "connection_id" field.
func (_u *GoogleDriveSyncUpdateOne) SetConnectionID(v string) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableConnectionID(v *string) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *GoogleDriveSyncUpdateOne) SetFolderID(v string) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFolderID(v *string) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *GoogleDriveSyncUpdateOne) ClearFolderID() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearFolderID()
	return _u
}

// SetSyncType sets the "sync_type" field.
func (_u *GoogleDriveSyncUpdateOne) SetSyncType(v googledrivesync.SyncType) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetSyncType(v)
	return _u
}

// SetNillableSyncType sets the "sync_type" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableSyncType(v *googledrivesync.SyncType) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetSyncType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoogleDriveSyncUpdateOne) SetStatus(v googledrivesync.Status) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableStatus(v *googledrivesync.Status) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *GoogleDriveSyncUpdateOne) SetStartedAt(v time.Time) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableStartedAt(v *time.Time) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *GoogleDriveSyncUpdateOne) ClearStartedAt() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GoogleDriveSyncUpdateOne) SetCompletedAt(v time.Time) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableCompletedAt(v *time.Time) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GoogleDriveSyncUpdateOne) ClearCompletedAt() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetFilesScanned sets the "files_scanned" field.
func (_u *GoogleDriveSyncUpdateOne) SetFilesScanned(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetFilesScanned()
	_u.mutation.SetFilesScanned(v)
	return _u
}

// SetNillableFilesScanned sets the "files_scanned" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFilesScanned(v *int) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFilesScanned(*v)
	}
	return _u
}

// AddFilesScanned adds value to the "files_scanned" field.
func (_u *GoogleDriveSyncUpdateOne) AddFilesScanned(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddFilesScanned(v)
	return _u
}

// SetFilesDownloaded sets the "files_downloaded" field.
func (_u *GoogleDriveSyncUpdateOne) SetFilesDownloaded(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetFilesDownloaded()
	_u.mutation.SetFilesDownloaded(v)
	return _u
}

// SetNillableFilesDownloaded sets the "files_downloaded" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFilesDownloaded(v *int) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFilesDownloaded(*v)
	}
	return _u
}

// AddFilesDownloaded adds value to the "files_downloaded" field.
func (_u *GoogleDriveSyncUpdateOne) AddFilesDownloaded(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddFilesDownloaded(v)
	return _u
}

// SetFilesUploaded sets the "files_uploaded" field.
func (_u *GoogleDriveSyncUpdateOne) SetFilesUploaded(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetFilesUploaded()
	_u.mutation.SetFilesUploaded(v)
	return _u
}

// SetNillableFilesUploaded sets the "files_uploaded" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFilesUploaded(v *int) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFilesUploaded(*v)
	}
	return _u
}

// AddFilesUploaded adds value to the "files_uploaded" field.
func (_u *GoogleDriveSyncUpdateOne) AddFilesUploaded(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddFilesUploaded(v)
	return _u
}

// SetFilesDeleted sets the "files_deleted" field.
func (_u *GoogleDriveSyncUpdateOne) SetFilesDeleted(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetFilesDeleted()
	_u.mutation.SetFilesDeleted(v)
	return _u
}

// SetNillableFilesDeleted sets the "files_deleted" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFilesDeleted(v *int) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFilesDeleted(*v)
	}
	return _u
}

// AddFilesDeleted adds value to the "files_deleted" field.
func (_u *GoogleDriveSyncUpdateOne) AddFilesDeleted(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddFilesDeleted(v)
	return _u
}

// SetFilesFailed sets the "files_failed" field.
func (_u *GoogleDriveSyncUpdateOne) SetFilesFailed(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetFilesFailed()
	_u.mutation.SetFilesFailed(v)
	return _u
}

// SetNillableFilesFailed sets the "files_failed" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableFilesFailed(v *int) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetFilesFailed(*v)
	}
	return _u
}

// AddFilesFailed adds value to the "files_failed" field.
func (_u *GoogleDriveSyncUpdateOne) AddFilesFailed(v int) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddFilesFailed(v)
	return _u
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_u *GoogleDriveSyncUpdateOne) SetBytesTransferred(v int64) *GoogleDriveSyncUpdateOne {
	_u.mutation.ResetBytesTransferred()
	_u.mutation.SetBytesTransferred(v)
	return _u
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableBytesTransferred(v *int64) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetBytesTransferred(*v)
	}
	return _u
}

// AddBytesTransferred adds value to the "bytes_transferred" field.
func (_u *GoogleDriveSyncUpdateOne) AddBytesTransferred(v int64) *GoogleDriveSyncUpdateOne {
	_u.mutation.AddBytesTransferred(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GoogleDriveSyncUpdateOne) SetErrorMessage(v string) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableErrorMessage(v *string) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *GoogleDriveSyncUpdateOne) ClearErrorMessage() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorDetails sets the "error_details" field.
func (_u *GoogleDriveSyncUpdateOne) SetErrorDetails(v map[string]interface{}) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetErrorDetails(v)
	return _u
}

// ClearErrorDetails clears the value of the "error_details" field.
func (_u *GoogleDriveSyncUpdateOne) ClearErrorDetails() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearErrorDetails()
	return _u
}

// SetChangeToken sets the "change_token" field.
func (_u *GoogleDriveSyncUpdateOne) SetChangeToken(v string) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetChangeToken(v)
	return _u
}

// SetNillableChangeToken sets the "change_token" field if the given value is not nil.
func (_u *GoogleDriveSyncUpdateOne) SetNillableChangeToken(v *string) *GoogleDriveSyncUpdateOne {
	if v != nil {
		_u.SetChangeToken(*v)
	}
	return _u
}

// ClearChangeToken clears the value of the "change_token" field.
func (_u *GoogleDriveSyncUpdateOne) ClearChangeToken() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearChangeToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoogleDriveSyncUpdateOne) SetUpdatedAt(v time.Time) *GoogleDriveSyncUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConnection sets the "connection" edge to the GoogleDriveConnection entity.
func (_u *GoogleDriveSyncUpdateOne) SetConnection(v *GoogleDriveConnection) *GoogleDriveSyncUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the GoogleDriveSyncMutation object of the builder.
func (_u *GoogleDriveSyncUpdateOne) Mutation() *GoogleDriveSyncMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the GoogleDriveConnection entity.
func (_u *GoogleDriveSyncUpdateOne) ClearConnection() *GoogleDriveSyncUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the GoogleDriveSyncUpdate builder.
func (_u *GoogleDriveSyncUpdateOne) Where(ps ...predicate.GoogleDriveSync) *GoogleDriveSyncUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoogleDriveSyncUpdateOne) Select(field string, fields ...string) *GoogleDriveSyncUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoogleDriveSync entity.
func (_u *GoogleDriveSyncUpdateOne) Save(ctx context.Context) (*GoogleDriveSync, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoogleDriveSyncUpdateOne) SaveX(ctx context.Context) *GoogleDriveSync {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoogleDriveSyncUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoogleDriveSyncUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoogleDriveSyncUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := googledrivesync.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoogleDriveSyncUpdateOne) check() error {
	if v, ok := _u.mutation.ConnectionID(); ok {
		if err := googledrivesync.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.connection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncType(); ok {
		if err := googledrivesync.SyncTypeValidator(v); err != nil {
			return &ValidationError{Name: "sync_type", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.sync_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := googledrivesync.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.status": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GoogleDriveSync.connection"`)
	}
	return nil
}

func (_u *GoogleDriveSyncUpdateOne) sqlSave(ctx context.Context) (_node *GoogleDriveSync, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(googledrivesync.Table, googledrivesync.Columns, sqlgraph.NewFieldSpec(googledrivesync.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GoogleDriveSync.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, googledrivesync.FieldID)
		for _, f := range fields {
			if !googledrivesync.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != googledrivesync.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(googledrivesync.FieldFolderID, field.TypeString, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(googledrivesync.FieldFolderID, field.TypeString)
	}
	if value, ok := _u.mutation.SyncType(); ok {
		_spec.SetField(googledrivesync.FieldSyncType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(googledrivesync.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(googledrivesync.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(googledrivesync.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(googledrivesync.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(googledrivesync.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FilesScanned(); ok {
		_spec.SetField(googledrivesync.FieldFilesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesScanned(); ok {
		_spec.AddField(googledrivesync.FieldFilesScanned, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesDownloaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesDownloaded(); ok {
		_spec.AddField(googledrivesync.FieldFilesDownloaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesUploaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesUploaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesUploaded(); ok {
		_spec.AddField(googledrivesync.FieldFilesUploaded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesDeleted(); ok {
		_spec.SetField(googledrivesync.FieldFilesDeleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesDeleted(); ok {
		_spec.AddField(googledrivesync.FieldFilesDeleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesFailed(); ok {
		_spec.SetField(googledrivesync.FieldFilesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesFailed(); ok {
		_spec.AddField(googledrivesync.FieldFilesFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BytesTransferred(); ok {
		_spec.SetField(googledrivesync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytesTransferred(); ok {
		_spec.AddField(googledrivesync.FieldBytesTransferred, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(googledrivesync.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(googledrivesync.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorDetails(); ok {
		_spec.SetField(googledrivesync.FieldErrorDetails, field.TypeJSON, value)
	}
	if _u.mutation.ErrorDetailsCleared() {
		_spec.ClearField(googledrivesync.FieldErrorDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.ChangeToken(); ok {
		_spec.SetField(googledrivesync.FieldChangeToken, field.TypeString, value)
	}
	if _u.mutation.ChangeTokenCleared() {
		_spec.ClearField(googledrivesync.FieldChangeToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(googledrivesync.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   googledrivesync.ConnectionTable,
			Columns: []string{googledrivesync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(googledriveconnection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   googledrivesync.ConnectionTable,
			Columns: []string{googledrivesync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(googledriveconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GoogleDriveSync{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{googledrivesync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
