// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/googledriveconnection"
	"clockzen-next/internal/ent/googledrivesync"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoogleDriveSyncCreate is the builder for creating a GoogleDriveSync entity.
type GoogleDriveSyncCreate struct {
	config
	mutation *GoogleDriveSyncMutation
	hooks    []Hook
}

// SetConnectionID sets the "connection_id" field.
func (_c *GoogleDriveSyncCreate) SetConnectionID(v string) *GoogleDriveSyncCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetFolderID sets the "folder_id" field.
func (_c *GoogleDriveSyncCreate) SetFolderID(v string) *GoogleDriveSyncCreate {
	_c.mutation.SetFolderID(v)
	return _c
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFolderID(v *string) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFolderID(*v)
	}
	return _c
}

// SetSyncType sets the "sync_type" field.
func (_c *GoogleDriveSyncCreate) SetSyncType(v googledrivesync.SyncType) *GoogleDriveSyncCreate {
	_c.mutation.SetSyncType(v)
	return _c
}

// SetNillableSyncType sets the "sync_type" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableSyncType(v *googledrivesync.SyncType) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetSyncType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GoogleDriveSyncCreate) SetStatus(v googledrivesync.Status) *GoogleDriveSyncCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableStatus(v *googledrivesync.Status) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *GoogleDriveSyncCreate) SetStartedAt(v time.Time) *GoogleDriveSyncCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableStartedAt(v *time.Time) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *GoogleDriveSyncCreate) SetCompletedAt(v time.Time) *GoogleDriveSyncCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableCompletedAt(v *time.Time) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetFilesScanned sets the "files_scanned" field.
func (_c *GoogleDriveSyncCreate) SetFilesScanned(v int) *GoogleDriveSyncCreate {
	_c.mutation.SetFilesScanned(v)
	return _c
}

// SetNillableFilesScanned sets the "files_scanned" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFilesScanned(v *int) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFilesScanned(*v)
	}
	return _c
}

// SetFilesDownloaded sets the "files_downloaded" field.
func (_c *GoogleDriveSyncCreate) SetFilesDownloaded(v int) *GoogleDriveSyncCreate {
	_c.mutation.SetFilesDownloaded(v)
	return _c
}

// SetNillableFilesDownloaded sets the "files_downloaded" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFilesDownloaded(v *int) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFilesDownloaded(*v)
	}
	return _c
}

// SetFilesUploaded sets the "files_uploaded" field.
func (_c *GoogleDriveSyncCreate) SetFilesUploaded(v int) *GoogleDriveSyncCreate {
	_c.mutation.SetFilesUploaded(v)
	return _c
}

// SetNillableFilesUploaded sets the "files_uploaded" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFilesUploaded(v *int) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFilesUploaded(*v)
	}
	return _c
}

// SetFilesDeleted sets the "files_deleted" field.
func (_c *GoogleDriveSyncCreate) SetFilesDeleted(v int) *GoogleDriveSyncCreate {
	_c.mutation.SetFilesDeleted(v)
	return _c
}

// SetNillableFilesDeleted sets the "files_deleted" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFilesDeleted(v *int) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFilesDeleted(*v)
	}
	return _c
}

// SetFilesFailed sets the "files_failed" field.
func (_c *GoogleDriveSyncCreate) SetFilesFailed(v int) *GoogleDriveSyncCreate {
	_c.mutation.SetFilesFailed(v)
	return _c
}

// SetNillableFilesFailed sets the "files_failed" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableFilesFailed(v *int) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetFilesFailed(*v)
	}
	return _c
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_c *GoogleDriveSyncCreate) SetBytesTransferred(v int64) *GoogleDriveSyncCreate {
	_c.mutation.SetBytesTransferred(v)
	return _c
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableBytesTransferred(v *int64) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetBytesTransferred(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *GoogleDriveSyncCreate) SetErrorMessage(v string) *GoogleDriveSyncCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableErrorMessage(v *string) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetErrorDetails sets the "error_details" field.
func (_c *GoogleDriveSyncCreate) SetErrorDetails(v map[string]interface{}) *GoogleDriveSyncCreate {
	_c.mutation.SetErrorDetails(v)
	return _c
}

// SetChangeToken sets the "change_token" field.
func (_c *GoogleDriveSyncCreate) SetChangeToken(v string) *GoogleDriveSyncCreate {
	_c.mutation.SetChangeToken(v)
	return _c
}

// SetNillableChangeToken sets the "change_token" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableChangeToken(v *string) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetChangeToken(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoogleDriveSyncCreate) SetCreatedAt(v time.Time) *GoogleDriveSyncCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableCreatedAt(v *time.Time) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GoogleDriveSyncCreate) SetUpdatedAt(v time.Time) *GoogleDriveSyncCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GoogleDriveSyncCreate) SetNillableUpdatedAt(v *time.Time) *GoogleDriveSyncCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GoogleDriveSyncCreate) SetID(v string) *GoogleDriveSyncCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetConnection sets the "connection" edge to the GoogleDriveConnection entity.
func (_c *GoogleDriveSyncCreate) SetConnection(v *GoogleDriveConnection) *GoogleDriveSyncCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the GoogleDriveSyncMutation object of the builder.
func (_c *GoogleDriveSyncCreate) Mutation() *GoogleDriveSyncMutation {
	return _c.mutation
}

// Save creates the GoogleDriveSync in the database.
func (_c *GoogleDriveSyncCreate) Save(ctx context.Context) (*GoogleDriveSync, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoogleDriveSyncCreate) SaveX(ctx context.Context) *GoogleDriveSync {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoogleDriveSyncCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoogleDriveSyncCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoogleDriveSyncCreate) defaults() {
	if _, ok := _c.mutation.SyncType(); !ok {
		v := googledrivesync.DefaultSyncType
		_c.mutation.SetSyncType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := googledrivesync.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FilesScanned(); !ok {
		v := googledrivesync.DefaultFilesScanned
		_c.mutation.SetFilesScanned(v)
	}
	if _, ok := _c.mutation.FilesDownloaded(); !ok {
		v := googledrivesync.DefaultFilesDownloaded
		_c.mutation.SetFilesDownloaded(v)
	}
	if _, ok := _c.mutation.FilesUploaded(); !ok {
		v := googledrivesync.DefaultFilesUploaded
		_c.mutation.SetFilesUploaded(v)
	}
	if _, ok := _c.mutation.FilesDeleted(); !ok {
		v := googledrivesync.DefaultFilesDeleted
		_c.mutation.SetFilesDeleted(v)
	}
	if _, ok := _c.mutation.FilesFailed(); !ok {
		v := googledrivesync.DefaultFilesFailed
		_c.mutation.SetFilesFailed(v)
	}
	if _, ok := _c.mutation.BytesTransferred(); !ok {
		v := googledrivesync.DefaultBytesTransferred
		_c.mutation.SetBytesTransferred(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := googledrivesync.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := googledrivesync.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoogleDriveSyncCreate) check() error {
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "GoogleDriveSync.connection_id"`)}
	}
	if v, ok := _c.mutation.ConnectionID(); ok {
		if err := googledrivesync.ConnectionIDValidator(v); err != nil {
			return &ValidationError{Name: "connection_id", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.connection_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncType(); !ok {
		return &ValidationError{Name: "sync_type", err: errors.New(`ent: missing required field "GoogleDriveSync.sync_type"`)}
	}
	if v, ok := _c.mutation.SyncType(); ok {
		if err := googledrivesync.SyncTypeValidator(v); err != nil {
			return &ValidationError{Name: "sync_type", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.sync_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GoogleDriveSync.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := googledrivesync.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GoogleDriveSync.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FilesScanned(); !ok {
		return &ValidationError{Name: "files_scanned", err: errors.New(`ent: missing required field "GoogleDriveSync.files_scanned"`)}
	}
	if _, ok := _c.mutation.FilesDownloaded(); !ok {
		return &ValidationError{Name: "files_downloaded", err: errors.New(`ent: missing required field "GoogleDriveSync.files_downloaded"`)}
	}
	if _, ok := _c.mutation.FilesUploaded(); !ok {
		return &ValidationError{Name: "files_uploaded", err: errors.New(`ent: missing required field "GoogleDriveSync.files_uploaded"`)}
	}
	if _, ok := _c.mutation.FilesDeleted(); !ok {
		return &ValidationError{Name: "files_deleted", err: errors.New(`ent: missing required field "GoogleDriveSync.files_deleted"`)}
	}
	if _, ok := _c.mutation.FilesFailed(); !ok {
		return &ValidationError{Name: "files_failed", err: errors.New(`ent: missing required field "GoogleDriveSync.files_failed"`)}
	}
	if _, ok := _c.mutation.BytesTransferred(); !ok {
		return &ValidationError{Name: "bytes_transferred", err: errors.New(`ent: missing required field "GoogleDriveSync.bytes_transferred"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GoogleDriveSync.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GoogleDriveSync.updated_at"`)}
	}
	if len(_c.mutation.ConnectionIDs()) == 0 {
		return &ValidationError{Name: "connection", err: errors.New(`ent: missing required edge "GoogleDriveSync.connection"`)}
	}
	return nil
}

func (_c *GoogleDriveSyncCreate) sqlSave(ctx context.Context) (*GoogleDriveSync, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GoogleDriveSync.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoogleDriveSyncCreate) createSpec() (*GoogleDriveSync, *sqlgraph.CreateSpec) {
	var (
		_node = &GoogleDriveSync{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(googledrivesync.Table, sqlgraph.NewFieldSpec(googledrivesync.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.FolderID(); ok {
		_spec.SetField(googledrivesync.FieldFolderID, field.TypeString, value)
		_node.FolderID = &value
	}
	if value, ok := _c.mutation.SyncType(); ok {
		_spec.SetField(googledrivesync.FieldSyncType, field.TypeEnum, value)
		_node.SyncType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(googledrivesync.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(googledrivesync.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(googledrivesync.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.FilesScanned(); ok {
		_spec.SetField(googledrivesync.FieldFilesScanned, field.TypeInt, value)
		_node.FilesScanned = value
	}
	if value, ok := _c.mutation.FilesDownloaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesDownloaded, field.TypeInt, value)
		_node.FilesDownloaded = value
	}
	if value, ok := _c.mutation.FilesUploaded(); ok {
		_spec.SetField(googledrivesync.FieldFilesUploaded, field.TypeInt, value)
		_node.FilesUploaded = value
	}
	if value, ok := _c.mutation.FilesDeleted(); ok {
		_spec.SetField(googledrivesync.FieldFilesDeleted, field.TypeInt, value)
		_node.FilesDeleted = value
	}
	if value, ok := _c.mutation.FilesFailed(); ok {
		_spec.SetField(googledrivesync.FieldFilesFailed, field.TypeInt, value)
		_node.FilesFailed = value
	}
	if value, ok := _c.mutation.BytesTransferred(); ok {
		_spec.SetField(googledrivesync.FieldBytesTransferred, field.TypeInt64, value)
		_node.BytesTransferred = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(googledrivesync.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.ErrorDetails(); ok {
		_spec.SetField(googledrivesync.FieldErrorDetails, field.TypeJSON, value)
		_node.ErrorDetails = value
	}
	if value, ok := _c.mutation.ChangeToken(); ok {
		_spec.SetField(googledrivesync.FieldChangeToken, field.TypeString, value)
		_node.ChangeToken = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(googledrivesync.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(googledrivesync.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   googledrivesync.ConnectionTable,
			Columns: []string{googledrivesync.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(googledriveconnection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConnectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoogleDriveSyncCreateBulk is the builder for creating many GoogleDriveSync entities in bulk.
type GoogleDriveSyncCreateBulk struct {
	config
	err      error
	builders []*GoogleDriveSyncCreate
}

// Save creates the GoogleDriveSync entities in the database.
func (_c *GoogleDriveSyncCreateBulk) Save(ctx context.Context) ([]*GoogleDriveSync, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GoogleDriveSync, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoogleDriveSyncMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoogleDriveSyncCreateBulk) SaveX(ctx context.Context) []*GoogleDriveSync {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoogleDriveSyncCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoogleDriveSyncCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
