// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/pipelinerule"
	"clockzen-next/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PipelineRuleDelete is the builder for deleting a PipelineRule entity.
type PipelineRuleDelete struct {
	config
	hooks    []Hook
	mutation *PipelineRuleMutation
}

// Where appends a list predicates to the PipelineRuleDelete builder.
func (_d *PipelineRuleDelete) Where(ps ...predicate.PipelineRule) *PipelineRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PipelineRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PipelineRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PipelineRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pipelinerule.Table, sqlgraph.NewFieldSpec(pipelinerule.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PipelineRuleDeleteOne is the builder for deleting a single PipelineRule entity.
type PipelineRuleDeleteOne struct {
	_d *PipelineRuleDelete
}

// Where appends a list predicates to the PipelineRuleDelete builder.
func (_d *PipelineRuleDeleteOne) Where(ps ...predicate.PipelineRule) *PipelineRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PipelineRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pipelinerule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PipelineRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
