// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/pipelineconfig"
	"clockzen-next/internal/ent/pipelineversion"
	"clockzen-next/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PipelineVersionUpdate is the builder for updating PipelineVersion entities.
type PipelineVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PipelineVersionMutation
}

// Where appends a list predicates to the PipelineVersionUpdate builder.
func (_u *PipelineVersionUpdate) Where(ps ...predicate.PipelineVersion) *PipelineVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConfigID sets the "config_id" field.
func (_u *PipelineVersionUpdate) SetConfigID(v string) *PipelineVersionUpdate {
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableConfigID(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *PipelineVersionUpdate) SetVersionNumber(v int) *PipelineVersionUpdate {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableVersionNumber(v *int) *PipelineVersionUpdate {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *PipelineVersionUpdate) AddVersionNumber(v int) *PipelineVersionUpdate {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PipelineVersionUpdate) SetName(v string) *PipelineVersionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableName(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PipelineVersionUpdate) ClearName() *PipelineVersionUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PipelineVersionUpdate) SetDescription(v string) *PipelineVersionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableDescription(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PipelineVersionUpdate) ClearDescription() *PipelineVersionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *PipelineVersionUpdate) SetChangelog(v string) *PipelineVersionUpdate {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableChangelog(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *PipelineVersionUpdate) ClearChangelog() *PipelineVersionUpdate {
	_u.mutation.ClearChangelog()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *PipelineVersionUpdate) SetSnapshot(v map[string]interface{}) *PipelineVersionUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *PipelineVersionUpdate) ClearSnapshot() *PipelineVersionUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetRulesSnapshot sets the "rules_snapshot" field.
func (_u *PipelineVersionUpdate) SetRulesSnapshot(v []map[string]interface{}) *PipelineVersionUpdate {
	_u.mutation.SetRulesSnapshot(v)
	return _u
}

// AppendRulesSnapshot appends value to the "rules_snapshot" field.
func (_u *PipelineVersionUpdate) AppendRulesSnapshot(v []map[string]interface{}) *PipelineVersionUpdate {
	_u.mutation.AppendRulesSnapshot(v)
	return _u
}

// ClearRulesSnapshot clears the value of the "rules_snapshot" field.
func (_u *PipelineVersionUpdate) ClearRulesSnapshot() *PipelineVersionUpdate {
	_u.mutation.ClearRulesSnapshot()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PipelineVersionUpdate) SetStatus(v pipelineversion.Status) *PipelineVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableStatus(v *pipelineversion.Status) *PipelineVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *PipelineVersionUpdate) SetIsCurrent(v bool) *PipelineVersionUpdate {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableIsCurrent(v *bool) *PipelineVersionUpdate {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PipelineVersionUpdate) SetCreatedBy(v string) *PipelineVersionUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableCreatedBy(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PipelineVersionUpdate) ClearCreatedBy() *PipelineVersionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *PipelineVersionUpdate) SetApprovedBy(v string) *PipelineVersionUpdate {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableApprovedBy(v *string) *PipelineVersionUpdate {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *PipelineVersionUpdate) ClearApprovedBy() *PipelineVersionUpdate {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *PipelineVersionUpdate) SetApprovedAt(v time.Time) *PipelineVersionUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableApprovedAt(v *time.Time) *PipelineVersionUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *PipelineVersionUpdate) ClearApprovedAt() *PipelineVersionUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *PipelineVersionUpdate) SetActivatedAt(v time.Time) *PipelineVersionUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableActivatedAt(v *time.Time) *PipelineVersionUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *PipelineVersionUpdate) ClearActivatedAt() *PipelineVersionUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetDeprecatedAt sets the "deprecated_at" field.
func (_u *PipelineVersionUpdate) SetDeprecatedAt(v time.Time) *PipelineVersionUpdate {
	_u.mutation.SetDeprecatedAt(v)
	return _u
}

// SetNillableDeprecatedAt sets the "deprecated_at" field if the given value is not nil.
func (_u *PipelineVersionUpdate) SetNillableDeprecatedAt(v *time.Time) *PipelineVersionUpdate {
	if v != nil {
		_u.SetDeprecatedAt(*v)
	}
	return _u
}

// ClearDeprecatedAt clears the value of the "deprecated_at" field.
func (_u *PipelineVersionUpdate) ClearDeprecatedAt() *PipelineVersionUpdate {
	_u.mutation.ClearDeprecatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PipelineVersionUpdate) SetUpdatedAt(v time.Time) *PipelineVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfig sets the "config" edge to the PipelineConfig entity.
func (_u *PipelineVersionUpdate) SetConfig(v *PipelineConfig) *PipelineVersionUpdate {
	return _u.SetConfigID(v.ID)
}

// Mutation returns the PipelineVersionMutation object of the builder.
func (_u *PipelineVersionUpdate) Mutation() *PipelineVersionMutation {
	return _u.mutation
}

// ClearConfig clears the "config" edge to the PipelineConfig entity.
func (_u *PipelineVersionUpdate) ClearConfig() *PipelineVersionUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PipelineVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PipelineVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PipelineVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PipelineVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PipelineVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pipelineversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PipelineVersionUpdate) check() error {
	if v, ok := _u.mutation.ConfigID(); ok {
		if err := pipelineversion.ConfigIDValidator(v); err != nil {
			return &ValidationError{Name: "config_id", err: fmt.Errorf(`ent: validator failed for field "PipelineVersion.config_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pipelineversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PipelineVersion.status": %w`, err)}
		}
	}
	if _u.mutation.ConfigCleared() && len(_u.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PipelineVersion.config"`)
	}
	return nil
}

func (_u *PipelineVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pipelineversion.Table, pipelineversion.Columns, sqlgraph.NewFieldSpec(pipelineversion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(pipelineversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(pipelineversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pipelineversion.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(pipelineversion.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pipelineversion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(pipelineversion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(pipelineversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(pipelineversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(pipelineversion.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(pipelineversion.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RulesSnapshot(); ok {
		_spec.SetField(pipelineversion.FieldRulesSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRulesSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pipelineversion.FieldRulesSnapshot, value)
		})
	}
	if _u.mutation.RulesSnapshotCleared() {
		_spec.ClearField(pipelineversion.FieldRulesSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pipelineversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(pipelineversion.FieldIsCurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(pipelineversion.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(pipelineversion.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(pipelineversion.FieldApprovedBy, field.TypeString, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(pipelineversion.FieldApprovedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(pipelineversion.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(pipelineversion.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(pipelineversion.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(pipelineversion.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeprecatedAt(); ok {
		_spec.SetField(pipelineversion.FieldDeprecatedAt, field.TypeTime, value)
	}
	if _u.mutation.DeprecatedAtCleared() {
		_spec.ClearField(pipelineversion.FieldDeprecatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pipelineversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelineversion.ConfigTable,
			Columns: []string{pipelineversion.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pipelineconfig.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelineversion.ConfigTable,
			Columns: []string{pipelineversion.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pipelineconfig.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pipelineversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PipelineVersionUpdateOne is the builder for updating a single PipelineVersion entity.
type PipelineVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PipelineVersionMutation
}

// SetConfigID sets the "config_id" field.
func (_u *PipelineVersionUpdateOne) SetConfigID(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetConfigID(v)
	return _u
}

// SetNillableConfigID sets the "config_id" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableConfigID(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetConfigID(*v)
	}
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *PipelineVersionUpdateOne) SetVersionNumber(v int) *PipelineVersionUpdateOne {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableVersionNumber(v *int) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *PipelineVersionUpdateOne) AddVersionNumber(v int) *PipelineVersionUpdateOne {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PipelineVersionUpdateOne) SetName(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableName(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PipelineVersionUpdateOne) ClearName() *PipelineVersionUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PipelineVersionUpdateOne) SetDescription(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableDescription(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PipelineVersionUpdateOne) ClearDescription() *PipelineVersionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *PipelineVersionUpdateOne) SetChangelog(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableChangelog(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *PipelineVersionUpdateOne) ClearChangelog() *PipelineVersionUpdateOne {
	_u.mutation.ClearChangelog()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *PipelineVersionUpdateOne) SetSnapshot(v map[string]interface{}) *PipelineVersionUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *PipelineVersionUpdateOne) ClearSnapshot() *PipelineVersionUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetRulesSnapshot sets the "rules_snapshot" field.
func (_u *PipelineVersionUpdateOne) SetRulesSnapshot(v []map[string]interface{}) *PipelineVersionUpdateOne {
	_u.mutation.SetRulesSnapshot(v)
	return _u
}

// AppendRulesSnapshot appends value to the "rules_snapshot" field.
func (_u *PipelineVersionUpdateOne) AppendRulesSnapshot(v []map[string]interface{}) *PipelineVersionUpdateOne {
	_u.mutation.AppendRulesSnapshot(v)
	return _u
}

// ClearRulesSnapshot clears the value of the "rules_snapshot" field.
func (_u *PipelineVersionUpdateOne) ClearRulesSnapshot() *PipelineVersionUpdateOne {
	_u.mutation.ClearRulesSnapshot()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PipelineVersionUpdateOne) SetStatus(v pipelineversion.Status) *PipelineVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableStatus(v *pipelineversion.Status) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *PipelineVersionUpdateOne) SetIsCurrent(v bool) *PipelineVersionUpdateOne {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableIsCurrent(v *bool) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PipelineVersionUpdateOne) SetCreatedBy(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableCreatedBy(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PipelineVersionUpdateOne) ClearCreatedBy() *PipelineVersionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *PipelineVersionUpdateOne) SetApprovedBy(v string) *PipelineVersionUpdateOne {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableApprovedBy(v *string) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *PipelineVersionUpdateOne) ClearApprovedBy() *PipelineVersionUpdateOne {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *PipelineVersionUpdateOne) SetApprovedAt(v time.Time) *PipelineVersionUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableApprovedAt(v *time.Time) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *PipelineVersionUpdateOne) ClearApprovedAt() *PipelineVersionUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *PipelineVersionUpdateOne) SetActivatedAt(v time.Time) *PipelineVersionUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableActivatedAt(v *time.Time) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *PipelineVersionUpdateOne) ClearActivatedAt() *PipelineVersionUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetDeprecatedAt sets the "deprecated_at" field.
func (_u *PipelineVersionUpdateOne) SetDeprecatedAt(v time.Time) *PipelineVersionUpdateOne {
	_u.mutation.SetDeprecatedAt(v)
	return _u
}

// SetNillableDeprecatedAt sets the "deprecated_at" field if the given value is not nil.
func (_u *PipelineVersionUpdateOne) SetNillableDeprecatedAt(v *time.Time) *PipelineVersionUpdateOne {
	if v != nil {
		_u.SetDeprecatedAt(*v)
	}
	return _u
}

// ClearDeprecatedAt clears the value of the "deprecated_at" field.
func (_u *PipelineVersionUpdateOne) ClearDeprecatedAt() *PipelineVersionUpdateOne {
	_u.mutation.ClearDeprecatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PipelineVersionUpdateOne) SetUpdatedAt(v time.Time) *PipelineVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfig sets the "config" edge to the PipelineConfig entity.
func (_u *PipelineVersionUpdateOne) SetConfig(v *PipelineConfig) *PipelineVersionUpdateOne {
	return _u.SetConfigID(v.ID)
}

// Mutation returns the PipelineVersionMutation object of the builder.
func (_u *PipelineVersionUpdateOne) Mutation() *PipelineVersionMutation {
	return _u.mutation
}

// ClearConfig clears the "config" edge to the PipelineConfig entity.
func (_u *PipelineVersionUpdateOne) ClearConfig() *PipelineVersionUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// Where appends a list predicates to the PipelineVersionUpdate builder.
func (_u *PipelineVersionUpdateOne) Where(ps ...predicate.PipelineVersion) *PipelineVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PipelineVersionUpdateOne) Select(field string, fields ...string) *PipelineVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PipelineVersion entity.
func (_u *PipelineVersionUpdateOne) Save(ctx context.Context) (*PipelineVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PipelineVersionUpdateOne) SaveX(ctx context.Context) *PipelineVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PipelineVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PipelineVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PipelineVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pipelineversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PipelineVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ConfigID(); ok {
		if err := pipelineversion.ConfigIDValidator(v); err != nil {
			return &ValidationError{Name: "config_id", err: fmt.Errorf(`ent: validator failed for field "PipelineVersion.config_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pipelineversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PipelineVersion.status": %w`, err)}
		}
	}
	if _u.mutation.ConfigCleared() && len(_u.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PipelineVersion.config"`)
	}
	return nil
}

func (_u *PipelineVersionUpdateOne) sqlSave(ctx context.Context) (_node *PipelineVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pipelineversion.Table, pipelineversion.Columns, sqlgraph.NewFieldSpec(pipelineversion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PipelineVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pipelineversion.FieldID)
		for _, f := range fields {
			if !pipelineversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pipelineversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(pipelineversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(pipelineversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pipelineversion.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(pipelineversion.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pipelineversion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(pipelineversion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(pipelineversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(pipelineversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(pipelineversion.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(pipelineversion.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RulesSnapshot(); ok {
		_spec.SetField(pipelineversion.FieldRulesSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRulesSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pipelineversion.FieldRulesSnapshot, value)
		})
	}
	if _u.mutation.RulesSnapshotCleared() {
		_spec.ClearField(pipelineversion.FieldRulesSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pipelineversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(pipelineversion.FieldIsCurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(pipelineversion.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(pipelineversion.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(pipelineversion.FieldApprovedBy, field.TypeString, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(pipelineversion.FieldApprovedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(pipelineversion.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(pipelineversion.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(pipelineversion.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(pipelineversion.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeprecatedAt(); ok {
		_spec.SetField(pipelineversion.FieldDeprecatedAt, field.TypeTime, value)
	}
	if _u.mutation.DeprecatedAtCleared() {
		_spec.ClearField(pipelineversion.FieldDeprecatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pipelineversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelineversion.ConfigTable,
			Columns: []string{pipelineversion.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pipelineconfig.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pipelineversion.ConfigTable,
			Columns: []string{pipelineversion.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pipelineconfig.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PipelineVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pipelineversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
