// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/pipelineconfig"
	"clockzen-next/internal/ent/pipelineversion"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PipelineVersion is the model entity for the PipelineVersion schema.
type PipelineVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ID of the parent pipeline config
	ConfigID string `json:"config_id,omitempty"`
	// Version number (incrementing)
	VersionNumber int `json:"version_number,omitempty"`
	// Optional name for this version (e.g., 'Initial Release', 'Bug Fix')
	Name *string `json:"name,omitempty"`
	// Description of changes in this version
	Description *string `json:"description,omitempty"`
	// Detailed changelog for this version
	Changelog *string `json:"changelog,omitempty"`
	// Complete snapshot of the pipeline config at this version
	Snapshot map[string]interface{} `json:"snapshot,omitempty"`
	// Snapshot of all rules at this version
	RulesSnapshot []map[string]interface{} `json:"rules_snapshot,omitempty"`
	// Version status
	Status pipelineversion.Status `json:"status,omitempty"`
	// Whether this is the currently active version
	IsCurrent bool `json:"is_current,omitempty"`
	// User ID who created this version
	CreatedBy *string `json:"created_by,omitempty"`
	// User ID who approved this version
	ApprovedBy *string `json:"approved_by,omitempty"`
	// When the version was approved
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// When the version became active
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// When the version was deprecated
	DeprecatedAt *time.Time `json:"deprecated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PipelineVersionQuery when eager-loading is set.
	Edges        PipelineVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PipelineVersionEdges holds the relations/edges for other nodes in the graph.
type PipelineVersionEdges struct {
	// The pipeline config this version belongs to
	Config *PipelineConfig `json:"config,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConfigOrErr returns the Config value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PipelineVersionEdges) ConfigOrErr() (*PipelineConfig, error) {
	if e.Config != nil {
		return e.Config, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: pipelineconfig.Label}
	}
	return nil, &NotLoadedError{edge: "config"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PipelineVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pipelineversion.FieldSnapshot, pipelineversion.FieldRulesSnapshot:
			values[i] = new([]byte)
		case pipelineversion.FieldIsCurrent:
			values[i] = new(sql.NullBool)
		case pipelineversion.FieldVersionNumber:
			values[i] = new(sql.NullInt64)
		case pipelineversion.FieldID, pipelineversion.FieldConfigID, pipelineversion.FieldName, pipelineversion.FieldDescription, pipelineversion.FieldChangelog, pipelineversion.FieldStatus, pipelineversion.FieldCreatedBy, pipelineversion.FieldApprovedBy:
			values[i] = new(sql.NullString)
		case pipelineversion.FieldApprovedAt, pipelineversion.FieldActivatedAt, pipelineversion.FieldDeprecatedAt, pipelineversion.FieldCreatedAt, pipelineversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PipelineVersion fields.
func (_m *PipelineVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pipelineversion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case pipelineversion.FieldConfigID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_id", values[i])
			} else if value.Valid {
				_m.ConfigID = value.String
			}
		case pipelineversion.FieldVersionNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_number", values[i])
			} else if value.Valid {
				_m.VersionNumber = int(value.Int64)
			}
		case pipelineversion.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case pipelineversion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case pipelineversion.FieldChangelog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field changelog", values[i])
			} else if value.Valid {
				_m.Changelog = new(string)
				*_m.Changelog = value.String
			}
		case pipelineversion.FieldSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Snapshot); err != nil {
					return fmt.Errorf("unmarshal field snapshot: %w", err)
				}
			}
		case pipelineversion.FieldRulesSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rules_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RulesSnapshot); err != nil {
					return fmt.Errorf("unmarshal field rules_snapshot: %w", err)
				}
			}
		case pipelineversion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = pipelineversion.Status(value.String)
			}
		case pipelineversion.FieldIsCurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_current", values[i])
			} else if value.Valid {
				_m.IsCurrent = value.Bool
			}
		case pipelineversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(string)
				*_m.CreatedBy = value.String
			}
		case pipelineversion.FieldApprovedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by", values[i])
			} else if value.Valid {
				_m.ApprovedBy = new(string)
				*_m.ApprovedBy = value.String
			}
		case pipelineversion.FieldApprovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approved_at", values[i])
			} else if value.Valid {
				_m.ApprovedAt = new(time.Time)
				*_m.ApprovedAt = value.Time
			}
		case pipelineversion.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case pipelineversion.FieldDeprecatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deprecated_at", values[i])
			} else if value.Valid {
				_m.DeprecatedAt = new(time.Time)
				*_m.DeprecatedAt = value.Time
			}
		case pipelineversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pipelineversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PipelineVersion.
// This includes values selected through modifiers, order, etc.
func (_m *PipelineVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConfig queries the "config" edge of the PipelineVersion entity.
func (_m *PipelineVersion) QueryConfig() *PipelineConfigQuery {
	return NewPipelineVersionClient(_m.config).QueryConfig(_m)
}

// Update returns a builder for updating this PipelineVersion.
// Note that you need to call PipelineVersion.Unwrap() before calling this method if this PipelineVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PipelineVersion) Update() *PipelineVersionUpdateOne {
	return NewPipelineVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PipelineVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PipelineVersion) Unwrap() *PipelineVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PipelineVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PipelineVersion) String() string {
	var builder strings.Builder
	builder.WriteString("PipelineVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("config_id=")
	builder.WriteString(_m.ConfigID)
	builder.WriteString(", ")
	builder.WriteString("version_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.VersionNumber))
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Changelog; v != nil {
		builder.WriteString("changelog=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.Snapshot))
	builder.WriteString(", ")
	builder.WriteString("rules_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RulesSnapshot))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("is_current=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCurrent))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ApprovedBy; v != nil {
		builder.WriteString("approved_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ApprovedAt; v != nil {
		builder.WriteString("approved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeprecatedAt; v != nil {
		builder.WriteString("deprecated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PipelineVersions is a parsable slice of PipelineVersion.
type PipelineVersions []*PipelineVersion
