// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/emailconnection"
	"clockzen-next/internal/ent/emaillabel"
	"clockzen-next/internal/ent/emailsync"
	"clockzen-next/internal/ent/googledriveconnection"
	"clockzen-next/internal/ent/googledrivefolder"
	"clockzen-next/internal/ent/googledrivesync"
	"clockzen-next/internal/ent/lineitem"
	"clockzen-next/internal/ent/receipt"
	"clockzen-next/internal/ent/schema"
	"clockzen-next/internal/ent/transaction"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	emailconnectionFields := schema.EmailConnection{}.Fields()
	_ = emailconnectionFields
	// emailconnectionDescUserID is the schema descriptor for user_id field.
	emailconnectionDescUserID := emailconnectionFields[1].Descriptor()
	// emailconnection.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	emailconnection.UserIDValidator = emailconnectionDescUserID.Validators[0].(func(string) error)
	// emailconnectionDescProviderAccountID is the schema descriptor for provider_account_id field.
	emailconnectionDescProviderAccountID := emailconnectionFields[2].Descriptor()
	// emailconnection.ProviderAccountIDValidator is a validator for the "provider_account_id" field. It is called by the builders before save.
	emailconnection.ProviderAccountIDValidator = emailconnectionDescProviderAccountID.Validators[0].(func(string) error)
	// emailconnectionDescEmail is the schema descriptor for email field.
	emailconnectionDescEmail := emailconnectionFields[3].Descriptor()
	// emailconnection.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	emailconnection.EmailValidator = emailconnectionDescEmail.Validators[0].(func(string) error)
	// emailconnectionDescCreatedAt is the schema descriptor for created_at field.
	emailconnectionDescCreatedAt := emailconnectionFields[9].Descriptor()
	// emailconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailconnection.DefaultCreatedAt = emailconnectionDescCreatedAt.Default.(func() time.Time)
	// emailconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	emailconnectionDescUpdatedAt := emailconnectionFields[10].Descriptor()
	// emailconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	emailconnection.DefaultUpdatedAt = emailconnectionDescUpdatedAt.Default.(func() time.Time)
	// emailconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	emailconnection.UpdateDefaultUpdatedAt = emailconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	emaillabelFields := schema.EmailLabel{}.Fields()
	_ = emaillabelFields
	// emaillabelDescConnectionID is the schema descriptor for connection_id field.
	emaillabelDescConnectionID := emaillabelFields[1].Descriptor()
	// emaillabel.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	emaillabel.ConnectionIDValidator = emaillabelDescConnectionID.Validators[0].(func(string) error)
	// emaillabelDescProviderLabelID is the schema descriptor for provider_label_id field.
	emaillabelDescProviderLabelID := emaillabelFields[2].Descriptor()
	// emaillabel.ProviderLabelIDValidator is a validator for the "provider_label_id" field. It is called by the builders before save.
	emaillabel.ProviderLabelIDValidator = emaillabelDescProviderLabelID.Validators[0].(func(string) error)
	// emaillabelDescName is the schema descriptor for name field.
	emaillabelDescName := emaillabelFields[3].Descriptor()
	// emaillabel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	emaillabel.NameValidator = emaillabelDescName.Validators[0].(func(string) error)
	// emaillabelDescSyncEnabled is the schema descriptor for sync_enabled field.
	emaillabelDescSyncEnabled := emaillabelFields[7].Descriptor()
	// emaillabel.DefaultSyncEnabled holds the default value on creation for the sync_enabled field.
	emaillabel.DefaultSyncEnabled = emaillabelDescSyncEnabled.Default.(bool)
	// emaillabelDescMessageCount is the schema descriptor for message_count field.
	emaillabelDescMessageCount := emaillabelFields[8].Descriptor()
	// emaillabel.DefaultMessageCount holds the default value on creation for the message_count field.
	emaillabel.DefaultMessageCount = emaillabelDescMessageCount.Default.(int64)
	// emaillabelDescUnreadCount is the schema descriptor for unread_count field.
	emaillabelDescUnreadCount := emaillabelFields[9].Descriptor()
	// emaillabel.DefaultUnreadCount holds the default value on creation for the unread_count field.
	emaillabel.DefaultUnreadCount = emaillabelDescUnreadCount.Default.(int64)
	// emaillabelDescCreatedAt is the schema descriptor for created_at field.
	emaillabelDescCreatedAt := emaillabelFields[11].Descriptor()
	// emaillabel.DefaultCreatedAt holds the default value on creation for the created_at field.
	emaillabel.DefaultCreatedAt = emaillabelDescCreatedAt.Default.(func() time.Time)
	// emaillabelDescUpdatedAt is the schema descriptor for updated_at field.
	emaillabelDescUpdatedAt := emaillabelFields[12].Descriptor()
	// emaillabel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	emaillabel.DefaultUpdatedAt = emaillabelDescUpdatedAt.Default.(func() time.Time)
	// emaillabel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	emaillabel.UpdateDefaultUpdatedAt = emaillabelDescUpdatedAt.UpdateDefault.(func() time.Time)
	emailsyncFields := schema.EmailSync{}.Fields()
	_ = emailsyncFields
	// emailsyncDescConnectionID is the schema descriptor for connection_id field.
	emailsyncDescConnectionID := emailsyncFields[1].Descriptor()
	// emailsync.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	emailsync.ConnectionIDValidator = emailsyncDescConnectionID.Validators[0].(func(string) error)
	// emailsyncDescMessagesScanned is the schema descriptor for messages_scanned field.
	emailsyncDescMessagesScanned := emailsyncFields[7].Descriptor()
	// emailsync.DefaultMessagesScanned holds the default value on creation for the messages_scanned field.
	emailsync.DefaultMessagesScanned = emailsyncDescMessagesScanned.Default.(int)
	// emailsyncDescMessagesDownloaded is the schema descriptor for messages_downloaded field.
	emailsyncDescMessagesDownloaded := emailsyncFields[8].Descriptor()
	// emailsync.DefaultMessagesDownloaded holds the default value on creation for the messages_downloaded field.
	emailsync.DefaultMessagesDownloaded = emailsyncDescMessagesDownloaded.Default.(int)
	// emailsyncDescMessagesIndexed is the schema descriptor for messages_indexed field.
	emailsyncDescMessagesIndexed := emailsyncFields[9].Descriptor()
	// emailsync.DefaultMessagesIndexed holds the default value on creation for the messages_indexed field.
	emailsync.DefaultMessagesIndexed = emailsyncDescMessagesIndexed.Default.(int)
	// emailsyncDescMessagesFailed is the schema descriptor for messages_failed field.
	emailsyncDescMessagesFailed := emailsyncFields[10].Descriptor()
	// emailsync.DefaultMessagesFailed holds the default value on creation for the messages_failed field.
	emailsync.DefaultMessagesFailed = emailsyncDescMessagesFailed.Default.(int)
	// emailsyncDescAttachmentsDownloaded is the schema descriptor for attachments_downloaded field.
	emailsyncDescAttachmentsDownloaded := emailsyncFields[11].Descriptor()
	// emailsync.DefaultAttachmentsDownloaded holds the default value on creation for the attachments_downloaded field.
	emailsync.DefaultAttachmentsDownloaded = emailsyncDescAttachmentsDownloaded.Default.(int)
	// emailsyncDescBytesTransferred is the schema descriptor for bytes_transferred field.
	emailsyncDescBytesTransferred := emailsyncFields[12].Descriptor()
	// emailsync.DefaultBytesTransferred holds the default value on creation for the bytes_transferred field.
	emailsync.DefaultBytesTransferred = emailsyncDescBytesTransferred.Default.(int64)
	// emailsyncDescCreatedAt is the schema descriptor for created_at field.
	emailsyncDescCreatedAt := emailsyncFields[16].Descriptor()
	// emailsync.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailsync.DefaultCreatedAt = emailsyncDescCreatedAt.Default.(func() time.Time)
	// emailsyncDescUpdatedAt is the schema descriptor for updated_at field.
	emailsyncDescUpdatedAt := emailsyncFields[17].Descriptor()
	// emailsync.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	emailsync.DefaultUpdatedAt = emailsyncDescUpdatedAt.Default.(func() time.Time)
	// emailsync.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	emailsync.UpdateDefaultUpdatedAt = emailsyncDescUpdatedAt.UpdateDefault.(func() time.Time)
	googledriveconnectionFields := schema.GoogleDriveConnection{}.Fields()
	_ = googledriveconnectionFields
	// googledriveconnectionDescUserID is the schema descriptor for user_id field.
	googledriveconnectionDescUserID := googledriveconnectionFields[1].Descriptor()
	// googledriveconnection.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	googledriveconnection.UserIDValidator = googledriveconnectionDescUserID.Validators[0].(func(string) error)
	// googledriveconnectionDescGoogleAccountID is the schema descriptor for google_account_id field.
	googledriveconnectionDescGoogleAccountID := googledriveconnectionFields[2].Descriptor()
	// googledriveconnection.GoogleAccountIDValidator is a validator for the "google_account_id" field. It is called by the builders before save.
	googledriveconnection.GoogleAccountIDValidator = googledriveconnectionDescGoogleAccountID.Validators[0].(func(string) error)
	// googledriveconnectionDescEmail is the schema descriptor for email field.
	googledriveconnectionDescEmail := googledriveconnectionFields[3].Descriptor()
	// googledriveconnection.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	googledriveconnection.EmailValidator = googledriveconnectionDescEmail.Validators[0].(func(string) error)
	// googledriveconnectionDescCreatedAt is the schema descriptor for created_at field.
	googledriveconnectionDescCreatedAt := googledriveconnectionFields[8].Descriptor()
	// googledriveconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledriveconnection.DefaultCreatedAt = googledriveconnectionDescCreatedAt.Default.(func() time.Time)
	// googledriveconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	googledriveconnectionDescUpdatedAt := googledriveconnectionFields[9].Descriptor()
	// googledriveconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledriveconnection.DefaultUpdatedAt = googledriveconnectionDescUpdatedAt.Default.(func() time.Time)
	// googledriveconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledriveconnection.UpdateDefaultUpdatedAt = googledriveconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	googledrivefolderFields := schema.GoogleDriveFolder{}.Fields()
	_ = googledrivefolderFields
	// googledrivefolderDescConnectionID is the schema descriptor for connection_id field.
	googledrivefolderDescConnectionID := googledrivefolderFields[1].Descriptor()
	// googledrivefolder.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	googledrivefolder.ConnectionIDValidator = googledrivefolderDescConnectionID.Validators[0].(func(string) error)
	// googledrivefolderDescDriveFolderID is the schema descriptor for drive_folder_id field.
	googledrivefolderDescDriveFolderID := googledrivefolderFields[2].Descriptor()
	// googledrivefolder.DriveFolderIDValidator is a validator for the "drive_folder_id" field. It is called by the builders before save.
	googledrivefolder.DriveFolderIDValidator = googledrivefolderDescDriveFolderID.Validators[0].(func(string) error)
	// googledrivefolderDescName is the schema descriptor for name field.
	googledrivefolderDescName := googledrivefolderFields[3].Descriptor()
	// googledrivefolder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	googledrivefolder.NameValidator = googledrivefolderDescName.Validators[0].(func(string) error)
	// googledrivefolderDescIsRoot is the schema descriptor for is_root field.
	googledrivefolderDescIsRoot := googledrivefolderFields[6].Descriptor()
	// googledrivefolder.DefaultIsRoot holds the default value on creation for the is_root field.
	googledrivefolder.DefaultIsRoot = googledrivefolderDescIsRoot.Default.(bool)
	// googledrivefolderDescSyncEnabled is the schema descriptor for sync_enabled field.
	googledrivefolderDescSyncEnabled := googledrivefolderFields[7].Descriptor()
	// googledrivefolder.DefaultSyncEnabled holds the default value on creation for the sync_enabled field.
	googledrivefolder.DefaultSyncEnabled = googledrivefolderDescSyncEnabled.Default.(bool)
	// googledrivefolderDescFileCount is the schema descriptor for file_count field.
	googledrivefolderDescFileCount := googledrivefolderFields[9].Descriptor()
	// googledrivefolder.DefaultFileCount holds the default value on creation for the file_count field.
	googledrivefolder.DefaultFileCount = googledrivefolderDescFileCount.Default.(int64)
	// googledrivefolderDescTotalSizeBytes is the schema descriptor for total_size_bytes field.
	googledrivefolderDescTotalSizeBytes := googledrivefolderFields[10].Descriptor()
	// googledrivefolder.DefaultTotalSizeBytes holds the default value on creation for the total_size_bytes field.
	googledrivefolder.DefaultTotalSizeBytes = googledrivefolderDescTotalSizeBytes.Default.(int64)
	// googledrivefolderDescCreatedAt is the schema descriptor for created_at field.
	googledrivefolderDescCreatedAt := googledrivefolderFields[11].Descriptor()
	// googledrivefolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledrivefolder.DefaultCreatedAt = googledrivefolderDescCreatedAt.Default.(func() time.Time)
	// googledrivefolderDescUpdatedAt is the schema descriptor for updated_at field.
	googledrivefolderDescUpdatedAt := googledrivefolderFields[12].Descriptor()
	// googledrivefolder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledrivefolder.DefaultUpdatedAt = googledrivefolderDescUpdatedAt.Default.(func() time.Time)
	// googledrivefolder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledrivefolder.UpdateDefaultUpdatedAt = googledrivefolderDescUpdatedAt.UpdateDefault.(func() time.Time)
	googledrivesyncFields := schema.GoogleDriveSync{}.Fields()
	_ = googledrivesyncFields
	// googledrivesyncDescConnectionID is the schema descriptor for connection_id field.
	googledrivesyncDescConnectionID := googledrivesyncFields[1].Descriptor()
	// googledrivesync.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	googledrivesync.ConnectionIDValidator = googledrivesyncDescConnectionID.Validators[0].(func(string) error)
	// googledrivesyncDescFilesScanned is the schema descriptor for files_scanned field.
	googledrivesyncDescFilesScanned := googledrivesyncFields[7].Descriptor()
	// googledrivesync.DefaultFilesScanned holds the default value on creation for the files_scanned field.
	googledrivesync.DefaultFilesScanned = googledrivesyncDescFilesScanned.Default.(int)
	// googledrivesyncDescFilesDownloaded is the schema descriptor for files_downloaded field.
	googledrivesyncDescFilesDownloaded := googledrivesyncFields[8].Descriptor()
	// googledrivesync.DefaultFilesDownloaded holds the default value on creation for the files_downloaded field.
	googledrivesync.DefaultFilesDownloaded = googledrivesyncDescFilesDownloaded.Default.(int)
	// googledrivesyncDescFilesUploaded is the schema descriptor for files_uploaded field.
	googledrivesyncDescFilesUploaded := googledrivesyncFields[9].Descriptor()
	// googledrivesync.DefaultFilesUploaded holds the default value on creation for the files_uploaded field.
	googledrivesync.DefaultFilesUploaded = googledrivesyncDescFilesUploaded.Default.(int)
	// googledrivesyncDescFilesDeleted is the schema descriptor for files_deleted field.
	googledrivesyncDescFilesDeleted := googledrivesyncFields[10].Descriptor()
	// googledrivesync.DefaultFilesDeleted holds the default value on creation for the files_deleted field.
	googledrivesync.DefaultFilesDeleted = googledrivesyncDescFilesDeleted.Default.(int)
	// googledrivesyncDescFilesFailed is the schema descriptor for files_failed field.
	googledrivesyncDescFilesFailed := googledrivesyncFields[11].Descriptor()
	// googledrivesync.DefaultFilesFailed holds the default value on creation for the files_failed field.
	googledrivesync.DefaultFilesFailed = googledrivesyncDescFilesFailed.Default.(int)
	// googledrivesyncDescBytesTransferred is the schema descriptor for bytes_transferred field.
	googledrivesyncDescBytesTransferred := googledrivesyncFields[12].Descriptor()
	// googledrivesync.DefaultBytesTransferred holds the default value on creation for the bytes_transferred field.
	googledrivesync.DefaultBytesTransferred = googledrivesyncDescBytesTransferred.Default.(int64)
	// googledrivesyncDescCreatedAt is the schema descriptor for created_at field.
	googledrivesyncDescCreatedAt := googledrivesyncFields[16].Descriptor()
	// googledrivesync.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledrivesync.DefaultCreatedAt = googledrivesyncDescCreatedAt.Default.(func() time.Time)
	// googledrivesyncDescUpdatedAt is the schema descriptor for updated_at field.
	googledrivesyncDescUpdatedAt := googledrivesyncFields[17].Descriptor()
	// googledrivesync.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledrivesync.DefaultUpdatedAt = googledrivesyncDescUpdatedAt.Default.(func() time.Time)
	// googledrivesync.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledrivesync.UpdateDefaultUpdatedAt = googledrivesyncDescUpdatedAt.UpdateDefault.(func() time.Time)
	lineitemFields := schema.LineItem{}.Fields()
	_ = lineitemFields
	// lineitemDescReceiptID is the schema descriptor for receipt_id field.
	lineitemDescReceiptID := lineitemFields[1].Descriptor()
	// lineitem.ReceiptIDValidator is a validator for the "receipt_id" field. It is called by the builders before save.
	lineitem.ReceiptIDValidator = lineitemDescReceiptID.Validators[0].(func(string) error)
	// lineitemDescLineNumber is the schema descriptor for line_number field.
	lineitemDescLineNumber := lineitemFields[2].Descriptor()
	// lineitem.DefaultLineNumber holds the default value on creation for the line_number field.
	lineitem.DefaultLineNumber = lineitemDescLineNumber.Default.(int)
	// lineitemDescDescription is the schema descriptor for description field.
	lineitemDescDescription := lineitemFields[3].Descriptor()
	// lineitem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	lineitem.DescriptionValidator = lineitemDescDescription.Validators[0].(func(string) error)
	// lineitemDescQuantity is the schema descriptor for quantity field.
	lineitemDescQuantity := lineitemFields[6].Descriptor()
	// lineitem.DefaultQuantity holds the default value on creation for the quantity field.
	lineitem.DefaultQuantity = lineitemDescQuantity.Default.(float64)
	// lineitemDescDiscountAmount is the schema descriptor for discount_amount field.
	lineitemDescDiscountAmount := lineitemFields[10].Descriptor()
	// lineitem.DefaultDiscountAmount holds the default value on creation for the discount_amount field.
	lineitem.DefaultDiscountAmount = lineitemDescDiscountAmount.Default.(float64)
	// lineitemDescTaxAmount is the schema descriptor for tax_amount field.
	lineitemDescTaxAmount := lineitemFields[12].Descriptor()
	// lineitem.DefaultTaxAmount holds the default value on creation for the tax_amount field.
	lineitem.DefaultTaxAmount = lineitemDescTaxAmount.Default.(float64)
	// lineitemDescIsTaxable is the schema descriptor for is_taxable field.
	lineitemDescIsTaxable := lineitemFields[14].Descriptor()
	// lineitem.DefaultIsTaxable holds the default value on creation for the is_taxable field.
	lineitem.DefaultIsTaxable = lineitemDescIsTaxable.Default.(bool)
	// lineitemDescCreatedAt is the schema descriptor for created_at field.
	lineitemDescCreatedAt := lineitemFields[19].Descriptor()
	// lineitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	lineitem.DefaultCreatedAt = lineitemDescCreatedAt.Default.(func() time.Time)
	// lineitemDescUpdatedAt is the schema descriptor for updated_at field.
	lineitemDescUpdatedAt := lineitemFields[20].Descriptor()
	// lineitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lineitem.DefaultUpdatedAt = lineitemDescUpdatedAt.Default.(func() time.Time)
	// lineitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	lineitem.UpdateDefaultUpdatedAt = lineitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	receiptFields := schema.Receipt{}.Fields()
	_ = receiptFields
	// receiptDescUserID is the schema descriptor for user_id field.
	receiptDescUserID := receiptFields[1].Descriptor()
	// receipt.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	receipt.UserIDValidator = receiptDescUserID.Validators[0].(func(string) error)
	// receiptDescFileName is the schema descriptor for file_name field.
	receiptDescFileName := receiptFields[5].Descriptor()
	// receipt.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	receipt.FileNameValidator = receiptDescFileName.Validators[0].(func(string) error)
	// receiptDescMimeType is the schema descriptor for mime_type field.
	receiptDescMimeType := receiptFields[7].Descriptor()
	// receipt.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	receipt.MimeTypeValidator = receiptDescMimeType.Validators[0].(func(string) error)
	// receiptDescFileSize is the schema descriptor for file_size field.
	receiptDescFileSize := receiptFields[8].Descriptor()
	// receipt.DefaultFileSize holds the default value on creation for the file_size field.
	receipt.DefaultFileSize = receiptDescFileSize.Default.(int64)
	// receiptDescOcrCompleted is the schema descriptor for ocr_completed field.
	receiptDescOcrCompleted := receiptFields[13].Descriptor()
	// receipt.DefaultOcrCompleted holds the default value on creation for the ocr_completed field.
	receipt.DefaultOcrCompleted = receiptDescOcrCompleted.Default.(bool)
	// receiptDescCurrency is the schema descriptor for currency field.
	receiptDescCurrency := receiptFields[22].Descriptor()
	// receipt.DefaultCurrency holds the default value on creation for the currency field.
	receipt.DefaultCurrency = receiptDescCurrency.Default.(string)
	// receiptDescCreatedAt is the schema descriptor for created_at field.
	receiptDescCreatedAt := receiptFields[30].Descriptor()
	// receipt.DefaultCreatedAt holds the default value on creation for the created_at field.
	receipt.DefaultCreatedAt = receiptDescCreatedAt.Default.(func() time.Time)
	// receiptDescUpdatedAt is the schema descriptor for updated_at field.
	receiptDescUpdatedAt := receiptFields[31].Descriptor()
	// receipt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	receipt.DefaultUpdatedAt = receiptDescUpdatedAt.Default.(func() time.Time)
	// receipt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	receipt.UpdateDefaultUpdatedAt = receiptDescUpdatedAt.UpdateDefault.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescReceiptID is the schema descriptor for receipt_id field.
	transactionDescReceiptID := transactionFields[1].Descriptor()
	// transaction.ReceiptIDValidator is a validator for the "receipt_id" field. It is called by the builders before save.
	transaction.ReceiptIDValidator = transactionDescReceiptID.Validators[0].(func(string) error)
	// transactionDescUserID is the schema descriptor for user_id field.
	transactionDescUserID := transactionFields[2].Descriptor()
	// transaction.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	transaction.UserIDValidator = transactionDescUserID.Validators[0].(func(string) error)
	// transactionDescCurrency is the schema descriptor for currency field.
	transactionDescCurrency := transactionFields[5].Descriptor()
	// transaction.DefaultCurrency holds the default value on creation for the currency field.
	transaction.DefaultCurrency = transactionDescCurrency.Default.(string)
	// transactionDescIsRecurring is the schema descriptor for is_recurring field.
	transactionDescIsRecurring := transactionFields[15].Descriptor()
	// transaction.DefaultIsRecurring holds the default value on creation for the is_recurring field.
	transaction.DefaultIsRecurring = transactionDescIsRecurring.Default.(bool)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[21].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionFields[22].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
