// Code generated by ent, DO NOT EDIT.

package ent

import (
	"clockzen-next/internal/ent/googledriveconnection"
	"clockzen-next/internal/ent/googledrivefolder"
	"clockzen-next/internal/ent/googledrivesync"
	"clockzen-next/internal/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	googledriveconnectionFields := schema.GoogleDriveConnection{}.Fields()
	_ = googledriveconnectionFields
	// googledriveconnectionDescUserID is the schema descriptor for user_id field.
	googledriveconnectionDescUserID := googledriveconnectionFields[1].Descriptor()
	// googledriveconnection.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	googledriveconnection.UserIDValidator = googledriveconnectionDescUserID.Validators[0].(func(string) error)
	// googledriveconnectionDescGoogleAccountID is the schema descriptor for google_account_id field.
	googledriveconnectionDescGoogleAccountID := googledriveconnectionFields[2].Descriptor()
	// googledriveconnection.GoogleAccountIDValidator is a validator for the "google_account_id" field. It is called by the builders before save.
	googledriveconnection.GoogleAccountIDValidator = googledriveconnectionDescGoogleAccountID.Validators[0].(func(string) error)
	// googledriveconnectionDescEmail is the schema descriptor for email field.
	googledriveconnectionDescEmail := googledriveconnectionFields[3].Descriptor()
	// googledriveconnection.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	googledriveconnection.EmailValidator = googledriveconnectionDescEmail.Validators[0].(func(string) error)
	// googledriveconnectionDescCreatedAt is the schema descriptor for created_at field.
	googledriveconnectionDescCreatedAt := googledriveconnectionFields[8].Descriptor()
	// googledriveconnection.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledriveconnection.DefaultCreatedAt = googledriveconnectionDescCreatedAt.Default.(func() time.Time)
	// googledriveconnectionDescUpdatedAt is the schema descriptor for updated_at field.
	googledriveconnectionDescUpdatedAt := googledriveconnectionFields[9].Descriptor()
	// googledriveconnection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledriveconnection.DefaultUpdatedAt = googledriveconnectionDescUpdatedAt.Default.(func() time.Time)
	// googledriveconnection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledriveconnection.UpdateDefaultUpdatedAt = googledriveconnectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	googledrivefolderFields := schema.GoogleDriveFolder{}.Fields()
	_ = googledrivefolderFields
	// googledrivefolderDescConnectionID is the schema descriptor for connection_id field.
	googledrivefolderDescConnectionID := googledrivefolderFields[1].Descriptor()
	// googledrivefolder.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	googledrivefolder.ConnectionIDValidator = googledrivefolderDescConnectionID.Validators[0].(func(string) error)
	// googledrivefolderDescDriveFolderID is the schema descriptor for drive_folder_id field.
	googledrivefolderDescDriveFolderID := googledrivefolderFields[2].Descriptor()
	// googledrivefolder.DriveFolderIDValidator is a validator for the "drive_folder_id" field. It is called by the builders before save.
	googledrivefolder.DriveFolderIDValidator = googledrivefolderDescDriveFolderID.Validators[0].(func(string) error)
	// googledrivefolderDescName is the schema descriptor for name field.
	googledrivefolderDescName := googledrivefolderFields[3].Descriptor()
	// googledrivefolder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	googledrivefolder.NameValidator = googledrivefolderDescName.Validators[0].(func(string) error)
	// googledrivefolderDescIsRoot is the schema descriptor for is_root field.
	googledrivefolderDescIsRoot := googledrivefolderFields[6].Descriptor()
	// googledrivefolder.DefaultIsRoot holds the default value on creation for the is_root field.
	googledrivefolder.DefaultIsRoot = googledrivefolderDescIsRoot.Default.(bool)
	// googledrivefolderDescSyncEnabled is the schema descriptor for sync_enabled field.
	googledrivefolderDescSyncEnabled := googledrivefolderFields[7].Descriptor()
	// googledrivefolder.DefaultSyncEnabled holds the default value on creation for the sync_enabled field.
	googledrivefolder.DefaultSyncEnabled = googledrivefolderDescSyncEnabled.Default.(bool)
	// googledrivefolderDescFileCount is the schema descriptor for file_count field.
	googledrivefolderDescFileCount := googledrivefolderFields[9].Descriptor()
	// googledrivefolder.DefaultFileCount holds the default value on creation for the file_count field.
	googledrivefolder.DefaultFileCount = googledrivefolderDescFileCount.Default.(int64)
	// googledrivefolderDescTotalSizeBytes is the schema descriptor for total_size_bytes field.
	googledrivefolderDescTotalSizeBytes := googledrivefolderFields[10].Descriptor()
	// googledrivefolder.DefaultTotalSizeBytes holds the default value on creation for the total_size_bytes field.
	googledrivefolder.DefaultTotalSizeBytes = googledrivefolderDescTotalSizeBytes.Default.(int64)
	// googledrivefolderDescCreatedAt is the schema descriptor for created_at field.
	googledrivefolderDescCreatedAt := googledrivefolderFields[11].Descriptor()
	// googledrivefolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledrivefolder.DefaultCreatedAt = googledrivefolderDescCreatedAt.Default.(func() time.Time)
	// googledrivefolderDescUpdatedAt is the schema descriptor for updated_at field.
	googledrivefolderDescUpdatedAt := googledrivefolderFields[12].Descriptor()
	// googledrivefolder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledrivefolder.DefaultUpdatedAt = googledrivefolderDescUpdatedAt.Default.(func() time.Time)
	// googledrivefolder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledrivefolder.UpdateDefaultUpdatedAt = googledrivefolderDescUpdatedAt.UpdateDefault.(func() time.Time)
	googledrivesyncFields := schema.GoogleDriveSync{}.Fields()
	_ = googledrivesyncFields
	// googledrivesyncDescConnectionID is the schema descriptor for connection_id field.
	googledrivesyncDescConnectionID := googledrivesyncFields[1].Descriptor()
	// googledrivesync.ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	googledrivesync.ConnectionIDValidator = googledrivesyncDescConnectionID.Validators[0].(func(string) error)
	// googledrivesyncDescFilesScanned is the schema descriptor for files_scanned field.
	googledrivesyncDescFilesScanned := googledrivesyncFields[7].Descriptor()
	// googledrivesync.DefaultFilesScanned holds the default value on creation for the files_scanned field.
	googledrivesync.DefaultFilesScanned = googledrivesyncDescFilesScanned.Default.(int)
	// googledrivesyncDescFilesDownloaded is the schema descriptor for files_downloaded field.
	googledrivesyncDescFilesDownloaded := googledrivesyncFields[8].Descriptor()
	// googledrivesync.DefaultFilesDownloaded holds the default value on creation for the files_downloaded field.
	googledrivesync.DefaultFilesDownloaded = googledrivesyncDescFilesDownloaded.Default.(int)
	// googledrivesyncDescFilesUploaded is the schema descriptor for files_uploaded field.
	googledrivesyncDescFilesUploaded := googledrivesyncFields[9].Descriptor()
	// googledrivesync.DefaultFilesUploaded holds the default value on creation for the files_uploaded field.
	googledrivesync.DefaultFilesUploaded = googledrivesyncDescFilesUploaded.Default.(int)
	// googledrivesyncDescFilesDeleted is the schema descriptor for files_deleted field.
	googledrivesyncDescFilesDeleted := googledrivesyncFields[10].Descriptor()
	// googledrivesync.DefaultFilesDeleted holds the default value on creation for the files_deleted field.
	googledrivesync.DefaultFilesDeleted = googledrivesyncDescFilesDeleted.Default.(int)
	// googledrivesyncDescFilesFailed is the schema descriptor for files_failed field.
	googledrivesyncDescFilesFailed := googledrivesyncFields[11].Descriptor()
	// googledrivesync.DefaultFilesFailed holds the default value on creation for the files_failed field.
	googledrivesync.DefaultFilesFailed = googledrivesyncDescFilesFailed.Default.(int)
	// googledrivesyncDescBytesTransferred is the schema descriptor for bytes_transferred field.
	googledrivesyncDescBytesTransferred := googledrivesyncFields[12].Descriptor()
	// googledrivesync.DefaultBytesTransferred holds the default value on creation for the bytes_transferred field.
	googledrivesync.DefaultBytesTransferred = googledrivesyncDescBytesTransferred.Default.(int64)
	// googledrivesyncDescCreatedAt is the schema descriptor for created_at field.
	googledrivesyncDescCreatedAt := googledrivesyncFields[16].Descriptor()
	// googledrivesync.DefaultCreatedAt holds the default value on creation for the created_at field.
	googledrivesync.DefaultCreatedAt = googledrivesyncDescCreatedAt.Default.(func() time.Time)
	// googledrivesyncDescUpdatedAt is the schema descriptor for updated_at field.
	googledrivesyncDescUpdatedAt := googledrivesyncFields[17].Descriptor()
	// googledrivesync.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	googledrivesync.DefaultUpdatedAt = googledrivesyncDescUpdatedAt.Default.(func() time.Time)
	// googledrivesync.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	googledrivesync.UpdateDefaultUpdatedAt = googledrivesyncDescUpdatedAt.UpdateDefault.(func() time.Time)
}
