// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GoogleDriveConnection is the predicate function for googledriveconnection builders.
type GoogleDriveConnection func(*sql.Selector)

// GoogleDriveFolder is the predicate function for googledrivefolder builders.
type GoogleDriveFolder func(*sql.Selector)

// GoogleDriveSync is the predicate function for googledrivesync builders.
type GoogleDriveSync func(*sql.Selector)
