// Code generated by ent, DO NOT EDIT.

package lineitem

import (
	"clockzen-next/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldID, id))
}

// ReceiptID applies equality check predicate on the "receipt_id" field. It's identical to ReceiptIDEQ.
func ReceiptID(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldReceiptID, v))
}

// LineNumber applies equality check predicate on the "line_number" field. It's identical to LineNumberEQ.
func LineNumber(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldLineNumber, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDescription, v))
}

// Sku applies equality check predicate on the "sku" field. It's identical to SkuEQ.
func Sku(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldSku, v))
}

// ProductCode applies equality check predicate on the "product_code" field. It's identical to ProductCodeEQ.
func ProductCode(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldProductCode, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldQuantity, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUnit, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUnitPrice, v))
}

// TotalPrice applies equality check predicate on the "total_price" field. It's identical to TotalPriceEQ.
func TotalPrice(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTotalPrice, v))
}

// DiscountAmount applies equality check predicate on the "discount_amount" field. It's identical to DiscountAmountEQ.
func DiscountAmount(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDiscountAmount, v))
}

// DiscountDescription applies equality check predicate on the "discount_description" field. It's identical to DiscountDescriptionEQ.
func DiscountDescription(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDiscountDescription, v))
}

// TaxAmount applies equality check predicate on the "tax_amount" field. It's identical to TaxAmountEQ.
func TaxAmount(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTaxAmount, v))
}

// TaxRate applies equality check predicate on the "tax_rate" field. It's identical to TaxRateEQ.
func TaxRate(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTaxRate, v))
}

// IsTaxable applies equality check predicate on the "is_taxable" field. It's identical to IsTaxableEQ.
func IsTaxable(v bool) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldIsTaxable, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldCategory, v))
}

// LegacyID applies equality check predicate on the "legacy_id" field. It's identical to LegacyIDEQ.
func LegacyID(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldLegacyID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReceiptIDEQ applies the EQ predicate on the "receipt_id" field.
func ReceiptIDEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldReceiptID, v))
}

// ReceiptIDNEQ applies the NEQ predicate on the "receipt_id" field.
func ReceiptIDNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldReceiptID, v))
}

// ReceiptIDIn applies the In predicate on the "receipt_id" field.
func ReceiptIDIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldReceiptID, vs...))
}

// ReceiptIDNotIn applies the NotIn predicate on the "receipt_id" field.
func ReceiptIDNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldReceiptID, vs...))
}

// ReceiptIDGT applies the GT predicate on the "receipt_id" field.
func ReceiptIDGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldReceiptID, v))
}

// ReceiptIDGTE applies the GTE predicate on the "receipt_id" field.
func ReceiptIDGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldReceiptID, v))
}

// ReceiptIDLT applies the LT predicate on the "receipt_id" field.
func ReceiptIDLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldReceiptID, v))
}

// ReceiptIDLTE applies the LTE predicate on the "receipt_id" field.
func ReceiptIDLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldReceiptID, v))
}

// ReceiptIDContains applies the Contains predicate on the "receipt_id" field.
func ReceiptIDContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldReceiptID, v))
}

// ReceiptIDHasPrefix applies the HasPrefix predicate on the "receipt_id" field.
func ReceiptIDHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldReceiptID, v))
}

// ReceiptIDHasSuffix applies the HasSuffix predicate on the "receipt_id" field.
func ReceiptIDHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldReceiptID, v))
}

// ReceiptIDEqualFold applies the EqualFold predicate on the "receipt_id" field.
func ReceiptIDEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldReceiptID, v))
}

// ReceiptIDContainsFold applies the ContainsFold predicate on the "receipt_id" field.
func ReceiptIDContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldReceiptID, v))
}

// LineNumberEQ applies the EQ predicate on the "line_number" field.
func LineNumberEQ(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldLineNumber, v))
}

// LineNumberNEQ applies the NEQ predicate on the "line_number" field.
func LineNumberNEQ(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldLineNumber, v))
}

// LineNumberIn applies the In predicate on the "line_number" field.
func LineNumberIn(vs ...int) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldLineNumber, vs...))
}

// LineNumberNotIn applies the NotIn predicate on the "line_number" field.
func LineNumberNotIn(vs ...int) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldLineNumber, vs...))
}

// LineNumberGT applies the GT predicate on the "line_number" field.
func LineNumberGT(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldLineNumber, v))
}

// LineNumberGTE applies the GTE predicate on the "line_number" field.
func LineNumberGTE(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldLineNumber, v))
}

// LineNumberLT applies the LT predicate on the "line_number" field.
func LineNumberLT(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldLineNumber, v))
}

// LineNumberLTE applies the LTE predicate on the "line_number" field.
func LineNumberLTE(v int) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldLineNumber, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldDescription, v))
}

// SkuEQ applies the EQ predicate on the "sku" field.
func SkuEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldSku, v))
}

// SkuNEQ applies the NEQ predicate on the "sku" field.
func SkuNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldSku, v))
}

// SkuIn applies the In predicate on the "sku" field.
func SkuIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldSku, vs...))
}

// SkuNotIn applies the NotIn predicate on the "sku" field.
func SkuNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldSku, vs...))
}

// SkuGT applies the GT predicate on the "sku" field.
func SkuGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldSku, v))
}

// SkuGTE applies the GTE predicate on the "sku" field.
func SkuGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldSku, v))
}

// SkuLT applies the LT predicate on the "sku" field.
func SkuLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldSku, v))
}

// SkuLTE applies the LTE predicate on the "sku" field.
func SkuLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldSku, v))
}

// SkuContains applies the Contains predicate on the "sku" field.
func SkuContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldSku, v))
}

// SkuHasPrefix applies the HasPrefix predicate on the "sku" field.
func SkuHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldSku, v))
}

// SkuHasSuffix applies the HasSuffix predicate on the "sku" field.
func SkuHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldSku, v))
}

// SkuIsNil applies the IsNil predicate on the "sku" field.
func SkuIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldSku))
}

// SkuNotNil applies the NotNil predicate on the "sku" field.
func SkuNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldSku))
}

// SkuEqualFold applies the EqualFold predicate on the "sku" field.
func SkuEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldSku, v))
}

// SkuContainsFold applies the ContainsFold predicate on the "sku" field.
func SkuContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldSku, v))
}

// ProductCodeEQ applies the EQ predicate on the "product_code" field.
func ProductCodeEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldProductCode, v))
}

// ProductCodeNEQ applies the NEQ predicate on the "product_code" field.
func ProductCodeNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldProductCode, v))
}

// ProductCodeIn applies the In predicate on the "product_code" field.
func ProductCodeIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldProductCode, vs...))
}

// ProductCodeNotIn applies the NotIn predicate on the "product_code" field.
func ProductCodeNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldProductCode, vs...))
}

// ProductCodeGT applies the GT predicate on the "product_code" field.
func ProductCodeGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldProductCode, v))
}

// ProductCodeGTE applies the GTE predicate on the "product_code" field.
func ProductCodeGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldProductCode, v))
}

// ProductCodeLT applies the LT predicate on the "product_code" field.
func ProductCodeLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldProductCode, v))
}

// ProductCodeLTE applies the LTE predicate on the "product_code" field.
func ProductCodeLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldProductCode, v))
}

// ProductCodeContains applies the Contains predicate on the "product_code" field.
func ProductCodeContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldProductCode, v))
}

// ProductCodeHasPrefix applies the HasPrefix predicate on the "product_code" field.
func ProductCodeHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldProductCode, v))
}

// ProductCodeHasSuffix applies the HasSuffix predicate on the "product_code" field.
func ProductCodeHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldProductCode, v))
}

// ProductCodeIsNil applies the IsNil predicate on the "product_code" field.
func ProductCodeIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldProductCode))
}

// ProductCodeNotNil applies the NotNil predicate on the "product_code" field.
func ProductCodeNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldProductCode))
}

// ProductCodeEqualFold applies the EqualFold predicate on the "product_code" field.
func ProductCodeEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldProductCode, v))
}

// ProductCodeContainsFold applies the ContainsFold predicate on the "product_code" field.
func ProductCodeContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldProductCode, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldQuantity, v))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitIsNil applies the IsNil predicate on the "unit" field.
func UnitIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldUnit))
}

// UnitNotNil applies the NotNil predicate on the "unit" field.
func UnitNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldUnit))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldUnit, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldUnitPrice, v))
}

// TotalPriceEQ applies the EQ predicate on the "total_price" field.
func TotalPriceEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTotalPrice, v))
}

// TotalPriceNEQ applies the NEQ predicate on the "total_price" field.
func TotalPriceNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldTotalPrice, v))
}

// TotalPriceIn applies the In predicate on the "total_price" field.
func TotalPriceIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldTotalPrice, vs...))
}

// TotalPriceNotIn applies the NotIn predicate on the "total_price" field.
func TotalPriceNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldTotalPrice, vs...))
}

// TotalPriceGT applies the GT predicate on the "total_price" field.
func TotalPriceGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldTotalPrice, v))
}

// TotalPriceGTE applies the GTE predicate on the "total_price" field.
func TotalPriceGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldTotalPrice, v))
}

// TotalPriceLT applies the LT predicate on the "total_price" field.
func TotalPriceLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldTotalPrice, v))
}

// TotalPriceLTE applies the LTE predicate on the "total_price" field.
func TotalPriceLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldTotalPrice, v))
}

// DiscountAmountEQ applies the EQ predicate on the "discount_amount" field.
func DiscountAmountEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDiscountAmount, v))
}

// DiscountAmountNEQ applies the NEQ predicate on the "discount_amount" field.
func DiscountAmountNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldDiscountAmount, v))
}

// DiscountAmountIn applies the In predicate on the "discount_amount" field.
func DiscountAmountIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldDiscountAmount, vs...))
}

// DiscountAmountNotIn applies the NotIn predicate on the "discount_amount" field.
func DiscountAmountNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldDiscountAmount, vs...))
}

// DiscountAmountGT applies the GT predicate on the "discount_amount" field.
func DiscountAmountGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldDiscountAmount, v))
}

// DiscountAmountGTE applies the GTE predicate on the "discount_amount" field.
func DiscountAmountGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldDiscountAmount, v))
}

// DiscountAmountLT applies the LT predicate on the "discount_amount" field.
func DiscountAmountLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldDiscountAmount, v))
}

// DiscountAmountLTE applies the LTE predicate on the "discount_amount" field.
func DiscountAmountLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldDiscountAmount, v))
}

// DiscountAmountIsNil applies the IsNil predicate on the "discount_amount" field.
func DiscountAmountIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldDiscountAmount))
}

// DiscountAmountNotNil applies the NotNil predicate on the "discount_amount" field.
func DiscountAmountNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldDiscountAmount))
}

// DiscountDescriptionEQ applies the EQ predicate on the "discount_description" field.
func DiscountDescriptionEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldDiscountDescription, v))
}

// DiscountDescriptionNEQ applies the NEQ predicate on the "discount_description" field.
func DiscountDescriptionNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldDiscountDescription, v))
}

// DiscountDescriptionIn applies the In predicate on the "discount_description" field.
func DiscountDescriptionIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldDiscountDescription, vs...))
}

// DiscountDescriptionNotIn applies the NotIn predicate on the "discount_description" field.
func DiscountDescriptionNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldDiscountDescription, vs...))
}

// DiscountDescriptionGT applies the GT predicate on the "discount_description" field.
func DiscountDescriptionGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldDiscountDescription, v))
}

// DiscountDescriptionGTE applies the GTE predicate on the "discount_description" field.
func DiscountDescriptionGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldDiscountDescription, v))
}

// DiscountDescriptionLT applies the LT predicate on the "discount_description" field.
func DiscountDescriptionLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldDiscountDescription, v))
}

// DiscountDescriptionLTE applies the LTE predicate on the "discount_description" field.
func DiscountDescriptionLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldDiscountDescription, v))
}

// DiscountDescriptionContains applies the Contains predicate on the "discount_description" field.
func DiscountDescriptionContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldDiscountDescription, v))
}

// DiscountDescriptionHasPrefix applies the HasPrefix predicate on the "discount_description" field.
func DiscountDescriptionHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldDiscountDescription, v))
}

// DiscountDescriptionHasSuffix applies the HasSuffix predicate on the "discount_description" field.
func DiscountDescriptionHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldDiscountDescription, v))
}

// DiscountDescriptionIsNil applies the IsNil predicate on the "discount_description" field.
func DiscountDescriptionIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldDiscountDescription))
}

// DiscountDescriptionNotNil applies the NotNil predicate on the "discount_description" field.
func DiscountDescriptionNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldDiscountDescription))
}

// DiscountDescriptionEqualFold applies the EqualFold predicate on the "discount_description" field.
func DiscountDescriptionEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldDiscountDescription, v))
}

// DiscountDescriptionContainsFold applies the ContainsFold predicate on the "discount_description" field.
func DiscountDescriptionContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldDiscountDescription, v))
}

// TaxAmountEQ applies the EQ predicate on the "tax_amount" field.
func TaxAmountEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTaxAmount, v))
}

// TaxAmountNEQ applies the NEQ predicate on the "tax_amount" field.
func TaxAmountNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldTaxAmount, v))
}

// TaxAmountIn applies the In predicate on the "tax_amount" field.
func TaxAmountIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldTaxAmount, vs...))
}

// TaxAmountNotIn applies the NotIn predicate on the "tax_amount" field.
func TaxAmountNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldTaxAmount, vs...))
}

// TaxAmountGT applies the GT predicate on the "tax_amount" field.
func TaxAmountGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldTaxAmount, v))
}

// TaxAmountGTE applies the GTE predicate on the "tax_amount" field.
func TaxAmountGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldTaxAmount, v))
}

// TaxAmountLT applies the LT predicate on the "tax_amount" field.
func TaxAmountLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldTaxAmount, v))
}

// TaxAmountLTE applies the LTE predicate on the "tax_amount" field.
func TaxAmountLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldTaxAmount, v))
}

// TaxAmountIsNil applies the IsNil predicate on the "tax_amount" field.
func TaxAmountIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldTaxAmount))
}

// TaxAmountNotNil applies the NotNil predicate on the "tax_amount" field.
func TaxAmountNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldTaxAmount))
}

// TaxRateEQ applies the EQ predicate on the "tax_rate" field.
func TaxRateEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldTaxRate, v))
}

// TaxRateNEQ applies the NEQ predicate on the "tax_rate" field.
func TaxRateNEQ(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldTaxRate, v))
}

// TaxRateIn applies the In predicate on the "tax_rate" field.
func TaxRateIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldTaxRate, vs...))
}

// TaxRateNotIn applies the NotIn predicate on the "tax_rate" field.
func TaxRateNotIn(vs ...float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldTaxRate, vs...))
}

// TaxRateGT applies the GT predicate on the "tax_rate" field.
func TaxRateGT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldTaxRate, v))
}

// TaxRateGTE applies the GTE predicate on the "tax_rate" field.
func TaxRateGTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldTaxRate, v))
}

// TaxRateLT applies the LT predicate on the "tax_rate" field.
func TaxRateLT(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldTaxRate, v))
}

// TaxRateLTE applies the LTE predicate on the "tax_rate" field.
func TaxRateLTE(v float64) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldTaxRate, v))
}

// TaxRateIsNil applies the IsNil predicate on the "tax_rate" field.
func TaxRateIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldTaxRate))
}

// TaxRateNotNil applies the NotNil predicate on the "tax_rate" field.
func TaxRateNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldTaxRate))
}

// IsTaxableEQ applies the EQ predicate on the "is_taxable" field.
func IsTaxableEQ(v bool) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldIsTaxable, v))
}

// IsTaxableNEQ applies the NEQ predicate on the "is_taxable" field.
func IsTaxableNEQ(v bool) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldIsTaxable, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldCategory, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldTags))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldMetadata))
}

// LegacyIDEQ applies the EQ predicate on the "legacy_id" field.
func LegacyIDEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldLegacyID, v))
}

// LegacyIDNEQ applies the NEQ predicate on the "legacy_id" field.
func LegacyIDNEQ(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldLegacyID, v))
}

// LegacyIDIn applies the In predicate on the "legacy_id" field.
func LegacyIDIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldLegacyID, vs...))
}

// LegacyIDNotIn applies the NotIn predicate on the "legacy_id" field.
func LegacyIDNotIn(vs ...string) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldLegacyID, vs...))
}

// LegacyIDGT applies the GT predicate on the "legacy_id" field.
func LegacyIDGT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldLegacyID, v))
}

// LegacyIDGTE applies the GTE predicate on the "legacy_id" field.
func LegacyIDGTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldLegacyID, v))
}

// LegacyIDLT applies the LT predicate on the "legacy_id" field.
func LegacyIDLT(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldLegacyID, v))
}

// LegacyIDLTE applies the LTE predicate on the "legacy_id" field.
func LegacyIDLTE(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldLegacyID, v))
}

// LegacyIDContains applies the Contains predicate on the "legacy_id" field.
func LegacyIDContains(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContains(FieldLegacyID, v))
}

// LegacyIDHasPrefix applies the HasPrefix predicate on the "legacy_id" field.
func LegacyIDHasPrefix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasPrefix(FieldLegacyID, v))
}

// LegacyIDHasSuffix applies the HasSuffix predicate on the "legacy_id" field.
func LegacyIDHasSuffix(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldHasSuffix(FieldLegacyID, v))
}

// LegacyIDIsNil applies the IsNil predicate on the "legacy_id" field.
func LegacyIDIsNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldIsNull(FieldLegacyID))
}

// LegacyIDNotNil applies the NotNil predicate on the "legacy_id" field.
func LegacyIDNotNil() predicate.LineItem {
	return predicate.LineItem(sql.FieldNotNull(FieldLegacyID))
}

// LegacyIDEqualFold applies the EqualFold predicate on the "legacy_id" field.
func LegacyIDEqualFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldEqualFold(FieldLegacyID, v))
}

// LegacyIDContainsFold applies the ContainsFold predicate on the "legacy_id" field.
func LegacyIDContainsFold(v string) predicate.LineItem {
	return predicate.LineItem(sql.FieldContainsFold(FieldLegacyID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LineItem {
	return predicate.LineItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasReceipt applies the HasEdge predicate on the "receipt" edge.
func HasReceipt() predicate.LineItem {
	return predicate.LineItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReceiptTable, ReceiptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReceiptWith applies the HasEdge predicate on the "receipt" edge with a given conditions (other predicates).
func HasReceiptWith(preds ...predicate.Receipt) predicate.LineItem {
	return predicate.LineItem(func(s *sql.Selector) {
		step := newReceiptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LineItem) predicate.LineItem {
	return predicate.LineItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LineItem) predicate.LineItem {
	return predicate.LineItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LineItem) predicate.LineItem {
	return predicate.LineItem(sql.NotPredicates(p))
}
