// Code generated by ent, DO NOT EDIT.

package pipelineconfig

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pipelineconfig type in the database.
	Label = "pipeline_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPipelineType holds the string denoting the pipeline_type field in the database.
	FieldPipelineType = "pipeline_type"
	// FieldTriggerType holds the string denoting the trigger_type field in the database.
	FieldTriggerType = "trigger_type"
	// FieldTriggerConfig holds the string denoting the trigger_config field in the database.
	FieldTriggerConfig = "trigger_config"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldCurrentVersion holds the string denoting the current_version field in the database.
	FieldCurrentVersion = "current_version"
	// FieldSettings holds the string denoting the settings field in the database.
	FieldSettings = "settings"
	// FieldInputSchema holds the string denoting the input_schema field in the database.
	FieldInputSchema = "input_schema"
	// FieldOutputSchema holds the string denoting the output_schema field in the database.
	FieldOutputSchema = "output_schema"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldExecutionCount holds the string denoting the execution_count field in the database.
	FieldExecutionCount = "execution_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldFailureCount holds the string denoting the failure_count field in the database.
	FieldFailureCount = "failure_count"
	// FieldLastExecutedAt holds the string denoting the last_executed_at field in the database.
	FieldLastExecutedAt = "last_executed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRules holds the string denoting the rules edge name in mutations.
	EdgeRules = "rules"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// Table holds the table name of the pipelineconfig in the database.
	Table = "pipeline_configs"
	// RulesTable is the table that holds the rules relation/edge.
	RulesTable = "pipeline_rules"
	// RulesInverseTable is the table name for the PipelineRule entity.
	// It exists in this package in order to avoid circular dependency with the "pipelinerule" package.
	RulesInverseTable = "pipeline_rules"
	// RulesColumn is the table column denoting the rules relation/edge.
	RulesColumn = "config_id"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "pipeline_versions"
	// VersionsInverseTable is the table name for the PipelineVersion entity.
	// It exists in this package in order to avoid circular dependency with the "pipelineversion" package.
	VersionsInverseTable = "pipeline_versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "config_id"
)

// Columns holds all SQL columns for pipelineconfig fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldDescription,
	FieldPipelineType,
	FieldTriggerType,
	FieldTriggerConfig,
	FieldEnabled,
	FieldIsDefault,
	FieldCurrentVersion,
	FieldSettings,
	FieldInputSchema,
	FieldOutputSchema,
	FieldTags,
	FieldExecutionCount,
	FieldSuccessCount,
	FieldFailureCount,
	FieldLastExecutedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultCurrentVersion holds the default value on creation for the "current_version" field.
	DefaultCurrentVersion int
	// DefaultExecutionCount holds the default value on creation for the "execution_count" field.
	DefaultExecutionCount int
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// DefaultFailureCount holds the default value on creation for the "failure_count" field.
	DefaultFailureCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// PipelineType defines the type for the "pipeline_type" enum field.
type PipelineType string

// PipelineType values.
const (
	PipelineTypeReceiptProcessing PipelineType = "receipt_processing"
	PipelineTypeEmailParsing      PipelineType = "email_parsing"
	PipelineTypeCategorization    PipelineType = "categorization"
	PipelineTypeExport            PipelineType = "export"
	PipelineTypeNotification      PipelineType = "notification"
	PipelineTypeCustom            PipelineType = "custom"
)

func (pt PipelineType) String() string {
	return string(pt)
}

// PipelineTypeValidator is a validator for the "pipeline_type" field enum values. It is called by the builders before save.
func PipelineTypeValidator(pt PipelineType) error {
	switch pt {
	case PipelineTypeReceiptProcessing, PipelineTypeEmailParsing, PipelineTypeCategorization, PipelineTypeExport, PipelineTypeNotification, PipelineTypeCustom:
		return nil
	default:
		return fmt.Errorf("pipelineconfig: invalid enum value for pipeline_type field: %q", pt)
	}
}

// TriggerType defines the type for the "trigger_type" enum field.
type TriggerType string

// TriggerTypeManual is the default value of the TriggerType enum.
const DefaultTriggerType = TriggerTypeManual

// TriggerType values.
const (
	TriggerTypeManual    TriggerType = "manual"
	TriggerTypeOnReceipt TriggerType = "on_receipt"
	TriggerTypeOnSync    TriggerType = "on_sync"
	TriggerTypeScheduled TriggerType = "scheduled"
	TriggerTypeWebhook   TriggerType = "webhook"
)

func (tt TriggerType) String() string {
	return string(tt)
}

// TriggerTypeValidator is a validator for the "trigger_type" field enum values. It is called by the builders before save.
func TriggerTypeValidator(tt TriggerType) error {
	switch tt {
	case TriggerTypeManual, TriggerTypeOnReceipt, TriggerTypeOnSync, TriggerTypeScheduled, TriggerTypeWebhook:
		return nil
	default:
		return fmt.Errorf("pipelineconfig: invalid enum value for trigger_type field: %q", tt)
	}
}

// OrderOption defines the ordering options for the PipelineConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPipelineType orders the results by the pipeline_type field.
func ByPipelineType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPipelineType, opts...).ToFunc()
}

// ByTriggerType orders the results by the trigger_type field.
func ByTriggerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerType, opts...).ToFunc()
}

// ByTriggerConfig orders the results by the trigger_config field.
func ByTriggerConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerConfig, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByCurrentVersion orders the results by the current_version field.
func ByCurrentVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentVersion, opts...).ToFunc()
}

// ByExecutionCount orders the results by the execution_count field.
func ByExecutionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByFailureCount orders the results by the failure_count field.
func ByFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCount, opts...).ToFunc()
}

// ByLastExecutedAt orders the results by the last_executed_at field.
func ByLastExecutedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastExecutedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRulesCount orders the results by rules count.
func ByRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRulesStep(), opts...)
	}
}

// ByRules orders the results by rules terms.
func ByRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RulesTable, RulesColumn),
	)
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
	)
}
