// Code generated by ent, DO NOT EDIT.

package emailconnection

import (
	"clockzen-next/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldUserID, v))
}

// ProviderAccountID applies equality check predicate on the "provider_account_id" field. It's identical to ProviderAccountIDEQ.
func ProviderAccountID(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldProviderAccountID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldEmail, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// TokenExpiry applies equality check predicate on the "token_expiry" field. It's identical to TokenExpiryEQ.
func TokenExpiry(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldTokenExpiry, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldLastSyncAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldUserID, v))
}

// ProviderAccountIDEQ applies the EQ predicate on the "provider_account_id" field.
func ProviderAccountIDEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDNEQ applies the NEQ predicate on the "provider_account_id" field.
func ProviderAccountIDNEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDIn applies the In predicate on the "provider_account_id" field.
func ProviderAccountIDIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDNotIn applies the NotIn predicate on the "provider_account_id" field.
func ProviderAccountIDNotIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDGT applies the GT predicate on the "provider_account_id" field.
func ProviderAccountIDGT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldProviderAccountID, v))
}

// ProviderAccountIDGTE applies the GTE predicate on the "provider_account_id" field.
func ProviderAccountIDGTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldProviderAccountID, v))
}

// ProviderAccountIDLT applies the LT predicate on the "provider_account_id" field.
func ProviderAccountIDLT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldProviderAccountID, v))
}

// ProviderAccountIDLTE applies the LTE predicate on the "provider_account_id" field.
func ProviderAccountIDLTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldProviderAccountID, v))
}

// ProviderAccountIDContains applies the Contains predicate on the "provider_account_id" field.
func ProviderAccountIDContains(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContains(FieldProviderAccountID, v))
}

// ProviderAccountIDHasPrefix applies the HasPrefix predicate on the "provider_account_id" field.
func ProviderAccountIDHasPrefix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasPrefix(FieldProviderAccountID, v))
}

// ProviderAccountIDHasSuffix applies the HasSuffix predicate on the "provider_account_id" field.
func ProviderAccountIDHasSuffix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasSuffix(FieldProviderAccountID, v))
}

// ProviderAccountIDEqualFold applies the EqualFold predicate on the "provider_account_id" field.
func ProviderAccountIDEqualFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldProviderAccountID, v))
}

// ProviderAccountIDContainsFold applies the ContainsFold predicate on the "provider_account_id" field.
func ProviderAccountIDContainsFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldProviderAccountID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldEmail, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldProvider, vs...))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldContainsFold(FieldRefreshToken, v))
}

// TokenExpiryEQ applies the EQ predicate on the "token_expiry" field.
func TokenExpiryEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldTokenExpiry, v))
}

// TokenExpiryNEQ applies the NEQ predicate on the "token_expiry" field.
func TokenExpiryNEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldTokenExpiry, v))
}

// TokenExpiryIn applies the In predicate on the "token_expiry" field.
func TokenExpiryIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldTokenExpiry, vs...))
}

// TokenExpiryNotIn applies the NotIn predicate on the "token_expiry" field.
func TokenExpiryNotIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldTokenExpiry, vs...))
}

// TokenExpiryGT applies the GT predicate on the "token_expiry" field.
func TokenExpiryGT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldTokenExpiry, v))
}

// TokenExpiryGTE applies the GTE predicate on the "token_expiry" field.
func TokenExpiryGTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldTokenExpiry, v))
}

// TokenExpiryLT applies the LT predicate on the "token_expiry" field.
func TokenExpiryLT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldTokenExpiry, v))
}

// TokenExpiryLTE applies the LTE predicate on the "token_expiry" field.
func TokenExpiryLTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldTokenExpiry, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.EmailConnection {
	return predicate.EmailConnection(sql.FieldNotNull(FieldLastSyncAt))
}

// HasLabels applies the HasEdge predicate on the "labels" edge.
func HasLabels() predicate.EmailConnection {
	return predicate.EmailConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LabelsTable, LabelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLabelsWith applies the HasEdge predicate on the "labels" edge with a given conditions (other predicates).
func HasLabelsWith(preds ...predicate.EmailLabel) predicate.EmailConnection {
	return predicate.EmailConnection(func(s *sql.Selector) {
		step := newLabelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyncs applies the HasEdge predicate on the "syncs" edge.
func HasSyncs() predicate.EmailConnection {
	return predicate.EmailConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncsTable, SyncsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncsWith applies the HasEdge predicate on the "syncs" edge with a given conditions (other predicates).
func HasSyncsWith(preds ...predicate.EmailSync) predicate.EmailConnection {
	return predicate.EmailConnection(func(s *sql.Selector) {
		step := newSyncsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailConnection) predicate.EmailConnection {
	return predicate.EmailConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailConnection) predicate.EmailConnection {
	return predicate.EmailConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailConnection) predicate.EmailConnection {
	return predicate.EmailConnection(sql.NotPredicates(p))
}
