// Code generated by ent, DO NOT EDIT.

package googledrivefolder

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the googledrivefolder type in the database.
	Label = "google_drive_folder"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldDriveFolderID holds the string denoting the drive_folder_id field in the database.
	FieldDriveFolderID = "drive_folder_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldParentFolderID holds the string denoting the parent_folder_id field in the database.
	FieldParentFolderID = "parent_folder_id"
	// FieldIsRoot holds the string denoting the is_root field in the database.
	FieldIsRoot = "is_root"
	// FieldSyncEnabled holds the string denoting the sync_enabled field in the database.
	FieldSyncEnabled = "sync_enabled"
	// FieldSyncDirection holds the string denoting the sync_direction field in the database.
	FieldSyncDirection = "sync_direction"
	// FieldFileCount holds the string denoting the file_count field in the database.
	FieldFileCount = "file_count"
	// FieldTotalSizeBytes holds the string denoting the total_size_bytes field in the database.
	FieldTotalSizeBytes = "total_size_bytes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastScannedAt holds the string denoting the last_scanned_at field in the database.
	FieldLastScannedAt = "last_scanned_at"
	// EdgeConnection holds the string denoting the connection edge name in mutations.
	EdgeConnection = "connection"
	// Table holds the table name of the googledrivefolder in the database.
	Table = "google_drive_folders"
	// ConnectionTable is the table that holds the connection relation/edge.
	ConnectionTable = "google_drive_folders"
	// ConnectionInverseTable is the table name for the GoogleDriveConnection entity.
	// It exists in this package in order to avoid circular dependency with the "googledriveconnection" package.
	ConnectionInverseTable = "google_drive_connections"
	// ConnectionColumn is the table column denoting the connection relation/edge.
	ConnectionColumn = "connection_id"
)

// Columns holds all SQL columns for googledrivefolder fields.
var Columns = []string{
	FieldID,
	FieldConnectionID,
	FieldDriveFolderID,
	FieldName,
	FieldPath,
	FieldParentFolderID,
	FieldIsRoot,
	FieldSyncEnabled,
	FieldSyncDirection,
	FieldFileCount,
	FieldTotalSizeBytes,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLastScannedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	ConnectionIDValidator func(string) error
	// DriveFolderIDValidator is a validator for the "drive_folder_id" field. It is called by the builders before save.
	DriveFolderIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsRoot holds the default value on creation for the "is_root" field.
	DefaultIsRoot bool
	// DefaultSyncEnabled holds the default value on creation for the "sync_enabled" field.
	DefaultSyncEnabled bool
	// DefaultFileCount holds the default value on creation for the "file_count" field.
	DefaultFileCount int64
	// DefaultTotalSizeBytes holds the default value on creation for the "total_size_bytes" field.
	DefaultTotalSizeBytes int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// SyncDirection defines the type for the "sync_direction" enum field.
type SyncDirection string

// SyncDirectionDownload is the default value of the SyncDirection enum.
const DefaultSyncDirection = SyncDirectionDownload

// SyncDirection values.
const (
	SyncDirectionDownload      SyncDirection = "download"
	SyncDirectionUpload        SyncDirection = "upload"
	SyncDirectionBidirectional SyncDirection = "bidirectional"
)

func (sd SyncDirection) String() string {
	return string(sd)
}

// SyncDirectionValidator is a validator for the "sync_direction" field enum values. It is called by the builders before save.
func SyncDirectionValidator(sd SyncDirection) error {
	switch sd {
	case SyncDirectionDownload, SyncDirectionUpload, SyncDirectionBidirectional:
		return nil
	default:
		return fmt.Errorf("googledrivefolder: invalid enum value for sync_direction field: %q", sd)
	}
}

// OrderOption defines the ordering options for the GoogleDriveFolder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByDriveFolderID orders the results by the drive_folder_id field.
func ByDriveFolderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriveFolderID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByParentFolderID orders the results by the parent_folder_id field.
func ByParentFolderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentFolderID, opts...).ToFunc()
}

// ByIsRoot orders the results by the is_root field.
func ByIsRoot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRoot, opts...).ToFunc()
}

// BySyncEnabled orders the results by the sync_enabled field.
func BySyncEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncEnabled, opts...).ToFunc()
}

// BySyncDirection orders the results by the sync_direction field.
func BySyncDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncDirection, opts...).ToFunc()
}

// ByFileCount orders the results by the file_count field.
func ByFileCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileCount, opts...).ToFunc()
}

// ByTotalSizeBytes orders the results by the total_size_bytes field.
func ByTotalSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSizeBytes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastScannedAt orders the results by the last_scanned_at field.
func ByLastScannedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastScannedAt, opts...).ToFunc()
}

// ByConnectionField orders the results by connection field.
func ByConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionStep(), sql.OrderByField(field, opts...))
	}
}
func newConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
	)
}
