// Code generated by ent, DO NOT EDIT.

package googledrivefolder

import (
	"clockzen-next/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldID, id))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldConnectionID, v))
}

// DriveFolderID applies equality check predicate on the "drive_folder_id" field. It's identical to DriveFolderIDEQ.
func DriveFolderID(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldDriveFolderID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldPath, v))
}

// ParentFolderID applies equality check predicate on the "parent_folder_id" field. It's identical to ParentFolderIDEQ.
func ParentFolderID(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldParentFolderID, v))
}

// IsRoot applies equality check predicate on the "is_root" field. It's identical to IsRootEQ.
func IsRoot(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldIsRoot, v))
}

// SyncEnabled applies equality check predicate on the "sync_enabled" field. It's identical to SyncEnabledEQ.
func SyncEnabled(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldSyncEnabled, v))
}

// FileCount applies equality check predicate on the "file_count" field. It's identical to FileCountEQ.
func FileCount(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldFileCount, v))
}

// TotalSizeBytes applies equality check predicate on the "total_size_bytes" field. It's identical to TotalSizeBytesEQ.
func TotalSizeBytes(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastScannedAt applies equality check predicate on the "last_scanned_at" field. It's identical to LastScannedAtEQ.
func LastScannedAt(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldLastScannedAt, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDGT applies the GT predicate on the "connection_id" field.
func ConnectionIDGT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldConnectionID, v))
}

// ConnectionIDGTE applies the GTE predicate on the "connection_id" field.
func ConnectionIDGTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldConnectionID, v))
}

// ConnectionIDLT applies the LT predicate on the "connection_id" field.
func ConnectionIDLT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldConnectionID, v))
}

// ConnectionIDLTE applies the LTE predicate on the "connection_id" field.
func ConnectionIDLTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldConnectionID, v))
}

// ConnectionIDContains applies the Contains predicate on the "connection_id" field.
func ConnectionIDContains(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContains(FieldConnectionID, v))
}

// ConnectionIDHasPrefix applies the HasPrefix predicate on the "connection_id" field.
func ConnectionIDHasPrefix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasPrefix(FieldConnectionID, v))
}

// ConnectionIDHasSuffix applies the HasSuffix predicate on the "connection_id" field.
func ConnectionIDHasSuffix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasSuffix(FieldConnectionID, v))
}

// ConnectionIDEqualFold applies the EqualFold predicate on the "connection_id" field.
func ConnectionIDEqualFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldConnectionID, v))
}

// ConnectionIDContainsFold applies the ContainsFold predicate on the "connection_id" field.
func ConnectionIDContainsFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldConnectionID, v))
}

// DriveFolderIDEQ applies the EQ predicate on the "drive_folder_id" field.
func DriveFolderIDEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldDriveFolderID, v))
}

// DriveFolderIDNEQ applies the NEQ predicate on the "drive_folder_id" field.
func DriveFolderIDNEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldDriveFolderID, v))
}

// DriveFolderIDIn applies the In predicate on the "drive_folder_id" field.
func DriveFolderIDIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldDriveFolderID, vs...))
}

// DriveFolderIDNotIn applies the NotIn predicate on the "drive_folder_id" field.
func DriveFolderIDNotIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldDriveFolderID, vs...))
}

// DriveFolderIDGT applies the GT predicate on the "drive_folder_id" field.
func DriveFolderIDGT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldDriveFolderID, v))
}

// DriveFolderIDGTE applies the GTE predicate on the "drive_folder_id" field.
func DriveFolderIDGTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldDriveFolderID, v))
}

// DriveFolderIDLT applies the LT predicate on the "drive_folder_id" field.
func DriveFolderIDLT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldDriveFolderID, v))
}

// DriveFolderIDLTE applies the LTE predicate on the "drive_folder_id" field.
func DriveFolderIDLTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldDriveFolderID, v))
}

// DriveFolderIDContains applies the Contains predicate on the "drive_folder_id" field.
func DriveFolderIDContains(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContains(FieldDriveFolderID, v))
}

// DriveFolderIDHasPrefix applies the HasPrefix predicate on the "drive_folder_id" field.
func DriveFolderIDHasPrefix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasPrefix(FieldDriveFolderID, v))
}

// DriveFolderIDHasSuffix applies the HasSuffix predicate on the "drive_folder_id" field.
func DriveFolderIDHasSuffix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasSuffix(FieldDriveFolderID, v))
}

// DriveFolderIDEqualFold applies the EqualFold predicate on the "drive_folder_id" field.
func DriveFolderIDEqualFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldDriveFolderID, v))
}

// DriveFolderIDContainsFold applies the ContainsFold predicate on the "drive_folder_id" field.
func DriveFolderIDContainsFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldDriveFolderID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldPath, v))
}

// ParentFolderIDEQ applies the EQ predicate on the "parent_folder_id" field.
func ParentFolderIDEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldParentFolderID, v))
}

// ParentFolderIDNEQ applies the NEQ predicate on the "parent_folder_id" field.
func ParentFolderIDNEQ(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldParentFolderID, v))
}

// ParentFolderIDIn applies the In predicate on the "parent_folder_id" field.
func ParentFolderIDIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldParentFolderID, vs...))
}

// ParentFolderIDNotIn applies the NotIn predicate on the "parent_folder_id" field.
func ParentFolderIDNotIn(vs ...string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldParentFolderID, vs...))
}

// ParentFolderIDGT applies the GT predicate on the "parent_folder_id" field.
func ParentFolderIDGT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldParentFolderID, v))
}

// ParentFolderIDGTE applies the GTE predicate on the "parent_folder_id" field.
func ParentFolderIDGTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldParentFolderID, v))
}

// ParentFolderIDLT applies the LT predicate on the "parent_folder_id" field.
func ParentFolderIDLT(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldParentFolderID, v))
}

// ParentFolderIDLTE applies the LTE predicate on the "parent_folder_id" field.
func ParentFolderIDLTE(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldParentFolderID, v))
}

// ParentFolderIDContains applies the Contains predicate on the "parent_folder_id" field.
func ParentFolderIDContains(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContains(FieldParentFolderID, v))
}

// ParentFolderIDHasPrefix applies the HasPrefix predicate on the "parent_folder_id" field.
func ParentFolderIDHasPrefix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasPrefix(FieldParentFolderID, v))
}

// ParentFolderIDHasSuffix applies the HasSuffix predicate on the "parent_folder_id" field.
func ParentFolderIDHasSuffix(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldHasSuffix(FieldParentFolderID, v))
}

// ParentFolderIDIsNil applies the IsNil predicate on the "parent_folder_id" field.
func ParentFolderIDIsNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIsNull(FieldParentFolderID))
}

// ParentFolderIDNotNil applies the NotNil predicate on the "parent_folder_id" field.
func ParentFolderIDNotNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotNull(FieldParentFolderID))
}

// ParentFolderIDEqualFold applies the EqualFold predicate on the "parent_folder_id" field.
func ParentFolderIDEqualFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEqualFold(FieldParentFolderID, v))
}

// ParentFolderIDContainsFold applies the ContainsFold predicate on the "parent_folder_id" field.
func ParentFolderIDContainsFold(v string) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldContainsFold(FieldParentFolderID, v))
}

// IsRootEQ applies the EQ predicate on the "is_root" field.
func IsRootEQ(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldIsRoot, v))
}

// IsRootNEQ applies the NEQ predicate on the "is_root" field.
func IsRootNEQ(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldIsRoot, v))
}

// SyncEnabledEQ applies the EQ predicate on the "sync_enabled" field.
func SyncEnabledEQ(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldSyncEnabled, v))
}

// SyncEnabledNEQ applies the NEQ predicate on the "sync_enabled" field.
func SyncEnabledNEQ(v bool) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldSyncEnabled, v))
}

// SyncDirectionEQ applies the EQ predicate on the "sync_direction" field.
func SyncDirectionEQ(v SyncDirection) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldSyncDirection, v))
}

// SyncDirectionNEQ applies the NEQ predicate on the "sync_direction" field.
func SyncDirectionNEQ(v SyncDirection) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldSyncDirection, v))
}

// SyncDirectionIn applies the In predicate on the "sync_direction" field.
func SyncDirectionIn(vs ...SyncDirection) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldSyncDirection, vs...))
}

// SyncDirectionNotIn applies the NotIn predicate on the "sync_direction" field.
func SyncDirectionNotIn(vs ...SyncDirection) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldSyncDirection, vs...))
}

// FileCountEQ applies the EQ predicate on the "file_count" field.
func FileCountEQ(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldFileCount, v))
}

// FileCountNEQ applies the NEQ predicate on the "file_count" field.
func FileCountNEQ(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldFileCount, v))
}

// FileCountIn applies the In predicate on the "file_count" field.
func FileCountIn(vs ...int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldFileCount, vs...))
}

// FileCountNotIn applies the NotIn predicate on the "file_count" field.
func FileCountNotIn(vs ...int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldFileCount, vs...))
}

// FileCountGT applies the GT predicate on the "file_count" field.
func FileCountGT(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldFileCount, v))
}

// FileCountGTE applies the GTE predicate on the "file_count" field.
func FileCountGTE(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldFileCount, v))
}

// FileCountLT applies the LT predicate on the "file_count" field.
func FileCountLT(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldFileCount, v))
}

// FileCountLTE applies the LTE predicate on the "file_count" field.
func FileCountLTE(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldFileCount, v))
}

// TotalSizeBytesEQ applies the EQ predicate on the "total_size_bytes" field.
func TotalSizeBytesEQ(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesNEQ applies the NEQ predicate on the "total_size_bytes" field.
func TotalSizeBytesNEQ(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesIn applies the In predicate on the "total_size_bytes" field.
func TotalSizeBytesIn(vs ...int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesNotIn applies the NotIn predicate on the "total_size_bytes" field.
func TotalSizeBytesNotIn(vs ...int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesGT applies the GT predicate on the "total_size_bytes" field.
func TotalSizeBytesGT(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesGTE applies the GTE predicate on the "total_size_bytes" field.
func TotalSizeBytesGTE(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLT applies the LT predicate on the "total_size_bytes" field.
func TotalSizeBytesLT(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLTE applies the LTE predicate on the "total_size_bytes" field.
func TotalSizeBytesLTE(v int64) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldTotalSizeBytes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastScannedAtEQ applies the EQ predicate on the "last_scanned_at" field.
func LastScannedAtEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldEQ(FieldLastScannedAt, v))
}

// LastScannedAtNEQ applies the NEQ predicate on the "last_scanned_at" field.
func LastScannedAtNEQ(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNEQ(FieldLastScannedAt, v))
}

// LastScannedAtIn applies the In predicate on the "last_scanned_at" field.
func LastScannedAtIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIn(FieldLastScannedAt, vs...))
}

// LastScannedAtNotIn applies the NotIn predicate on the "last_scanned_at" field.
func LastScannedAtNotIn(vs ...time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotIn(FieldLastScannedAt, vs...))
}

// LastScannedAtGT applies the GT predicate on the "last_scanned_at" field.
func LastScannedAtGT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGT(FieldLastScannedAt, v))
}

// LastScannedAtGTE applies the GTE predicate on the "last_scanned_at" field.
func LastScannedAtGTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldGTE(FieldLastScannedAt, v))
}

// LastScannedAtLT applies the LT predicate on the "last_scanned_at" field.
func LastScannedAtLT(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLT(FieldLastScannedAt, v))
}

// LastScannedAtLTE applies the LTE predicate on the "last_scanned_at" field.
func LastScannedAtLTE(v time.Time) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldLTE(FieldLastScannedAt, v))
}

// LastScannedAtIsNil applies the IsNil predicate on the "last_scanned_at" field.
func LastScannedAtIsNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldIsNull(FieldLastScannedAt))
}

// LastScannedAtNotNil applies the NotNil predicate on the "last_scanned_at" field.
func LastScannedAtNotNil() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.FieldNotNull(FieldLastScannedAt))
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.GoogleDriveConnection) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GoogleDriveFolder) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GoogleDriveFolder) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GoogleDriveFolder) predicate.GoogleDriveFolder {
	return predicate.GoogleDriveFolder(sql.NotPredicates(p))
}
